### ISSUE TITLE
CMS Pages don't render

### ISSUE THREAD

**Issue by rossmc** [magento-research/pwa-studio#1002]
**Describe the bug**
CMS Pages don't render when I try to navigate to a URL for a CMS Page on the Venia storefront.

**To Reproduce**
1. Go to '/privacy-policy-cookie-restriction-mode' on Venia Storefront
2. See error
`ENOENT: no such file or directory, stat '/Users/ross/Projects/pwa-temp/packages/venia-concept/dist/privacy-policy-cookie-restriction-mode'`

*Update*
If you add `.html` to the end of the URL, you get a different error in the browser console:

![Screenshot 2019-03-26 at 11 09 33](https://user-images.githubusercontent.com/2452991/54988900-aeb1ad00-4fb7-11e9-9a69-c9b9a386869e.png)

**Expected behavior**
The CMS Page to load with it's content set in the Magento Admin Panel.

**Screenshots**
https://user-images.githubusercontent.com/2452991/54025192-14213380-419a-11e9-907f-862a9eef0854.png

**Please complete the following device information:**
 - Device: macbook pro
 - OS: Osx mojave
 - Browser chrome
 - Version 72
 - Magento Version 2.3
 - NPM version `6.7.0`
 - Node Version `v11.10.1`

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Additional context**
- The page loads on the Luma storefront.
- I'm using a local magento backend.

**Possible solutions**
The GraphQL query works when I test it in a GraphiQl...
![screenshot 2019-03-08 at 12 05 37](https://user-images.githubusercontent.com/2452991/54025342-872aaa00-419a-11e9-816d-ac4a8e73c11a.png)

**Comment by danrcoull** [comment]
#1029 See the pull request, here i had the same issue but this is how i got arround the issue

**Comment by rossmc** [comment]
Thanks @danrcoull, but when I applied the [changes from your PR](https://github.com/magento-research/pwa-studio/pull/1029/files) I still get the same errors when I browser to either

- https://magento-venia-concept-zyktx.local.pwadev:8886/privacy-policy-cookie-restriction-mode.html
- https://magento-venia-concept-zyktx.local.pwadev:8886/privacy-policy-cookie-restriction-mode

Can you browser to those URLs on your local?

**Comment by danrcoull** [comment]
does the cms page with that url key exist in magento ?

**Comment by rossmc** [comment]
Yes, that URL exists out-of-the-box on all M2 instances.  I also double checked it exists with Graph**i**QL.
```graphql
{
  urlResolver(url: "/privacy-policy-cookie-restriction-mode") {
    type
    id
  }
}
```
Use this public endpoint used by PWA Studio:
https://release-dev-231-npzdaky-zddsyhrdimyra.us-4.magentosite.cloud/graphql

The GraphQL response is:
```graphql
{
  "data": {
    "urlResolver": {
      "type": "CMS_PAGE",
      "id": 4
    }
  }
}
```

**Comment by awilcoxa** [comment]
This isn't a bug but a feature request for pulling in CMS content from Magento backend, currently a gap. closing this as a defect and will track through a feature request.
