### ISSUE TITLE
[DOCUMENTATION] Project and coding standard

### ISSUE THREAD

**Issue by jcalcaben** [magento-research/pwa-studio#1008]
Create a topic that lay out guidelines for working with and on PWA Studio.

**Comment by jcalcaben** [comment]
Link to internal wiki page:
https://wiki.corp.magento.com/display/FF/Project+and+Coding+Standard

**Comment by supernova-at** [comment]
This is looking good! Everyone on the team should probably take a look at this.

**Comment by sirugh** [comment]
This is nice. I'd like to see as much of this represented in some form of linting that could be automatically applied by the IDE.

**Comment by jcalcaben** [comment]
Internal reviews and feedback gathered so this issue can be closed. Work will continue in #1079
