### ISSUE TITLE
UAT: Swatch Tooltips

### ISSUE THREAD

**Issue by supernova-at** [magento-research/pwa-studio#1024]
The Swatch Tooltips on configurable products (pretty much any product in the "Top" category will do) need to be updated: 

![image.png](https://images.zenhubusercontent.com/5bef16763560017fb6812f47/e401c2f8-5734-4fbe-8fb1-33423a3494e5)

![Screen Shot 2019-03-19 at 11 51 47 AM](https://user-images.githubusercontent.com/13182778/54625578-8bc64c80-4a3d-11e9-9bf8-baa491860f63.png)

**Acceptance Criteria**:

1. The off-center tip makes the tooltip look unbalanced. Would centering the tip cause any issues with display when the tooltip needs to appear on the swatch at the left edge of the screen?

**Comment by sirugh** [comment]
#1390 will make this unnecessary.
