### ISSUE TITLE
PWA 2.1.0 Release Execution

### ISSUE THREAD

**Issue by jcalcaben** [magento-research/pwa-studio#1026]
Issue to track all activity for PWA 2.1.0 Release. (Based off activities on #923)

Current Action Items:

RTM
- [x] Author & Merge Release Notes to ./changelog.md : @jcalcaben
- [x] Commit Release Notes: @jcalcaben @zetlen @jimbo
- [x] Approve/signoff build: @zetlen @jimbo @dpatil-magento
- [x] Deploy to now.sh: @zetlen 
- [x] Verify now.sh deploys & scale configuration: @zetlen
- [x] Deploy to Magento Cloud: @bbatsche @tjwiebell 
- [x] Verify Cloud deploys: @bbatsche @tjwiebell and any Cloud ops personnel

GA
- [x] In Github, create release from tag v2.1.0: @zetlen @jimbo
- [x] Push the release tag to the repo
- [x] Merge release 2.1.0 to master
- [x] Copy CHANGELOG to Github release details : @zetlen @jimbo
- [x] Publish devdocs: @jcalcaben
- [x] Publish to NPM/package managers: @zetlen
- [x] Rebase all outstanding PRs on develop @sirugh

**Comment by zetlen** [comment]
@rugh is volunteering to do some rebase activity

**Comment by sirugh** [comment]
all is donezo.
