### ISSUE TITLE
Adding new pages to renderRoutes

### ISSUE THREAD

**Issue by SharlSherif** [magento-research/pwa-studio#1028]
I'm trying to create new pages and use them in the production build.
i added my page `component`  to the `renderRoutes` file like this :
```
import React from 'react';
import { Switch, Route } from 'react-router-dom';
import { Page } from '@magento/peregrine';
import ErrorView from 'src/components/ErrorView/index';

import RoutesTypes from './authentication';
// components
import MyPage from 'src/components/MyPage';

const { PrivateRoute, GuestRoute } = RoutesTypes;
const renderRoutingError = props => <ErrorView {...props} />;

const renderRoutes = () => (
    <Switch>
        <Route
            exact
            name="profile"
            staticName={true}
            path="/account/profile.html"
            component={MyPage}
        />
        <Route render={() => <Page>{renderRoutingError}</Page>} />
    </Switch>
);

export default renderRoutes;
```

and going to `/account/profile.html` does fully work as intended, but while the page is loading, this shows up :
![image](https://user-images.githubusercontent.com/29375572/54476064-a9a76d80-4801-11e9-9e64-e1d342f39246.png)

Is there a way to remove that `not found` in the `title` and `body` while the page is loading?

**Comment by awilcoxa** [comment]
@zetlen: "Any URL ending in .html will first be checked to see if it is an SEO URL to a catalog page. This is standard Magento 2 behavior. Adding custom routes requires both editing the renderRoutes file and the UPWARD configuration file right now...a better approach is currently in planning."
