### ISSUE TITLE
auto suggest and go to definition not working venia-concept<src folder 

### ISSUE THREAD

**Issue by ayushtuli1** [magento-research/pwa-studio#1030]
auto suggest and go to definition not working venia-concept<src folder

**Comment by tjwiebell** [comment]
We don't want to distribute editor specific configs in the repo, but all engineers have this similar config file in their project. This subject might a good candidate for docs, I'll discuss with the team and loop in @jcalcaben if we agree this should be added.

`packages/venia-concept/jsconfig.json`
```json
{
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "src/*": ["./src/*"]
        },
    },
    "exclude": [
        "node_modules",
        "dist"
    ]
}
```
