### ISSUE TITLE
Create video for docker dev environment setup

### ISSUE THREAD

**Issue by sharkySharks** [magento-research/pwa-studio#1036]
Per request from product, need to create a video detailing the setup process for running the docker development environment for PWA.

**Comment by sirugh** [comment]
I'd love this!

**Comment by sharkySharks** [comment]
Video created and pinned to both the community slack channel #pwa as well as internal slack channel. Distribution in formal documentation pending review and implementation from docs team.

**Comment by jcalcaben** [comment]
The video has been posted in the **Free Video Library** under **Training and Certification** in your Magento account.

Registration is free at https://u.magento.com/free-video-library:

Once registered, you can access the video at: https://magentou.mediaspace.kaltura.com/media/PWA+Docker+Development/0_fsypegt0
