### ISSUE TITLE
Fastly Image optimization not working with Upward PHP.

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/pwa-studio#1038]
Pre-conditions - 
1. Magento should be running on Production mode
2. Fastly should be enabled
3. upward_php as mid-level

Steps -
1. Navigate to Bottoms category

Issue - Image optimization not happening (Fastly params in image urls, `auto=webp&format=pjpg&width=<width-value>`.
Expected - Image optimization should happen so that page images will load faster.

**Comment by tjwiebell** [comment]
Closed via #1039
