### ISSUE TITLE
[bug]: Thumbnails are requested on Venia PDP in mobile

### ISSUE THREAD

**Issue by sirugh** [magento-research/pwa-studio#1041]
**Describe the bug**
In the Venia Storefront in a mobile view the page requests the thumbnail images unnecessarily.

In the following screenshot you can see the displayed image (640px) but you also can see the two thumbnails (240px) being requested.
[![Image from Gyazo](https://i.gyazo.com/9be2b5a1a6911bc062c9a9884dc3a683.png)](https://gyazo.com/9be2b5a1a6911bc062c9a9884dc3a683)

**To Reproduce**
1. Open a PDP in mobile view with the network tab open.
2. See that large (~640) and small (~240) images are requested.

**Expected behavior**
Only the necessary images are requested. On Desktop that would be large & small images but on mobile that should only be the large images.

**Please complete the following device information:**
 - Device: Macbook Pro
 - OS: Mojave
 - Browser: Chrome
 - Magento Version: 2.3.1
 - NPM version `npm -v` 6.7.0
 - Node Version `node -v` 11.6.0

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Possible solutions**
Avoid mounting thumbnail components when viewport is below a certain width.

**Comment by DmitryShmaliuk** [comment]
Please, assign me.
