### ISSUE TITLE
Need domain and ssl/tls cert from Adobe in order to enable HTTPS and service workers in AWS

### ISSUE THREAD

**Issue by sharkySharks** [magento-research/pwa-studio#1053]
As the title states, need to go through Adobe, per their policy, to get a domain and an associated ssl/tls certificate in order to enable HTTPS, and therefore service workers, for our demo deploy site in elastic beanstalk.

**Comment by sharkySharks** [comment]
This is an investigation with Chris Burton as the certificates for our backend Magento 2 instances that live in the regression environment have had their certs expire recently and therefore are sending 500 responses when trying to access the `/graphql` backend. Those certs need to be updated for `testsonfire.com` domains in AWS through Adobe as well, I will work to get the PWA demo site domains and certs along with this request.

**Comment by sharkySharks** [comment]
Adding HOLD label. Requests are in progress. Will be checking in with Chris on progress.

**Comment by sharkySharks** [comment]
Adding @cherdman here to track the progress of getting domains and tls certificates with Chris Burton.

**Comment by cherdman** [comment]
Kayden to get the account/domain/ssl powers. Will remain blocked for now.

**Comment by sharkySharks** [comment]
I watched the requests go into Adobe today, the page to request these domains were previously blocked to Magento. I will be tracking this as well as the subsequent tls certificate request.

**Comment by supernova-at** [comment]
We need SSL wildcard support for many subdomains (one for each pull request) to be secure.

**Comment by awilcoxa** [comment]
@sharkySharks @cherdman  any updates?

**Comment by sharkySharks** [comment]
I'm in email communication with Adobe setting this up. Will update this ticket when Adobe's side has been set up.

**Comment by sharkySharks** [comment]
Actually, as I was typing the above, they were approved 😃 

<img width="1664" alt="Screen Shot 2019-05-07 at 9 14 20 AM" src="https://user-images.githubusercontent.com/7784948/57315500-8e8e0700-70a8-11e9-918b-7c3ed26c3dbb.png">

I am out this week at a conference but will pick up setting this up in our AWS account when I am back in the office.

**Comment by sharkySharks** [comment]
Tracked on Commerce DevOps board: https://jira.corp.magento.com/browse/COMOPS-56

**Comment by supernova-at** [comment]
MAJOR UPDATE

All the certs have been approved and are available.

Need new tickets for prod and staging servers.

**Comment by awilcoxa** [comment]
@sharkySharks can you update?

**Comment by sharkySharks** [comment]
Update: I am back in the office. I can look at this sometime this week.

**Comment by dpatil-magento** [comment]
I updated pwa-venia-staging application with certificates keys and configuration changes and now we just need to update website's DNS to point to the ELB URL  "https://pwa-venia-deploy-staging.us-east-1.elasticbeanstalk.com "

Once this works, We can do the same for pwa-venia-demo application as well. And also need to request new certiificate for pwa-venia-stable.

**Comment by sharkySharks** [comment]
Nice work @dpatil-magento !

Future domain requests can be made here: https://dns.corp.adobe.com/#/home
DigiCert requests can be made here: https://www.digicert.com/account/login.php
Adobe docs on getting access to digicert, etc: https://inside.corp.adobe.com/itech/kc/IT00030.html

**Comment by dpatil-magento** [comment]
lighthouse report was stuck/crashing as http request were not redirected to http. AWS classic load balancer does not have this feature in built. Switched to Application load balancer which has the ability to do so and now Lighthouse works as expected.

**Comment by sharkySharks** [comment]
Please take a look at the elastic bean stalk instances you have deployed. 3/4 are red with some errors, and the one that is green is not running on `https`.

**Comment by dpatil-magento** [comment]
Fixed one instance https://develop.pwa-venia.com. I will update remaining two soon once terminated application gets removed.

**Comment by dpatil-magento** [comment]
@sharkySharks  All three instances are up and running now.
 https://develop.pwa-venia.com (Demo deploy pipeline)
https://prod.pwa-venia.com  (Stable pipeline)
https://prtest.pwa-venia-staging.com (Staging pipeline)

**Comment by sharkySharks** [comment]
@dpatil-magento the demo you showed me looks good and the lighthouse score looks great! Thanks for figuring all that out. I think this can be closed now 👍
