### ISSUE TITLE
Getting exception on Venia when a product doesnt have "Meta Description" and user access that product via direct URL.

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/pwa-studio#1064]
Steps - 
1. Create a product without "Meta Description"
2. Now try accessing with appending URL key to venia base url or go to product details page accessing via category and reload the page.

Expected - Product details page should be displayed.
Actual - Getting exception.

{"0":"Warning: htmlspecialchars() expects parameter 1 to be string, array given in \/app\/vendor\/mustache\/mustache\/src\/Mustache\/Cache\/NoopCache.php(45) : eval()'d code on line 118","1":"<pre>#1 htmlspecialchars() called at [vendor\/mustache\/mustache\/src\/Mustache\/Cache\/NoopCache.php(45) : eval()'d code:118]\n#2 ............

**Comment by tjwiebell** [comment]
Confirmed with @dpatil-magento that this isn't reproducible in `develop` any longer. Closing as obsolete.
