### ISSUE TITLE
pwastudio.io certificate error

### ISSUE THREAD

**Issue by NiklasBr** [magento-research/pwa-studio#1068]
**Describe the bug**
DLG_FLAGS_SEC_CERT_CN_INVALID when visiting pwastudio.io

**To Reproduce**
1. Go to pwastudio.io
2. See error

Since it appears to be a permanent redirect, you may need to clear browser or DNS cache depending on your env.

**Expected behavior**
A redirect to https://magento-research.github.io/pwa-studio/ should happen seamlessly.

**Additional context**
Or maybe add a new/updated cert?

**Comment by sirugh** [comment]
I think we're in the process of updating the cert so this PR/issue may not be necessary.

@ericerway status on the update?

**Comment by ericerway** [comment]
SSL and redirect fixed with hosting provider. Please verify. Thanks!

**Comment by sirugh** [comment]
Worked for me!
