### ISSUE TITLE
[bug]: Spacing for header buttons isn't even

### ISSUE THREAD

**Issue by sirugh** [magento-research/pwa-studio#1070]
**Describe the bug**
The header buttons are not spaced evenly. The center icon has no padding while the buttons to the right have left padding. This is probably because the header uses `grid-template: 1fr auto 1fr` so the center icon takes up only the space it needs.

**To Reproduce**
Open Venia and check out the header. You'll see what I mean.

**Expected behavior**
Header icons are spaced evenly

**Screenshots**
[![Image from Gyazo](https://i.gyazo.com/c9860dffb8d45a02218a11d7ad8301e1.png)](https://gyazo.com/c9860dffb8d45a02218a11d7ad8301e1)

**Please complete the following device information:**
 - Device: [e.g. iPhone6, PC] Mac
 - OS: [e.g. iOS8.1, Windows 10] SX
 - Browser [e.g. stock browser, safari] Chrome
 - Venia Version [e.g. 22] `develop`
 - Magento Version `2.3.1`

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Additional context**

**Possible solutions**
Add any ideas about possible solutions to the problem here.

**Comment by MarynaVozniuk** [comment]
I want to take it

**Comment by supernova-at** [comment]
Hi @MarynaVozniuk, sorry for the delayed response - are you still interested in picking up this ticket?

**Comment by MarynaVozniuk** [comment]
Hi @supernova-at, I think this issue can be closed, as I fixed this bug, see - https://github.com/magento-research/pwa-studio/pull/1129. 
Sorry, I didn't add the link right

**Comment by awilcoxa** [comment]
Closing issue as related PR has been merged.
