### ISSUE TITLE
Error Message too descriptive when Venia Sign In fails

### ISSUE THREAD

**Issue by supernova-at** [magento-research/pwa-studio#1075]
Security best practice is not to be too descriptive in error messages so that we don't clue attackers in to potential vulnerabilities. Further in this particular case, the technical details of the error are not user friendly.

# To Reproduce

In Venia, perform the following steps:
1. Click the top left "hamburger menu" to open up the left side nav
1. Click the "sign in" button at the bottom of the nav
1. Enter a valid username but invalid password
1. See the following error message is displayed:

 ![Screen Shot 2019-03-27 at 2.32.57 PM.png](https://images.zenhubusercontent.com/5bef16763560017fb6812f47/cc35f342-0cfb-4ae7-a60b-0c5fb8a95b59)

# Acceptance Criteria

1. Instead of showing the end user the endpoint we're hitting and the method we're using to hit it, display a simple "login failed" message instead

**Comment by tjwiebell** [comment]
This may be a duplicate of #819 (more user friendly vs. less descriptive, but same thing). Please close if you agree.

**Comment by tjwiebell** [comment]
Duplicate of #819
