### ISSUE TITLE
Publish Project Standards to public wiki

### ISSUE THREAD

**Issue by jcalcaben** [magento-research/pwa-studio#1079]
Make the project and coding standard public:
https://wiki.corp.magento.com/display/FF/Project+and+Coding+Standard

Related to: #1008

**Comment by jcalcaben** [comment]
Coding standards now publicly available in the wiki: https://github.com/magento-research/pwa-studio/wiki/Project-coding-standards-and-conventions

**Comment by supernova-at** [comment]
Looks good. The only thing I can think to add would be links to where we do these things in the repo itself, but I don't think that's a big deal.

**Comment by brendanfalkowski** [comment]
@jcalcaben — This one is a little confusing.

![Screen Shot 2019-04-02 at 12 39 32 PM](https://user-images.githubusercontent.com/214924/55431068-70326a00-5544-11e9-8dd5-05eecf67ec7c.png)

**Comment by jcalcaben** [comment]
@brendanfalkowski  - Can you point out which part is confusing for you?

**Comment by brendanfalkowski** [comment]
![Screen Shot 2019-04-02 at 12 39 32 PM](https://user-images.githubusercontent.com/214924/55431694-ff8c4d00-5545-11e9-81d2-402c4d328a24.png)

**Comment by jcalcaben** [comment]
ah, good catch. Consider it fixed. Thanks!
