### ISSUE TITLE
UX design and components for My Account

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#108]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[X] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## This issue is a:

[ ] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a shopper, I want a fast and seamless My Account experience on Venia on my mobile and desktop device so that I can manage my customer and order information from a single location.

Account Dashboard Account Information Address Book My Orders Billing Arrangements Recurring Profiles My Downloadable Products My Product Reviews My Wishlist My Applications Newsletter Subscriptions My Tags Store Credit Gift Card Gift Registry Reward Points My Invitations

## Expected result:

Early sketches and Venia design artifacts for My Account (as appropriate) 
Documentation of component breakdown; MVP labels where needed Feedback from internal/external to validate

**Comment by brendanfalkowski** [comment]
Would love if each instance of "my" was replaced with "your" (better) or (best) if pronouns were dropped entirely. I do this in every project. It's always been a pain in Magento to homogenize the inconsistent perspective.

Copywriting is more natural if the website speaks to the user from a third-person perspective. This is an ongoing fight when developers / editors aren't careful about perspective when writing messaging / content. It would help long-term if they didn't see differing pronoun references.

**Comment by ericerway** [comment]
Good callout, thanks @brendanfalkowski -- copying @soumya-ashok our UX designer to consider when she gets started later this week. 100% agree on content design where we could address with the new Venia theme. Thanks again! 👍

**Comment by soumya-ashok** [comment]
@brendanfalkowski Thank you for your feedback, sorry it's taken me a few days to catch up and respond. I will work with the team on refining the perspective.

**Comment by ericerway** [comment]
Marking as "Done" for this sprint; lots of valuable feedback received that will be created as new (smaller) stories for next sprint.

**Comment by brendanfalkowski** [comment]
@soumya-ashok + @ericerway — Feel free to reach out if you want any reference implementations / sounding board for pronoun use.

**Comment by ericerway** [comment]
Will do @brendanfalkowsi -- will be sure to include you in an upcoming content sweep, we could definitely use your perspective. Thanks!
