### ISSUE TITLE
Product variant selection 

### ISSUE THREAD

**Issue by aditidc** [magento-research/pwa-studio#1081]
**Describe the bug**
Every time the page is refreshed the color choice changes

**To Reproduce**
1. Go to 'veniapwa.com'
2. Click on any category. For e.g. Tops
3. Click on one of the products. This will open up the PDP. You will see Fashion color on the right hand side and 4 color variants.
4. Refresh the page. Now you see a different set of Fashion color variants.

**Expected behavior**
Fashion color variants should not change when page is refreshed

**Screenshots**

![image](https://user-images.githubusercontent.com/49005394/55115022-b4cf8880-50a0-11e9-9e36-afdc38e79ecc.png)

After page refresh:

![image](https://user-images.githubusercontent.com/49005394/55115062-ca44b280-50a0-11e9-9ca0-e8004469b469.png)

**Please complete the following device information:**
 - Device: Desktop
 - OS: Windows 10
 - Browser [Chrome]

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by tjwiebell** [comment]
@aditidc - this is a known limitation of the GraphQL query `customAttributeMetadata`, it does not return enough information about color swatches, so this component currently just picks a color at random to display. Please re-open if you feel there is a way to do this, but from our last audit of Magento 2.3.1, this still wasn't possible.

https://github.com/magento-research/pwa-studio/blob/develop/packages/venia-concept/src/components/ProductOptions/swatch.js#L58
