### ISSUE TITLE
Missing production documentation

### ISSUE THREAD

**Issue by LogimaeCommerce** [magento-research/pwa-studio#1082]
Hello,

I managed to set up the venia theme at shop.logima.io. I could not find any straightforward and available information on how to do that, so I basically just set it up the same way I've set up other PWAs. 

I am getting some errors when adding products in shopping cart etc. I would be very grateful if anyone could point me to the right direction here :)

**Exact errors I am getting is**
No product images showing in categories
Error messages when adding product to cart
Error upon "checkout"

<img width="1193" alt="Screenshot 2019-03-28 at 10 33 49" src="https://user-images.githubusercontent.com/48867557/55125598-2c56f380-5145-11e9-8306-5c8e8bd6cd0e.png">
<img width="1190" alt="Screenshot 2019-03-28 at 10 39 50" src="https://user-images.githubusercontent.com/48867557/55125838-f0705e00-5145-11e9-880f-7d6f57a8840a.png">
<img width="1199" alt="Screenshot 2019-03-28 at 10 52 13" src="https://user-images.githubusercontent.com/48867557/55126322-ac7e5880-5147-11e9-82cb-ba97a2eccf50.png">

What I did to make it into production:

        location / {
                proxy_pass http://0.0.0.0:42489/;
        }
in my nginx server block after running

        yarn install
        yarn build
        yarn run build && yarn run stage:venia

I followed the dev docs on how to setup the PWA theme for magento 2.3.1, which is at cloudpanel.logima.io (showing blank now after changing theme).

**Comment by sirugh** [comment]
Hi @LogimaeCommerce can you look in the network tab for any failures/errors? If you see some, please post them here. I'm wondering if your backend is returning an error. We could definitely represent errors a bit more clearly. Sorry!
