### ISSUE TITLE
is there a way to create routes without .html prefix?

### ISSUE THREAD

**Issue by ayushtuli1** [magento-research/pwa-studio#1083]
**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sirugh** [comment]
If you have questions please refer to the documentation or the public slack channel. If you have a desired change, please open an issue with details of your request.
