### ISSUE TITLE
[bug]: /dist/ folder 404'ing due to greedy regex in venia-upward.yml

### ISSUE THREAD

**Issue by j0rd** [magento-research/pwa-studio#1092]
**Describe the bug**

```
diff --git a/packages/venia-concept/venia-upward.yml b/packages/venia-concept/venia-upward.yml
index 52620e3..573236a 100644
--- a/packages/venia-concept/venia-upward.yml
+++ b/packages/venia-concept/venia-upward.yml
@@ -19,9 +19,6 @@ response:
       pattern: '^/(icons/.+|favicon.ico$|manifest.json$|veniaClosed.png$)'
       use: static
     # serve anything with a urlKey
-    - matches: urlKey
-      pattern: '.'
-      use: appShell
     - matches: request.url.pathname
       pattern: '^/$'
       use: appShell
```

`pattern: '.'` will match everything, and not let `default: bundles` declaration get hit, thus nothing in /dist/ folder gets loaded as it should, instead appShell is loaded.

**To Reproduce**
```
$ export NODE_ENV=production
$ export PORT=8888
$ cd pwa-studio/packages/venia-concept
$ node server.js
```
In your browser visit http://xxx.xxx.xxx.xxx:8888/js/client.js . Page not found 404 is loaded, and HTML is provided by app shell.

**Expected behavior**
Files in /dist/ folder as available relative to root URL and not 404'd/

**Possible solutions**
Make a less greedy regex. Remove that line entirely.
 
**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]: PC
 - OS [e.g. iOS8.1, Windows 10]: Ubuntu
 - Browser [e.g. Chrome, Safari]: Chromium
 - Browser Version [e.g. 22]: 73.0.3683.75
 - Magento Version: 2.3.1
 - PWA Studio Version: 2.1.0
 - NPM version `npm -v`: 6.4.1
 - Node Version `node -v`: v10.15.3

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by tjwiebell** [comment]
We've rolled back #1095 while we investigate a working fix for loading CMS pages w/o extensions. This should no longer be a problem.

**Comment by skynixukraine** [comment]
@tjwiebell  probably, it is time reopen it and resolve the issue, is not?
