### ISSUE TITLE
Mobile device - First Tap on swatch shows partial tooltip instead of selecting the swatch

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/pwa-studio#1101]
Description -
When user tries to select a swatch color option on mobile device on first tap partial tool tip displays and user has to do second tap in order to select the color option.

Steps - 
1. Go to Product details page on Venia store front.
2. Try to select a Color swatch via Tap.

Expected - New Color option should get selected.
Actual - Partial tool tip being displayed. If user does second tap the color option gets selected and Partial tool tip still retains.

Screen shot-  Trying to select "Green"
![image.png](https://images.zenhubusercontent.com/5c585c5aecb0076f3e898431/197c3be3-358a-497e-85e2-bd9e7b15a163)

Device Information 
Iphone SE

Environment - 
https://magento-venia.now.sh/

**Comment by sirugh** [comment]
This issue will be "resolved" since we are reworking tooltips/swatches. See #1390
