### ISSUE TITLE
Mini-cart Sidebar: If cart is empty and clicked on mini-cart, execute unwanted Rest API call.

### ISSUE THREAD

**Issue by vishal-7037** [magento-research/pwa-studio#1104]
**Describe the bug**
I've noticed extra or unwanted Rest API call executed on mini-cart open action even cart is empty.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the pwa-studio storefront.
2. Open developer console and go to the network tab.
3. Click on the mini-cart icon at the top right section.
4. See you will find rest API call even cart is empty.

**Expected behavior**
If the cart is empty, the rest API call shouldn't be executed.

**Screenshots**
![2019_04_02_Selection_002](https://user-images.githubusercontent.com/38535982/55396761-4720d200-5562-11e9-9f24-941064c46689.png)

**Please complete the following device information:**
 - Device: iPhone6/7/8, PC
 - OS: Ubuntu
 - Browser Chrome
 - Magento Version 2.3.1
 - PWA Studio Version: 2.1
 - NPM version 6.4.1
 - Node Version 10.15.2

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by sudeep-cedcoss** [comment]
I am working on this at #dmcdindia1
