### ISSUE TITLE
Scaffolding for peregrine and buildpack (auto-import)

### ISSUE THREAD

**Issue by zetlen** [magento-research/pwa-studio#111]
_From @zetlen on May 3, 2018 11:8_

As of the recently released 6.0.0, NPM has [built-in support for `create-` style packages](https://docs.npmjs.com/cli/init#description) which scaffold out a project directory (e.g. [`create-react-app`](https://github.com/facebook/create-react-app). It auto-installs the creator, so we could potentially tell folks to run just one command to get a theme set up (which would then prompt you for the config it needs to connect to a Magento instance)...

```sh
npm init @magento/pwa
```

_Copied from original issue: magento-research/magento-research-backoffice#7_

**Comment by awilcoxa** [comment]
closing during backlog cleanup
