### ISSUE TITLE
Determine whether migration to Adobe Vault as preferred credential store manager is necessary

### ISSUE THREAD

**Issue by sharkySharks** [magento-research/pwa-studio#1117]
Determine whether migration from AWS System Manager parameter store to Adobe Vault is necessary.

AWS System Manager is being used for storing sensitive credentials, tokens, urls, but Adobe Vault is the officially support tool-of-choice for Adobe and should be migrated to for long term use by the team.

Details on setting up Adobe Vault are still being worked thorugh. Comments from Mehryar Mansoor who is on the DevOps Platform team:
Vault access should be by high level teams. A request needs to be made to have a namespace provisioned for the team, which involved two steps. One is to have an LDAP group created in the “DX_Ldap” and you’ll want to request 3 ldap groups created: `magento_pwa_admins`, `magento_pwa_developers` and `magento_pwa_ro` (read-only).
The link to where you create this ticket is on one of the pages:
https://wiki.corp.adobe.com/display/CoreServicesTeam/CST+Vault
https://wiki.corp.adobe.com/display/CoreServicesTeam/Service+Consumption+Guide#ServiceConsumptionGuide-CreatepathwithinVault

**Comment by dpatil-magento** [comment]
Using AWS parameter store.
