### ISSUE TITLE
Mini-cart: Error occurred when clicking on update cart button without selecting product options.

### ISSUE THREAD

**Issue by vishal-7037** [magento-research/pwa-studio#1124]
**Describe the bug**
An error occurred when clicking on update cart button without selecting product options in mini-cart.

**To Reproduce**
1. Add any configurable product in the cart
2. Open cart and click on edit item action
3. Click on **Update Cart** button without selecting any options.

**Expected behavior**
The button should be disabled until product option selected.
![2019_04_08_Selection_002](https://user-images.githubusercontent.com/38535982/55726012-7afd6b00-5a2c-11e9-88b1-650288df2cf7.png)

**Screenshots**
![2019_04_08_Selection_003](https://user-images.githubusercontent.com/38535982/55726019-7f298880-5a2c-11e9-8850-1b4adf258e3c.png)
![2019_04_08_Selection_004](https://user-images.githubusercontent.com/38535982/55726023-818be280-5a2c-11e9-8078-bfbfa384bcb4.png)

**Possible solutions**
The button should be disabled until product option selected.

**Please complete the following device information:**
 - Device: iPhone6/7/8, PC
- OS: Ubuntu
- Browser Chrome
- Magento Version 2.3.1
- PWA Studio Version: 2.1
- NPM version 6.4.1
- Node Version 10.15.2

**Please let us know what packages this bug is in regards to:**
- [X] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by awilcoxa** [comment]
#900 also outlines the same problem contained here, although that ticket has some additional scope. Assigned developer should also review to ensure we've covered all related cart issues.
