### ISSUE TITLE
[doc]: Verbose comments/explainer on Venia's upward.yml

### ISSUE THREAD

**Issue by rowan-m** [magento-research/pwa-studio#1130]
The [`upward.yml`](/magento-research/pwa-studio/blob/develop/packages/venia-concept/venia-upward.yml) is a great example of the UPWARD spec applied to a real project. However, if that's your introduction to it, it can be a little intimidating.

It would be helpful to have this file commented as an explainer / walkthrough of what each resolver is doing and why it's structured in this particular way.

Specific things to call out in the file:

- when it comes to naming - what's part of the spec / reserved, what's convention, what's developer choice. e.g. `response`, `proxy`, `resource` at the top-level sound like they might have built-in meanings.
- use of variables / aliases (or at least, that's what they look like). e.g. `cmsPage: cmsPageResult.data.cmsPage`, why is it specified where it is, what's it doing? `cmsPage` is used further up in the config in `resource` which is harder to read.

Some things that would be useful in a getting started / explainer:

- what kind of feature means I need to add something to the config? The `CMS_PAGE` section has some cross-over with the app-routing, but it's not immediately clear how that relates.
- does everything start from the top-level `resource` resolver and then branch under that, or do any requests fall through to be picked up by later resolvers?

cc @zetlen

**Comment by zetlen** [comment]
We can and should add a bunch of comments to `venia-upward.yml`. I'm also excited to revise the spec so it's easier to read and analyze, but for now, e do need comments.
