### ISSUE TITLE
Migrate from CircleCI to AWS CI System - Turn off CircleCI

### ISSUE THREAD

**Issue by sharkySharks** [magento-research/pwa-studio#1131]
This is a story to track migration from CircleCI to AWS CI system. After the AWS CI system has been running in the repository for  ~1wk and shows no sign of any issues then: 

- remove CircleCI configuration from the repo
- remove CircleCI webhook from `settings` in the repo
- add AWS checks as required for Pull Request merges

**Comment by dpatil-magento** [comment]
Tested changes for below conditions of Pass/Fail, works same as circle ci.
![image.png](https://images.zenhubusercontent.com/5c585c5aecb0076f3e898431/76c70166-8a39-437b-a571-fa5e33265108)
