### ISSUE TITLE
Pipeline for automated npm release for PWA

### ISSUE THREAD

**Issue by sharkySharks** [magento-research/pwa-studio#1145]
Create a "push button" automated release pipeline for creating an npm package release through CI system. 

Some Acceptance Criteria:
- should be able to run a release through CI system
- the release should create an npm package
- there should be a shell script written that automates the release
- npm credentials should be stored in the secrets parameter store

Consider automating the full release process, including:
- creation of a git tag with change release notes
- running tests as part of release pipeline
- a script to cut a release branch for testing before running the official npm release
- semvr versioning if not already being handled automatically

**Comment by dpatil-magento** [comment]
Steps - https://gist.github.com/zetlen/8902418a6c6d4944e02b31e5955c1c93#file-YUCK-md

**Comment by dpatil-magento** [comment]
Rough idea assuming there are no merge conflicts to master (Happy Path):
Once QA sign-off stable branch for a release- 
1. Update release versions in parameter-store or simple text/config file in pwa-cicd repo
2. Edit the source of AWS code pipeline to QA signed-off branch and hit on Release button in AWS release pipeline ( set restrictive access to this pipeline) - Actions to Automate:
A - Download code from Stable branch to AWS
B - Update code with release version and commit.
C- Some AWS feature or Lambda function or Shell script to Push the code to Master with release Tag including previous commit.
D - Cloud watch to track above event and the initiate following  -
D1 - Run Tests and if its pass, another cloud watch to track this and trigger below
i - Deploy production AWS instance with latest release code.
ii - Publish NPM packages- Cloud watch to track above and initiate separate pipeline to download code to AWS from master and then ssh to npm and push the packages.
