### ISSUE TITLE
Receive System Configuration data from Magento Backend

### ISSUE THREAD

**Issue by nuzil** [magento-research/pwa-studio#115]
## This issue is for the following packages:

[x] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[x] `pwa-module`
[ ] `pwa-devdocs`

## This issue is a:
[x] Feature suggestion

## Description

Currently Magento has a lot of options for configuring frontend behaviour. Like "CMS page for home, Show Only Netto Price, Show Only brutto Price, Show Both" ... and a lot of more. 
As End-user, when I manage my shop I expect that all options that presented in Magento Backend are functional and can be used.

## Expected result:

In case if we want to build fully functional PWA application, we have to take care, that all options for system configuration are possible to use and their change will affect on a PWA Store front.

## Possible solutions:

As proposition I would like propose implement new API endpoints for GraphQL where developers can receive Stores -> Configuration values.

If everybody is agree with that I can create an issue in GraphQL board then.

## Additional impormation

So we have a current situation with PWA template configuration:
In case we are doing the full functional (even if we are talking about basic template) template, we need to retrieve multiple config options from Magento Backend.

Currently we are though about basic settings, and on our opinion we have those required attributes that will make possible to develop MVP of Venia theme:

### Content -> Design -> Configuration:

* HTML head Section
* Header Section
* Footer section

Others are not really required at this moment.

### Stores -> Configuration

* Web -> Default Pages (current blocker, cause we need to know correct pages ID. Otherwise we have to hardcode them).

At this moment that points that we already met.

Implementation

So to get those values, we need some API endpoints. 

As Ideas: 
a) We can extend storeStoreConfigManagerV1 with additional parameters to deliver required information. But not sure there is a sense to deliver configs only partially. 
b) Much better solution will be implement new API where user can search by Config Key (or extend storeStoreConfigManagerV1 with key parameter).

**Comment by artKozinets** [comment]
Also we need next config:

<h3>Stores -> Configuration</h3>

**| Catalog | Catalog -> Search Engine Optimization:** Category URL Suffix
