### ISSUE TITLE
Add all fields to Billing Address

### ISSUE THREAD

**Issue by supernova-at** [magento-research/pwa-studio#1154]
Users can select to have their billing address differ from their shipping address during checkout:

![Screen Shot 2019-04-22 at 3.37.18 PM.png](https://images.zenhubusercontent.com/5bef16763560017fb6812f47/73ea93ea-8931-4f33-acf7-600ef7fe0c5c)

These fields do not encompass the entirety of an address, however - the system currently [plucks the missing values from the shipping address](https://github.com/magento-research/pwa-studio/blob/93cee6854e18c98c5fd31b51473147f0621662d7/packages/venia-concept/src/actions/checkout/asyncActions.js#L198-L206).

We should add the following fields to the form:
1. Email
1. First Name
1. Last Name
1. Telephone

Additionally:

1. Please also update the [Checkout Actions](https://github.com/magento-research/pwa-studio/blob/93cee6854e18c98c5fd31b51473147f0621662d7/packages/venia-concept/src/actions/checkout/asyncActions.js#L198-L206) to no longer pluck values from Shipping Address.
1. Please ensure that the "Create Account" form after guest checkout is seeded properly.

![Screen Shot 2019-04-22 at 3.14.23 PM.png](https://images.zenhubusercontent.com/5bef16763560017fb6812f47/d3840394-bd2c-4be6-9e90-110865630e53)

**Comment by awilcoxa** [comment]
@soumya-ashok

**Comment by lewisvoncken** [comment]
@lewisvoncken 
[issue-1154.txt](https://github.com/magento-research/pwa-studio/files/3180048/issue-1154.txt)

**Comment by lewisvoncken** [comment]
@supernova-at and @awilcoxa 

I am working on it

**Comment by soumya-ashok** [comment]
@supernova-at and @awilcoxa - Here's the mockup. Please review and let me know if there are changes.
I assume all fields are required, including phone number?

![Billing + Shipping](https://user-images.githubusercontent.com/25960021/57890395-2e603900-77fd-11e9-8c04-6a59235683af.png)

**Comment by awilcoxa** [comment]
@lewisvoncken did you end up opening a PR for this?

**Comment by lewisvoncken** [comment]
@awilcoxa I have just created the pull request.
