### ISSUE TITLE
[bug]: If user tries to access product page after it goes to out of stock then system enters a infinite loop. 

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/pwa-studio#1159]
Steps - 
1. Access a product details page say for Product A.
2. Login to backend and make Product A as out of stock.
3. Now either refresh the product details page on storefront venia or try accessing the product again.

Expected - System should throw error message indicating product not available.
Actual - System show error notification and if user click on in the same error re-appears. User has to clear browser cache to make it work.

Screen - 
![image.png](https://images.zenhubusercontent.com/5c585c5aecb0076f3e898431/5eada186-2aed-4866-beb7-6d830e14b914)

**Comment by sudeep-cedcoss** [comment]
I am working on this at #dmcdindia1
