### ISSUE TITLE
[doc] M2 + PWA: one or two repos?

### ISSUE THREAD

**Issue by brendanfalkowski** [magento-research/pwa-studio#1161]
**Describe the request**
Our team is discussing Git repository structure as it relates to the M2 core and PWA Studio, which has implications for the production environment and deployment process.

### ONE REPO

```
/root
    /magento2
        /app
        /pub
        ....
    /pwa
        /packages
        ....
```

Pros: easy for mono-server deployment, one master = simple versioning
Cons: like a billion files crush an IDE's find speed

### TWO REPOS

```
/root (magento 2)
    /app
    /pub
    ....
```

```
/root (pwa)
    /packages
    ....
```

Pros: easier to pull upstream from PWA Studio during dev, faster dev environments, separation of concerns
Cons: complicated versioning + release process

**Possible solutions**
We started with two repos, because that's how Magento defined it themselves and we forked PWA Studio to take upstream changes down.

Backend + DevOps teams are getting antsy because there isn't guidance on how PWA should get into production, so they're questioning repo structure.

**Please let us know whether this is a new topic or a topic change request:**
 - [x] New Topic Request (ie. missing entire topic/section)
 - [ ] Topic Change Request (ie. spelling, organization)

**Comment by zetlen** [comment]
Hey @brendanfalkowski, the real answer to this is "you should structure your repository any way you like". Our product has artificially restrained you here by not being very consumable outside of cloning our repository. If you want to review #1198 for the next evolution of this, please do and give us more comments about our use cases on that PR!

**Comment by brendanfalkowski** [comment]
@zetlen — Awesome! We hacked a structure together on Thursday to pull from this repo as a forced upstream over our customizations but we were guessing something like this was pending.

Queue Friday: hey look, great!

Briefing the team now that code is public for it, and we'll test and report back.
