### ISSUE TITLE
Pwa Studio Showing error try to fill shipping address

### ISSUE THREAD

**Issue by prince-auriga** [magento-research/pwa-studio#1168]
I want to complete a process for a place an order but when I try it showing error 
Must contain exactly 2 character(s). in the state.

So it's under development or its a bug and how can check the complte process of Magento.
Like other functionality which Magento provides in frontend.

1. Add wishlist
2. Apply coupon
3. Category Page Filter missing.

So please clear can we use PWA-studio setup or there is development pending.
https://drive.google.com/file/d/1FzmbQksYPkSwW2e79kJrc3BXXCVaRBVf/view?usp=sharing

Thanks

**Comment by tjwiebell** [comment]
Insufficient detail to investigate. If this is still a problem, please create a new issue and use the Bug Report template and fill in all sections. The Venia reference supports the US locale only, so may be the issue you're encountering. There is a lots of development still pending, you can track our progress and pick up issues for contribution on our ZenHub board here:

https://app.zenhub.com/workspace/o/magento-research/pwa-studio/boards?repos=137249745
