### ISSUE TITLE
Implement standard connection between M2 storefront and theme

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#117]
## This issue is for the following packages:

[ ] `venia-concept`
[X] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[X] `pwa-devdocs`

## This issue is a:

[ ] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a developer, I want to a reliable and standard connection between Magento 2 and my PWA theme in Venia so that I can start development and contribute to the project.

Create Composer-driven link between theme and store
Integrate theme build with Magento 2 build and deployment
Implement Magento 2 setting for PWA awareness (development mode)

## Expected result:

Updates build and development tools for pwa-studio and Magento 2
Updated Magento 2 connector (module) for PWA "mode"
Clear examples and documentation
Testing coverage (as appropriate)

**Comment by awilcoxa** [comment]
Closing as complete
