### ISSUE TITLE
Integrate theme build with Magento 2 build and deployment

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#119]
## This issue is for the following packages:

[ ] `venia-concept`
[X] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[X] `pwa-devdocs`

## This issue is a:

[ ] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a developer, I want to build PWA themes for Magento 2 with development tools from the PWA Studio so that I can start development and contribute to the project.

## Expected result:

Updated build and development tools for pwa-studio and Magento 2
Testing and documentation (as appropriate)

**Comment by awilcoxa** [comment]
closing during backlog cleanup
