### ISSUE TITLE
[bug]: Schrodinger's certificate

### ISSUE THREAD

**Issue by brendanfalkowski** [magento-research/pwa-studio#1197]
**Describe the bug**
The cert created by PWA Studio expires in 2038, but Chrome + Firefox think it is expired.

Maybe setting such a far future date is causing doubts. Firefox sheds a little more light:

```
https://magento-ce-nibh1.local.pwadev:8634/search.html?query=shi&f=%7B%7D&sort=score&dir=desc

The certificate issuer’s certificate has expired. Check your system date and time.

HTTP Strict Transport Security: false
HTTP Public Key Pinning: false

Certificate chain:

-----BEGIN CERTIFICATE-----
............RRRRRRRRRREDACTED
-----END CERTIFICATE-----
```

**To Reproduce**
1. Run the build + watch.

**Expected behavior**
Nice green cert.

**Screenshots**
![Screen Shot 2019-05-02 at 3 23 17 PM](https://user-images.githubusercontent.com/214924/57112197-d3eeb500-6cf3-11e9-81e6-715f19be9eaa.png)

**Additional context**
The site still runs without this, but browsers don't like it.

**Possible solutions**
Maybe set a 1 year cert?

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]: Mac
 - OS [e.g. iOS8.1, Windows 10]: MacOS 10.14.4
 - Browser [e.g. Chrome, Safari]: Any
 - Magento Version: 2.3.1
 - PWA Studio Version: 2.3.1
 - NPM version `npm -v`: 10.15.3
 - Node Version `node -v`: 6.4.1

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by zetlen** [comment]
I think your underlying `devcert` certifying authority has expired. [This issue](https://github.com/davewasmer/devcert/pull/24) seems to be the underlying cause; that, plus a few other reasons, is why we are strongly considering forking `devcert`! We're just wary of taking on more code ownership.

For now, if you delete `devcert` from your keychain, and `rm -rf "~/Library/Application Support/devcert"`, then you should be able to clear out the expired cert and start again.

Please reopen this if that doesn't fix it!

**Comment by brendanfalkowski** [comment]
@zetlen — Thanks! Tested and working. Added to my manuals here: https://manuals.test/frameworks/magento-pwa-studio/troubleshooting
