### ISSUE TITLE
Implement Magento 2 setting for PWA awareness (development mode)

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#120]
## This issue is for the following packages:

[ ] `venia-concept`
[X] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[X] `pwa-devdocs`

## This issue is a:

[ ] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a developer, I want to configure Magento 2 for my PWA storefront so that it is aware of the "headless" approach including suppressing layout and other considerations to begin developing and contributing to the PWA Studio.

## Expected result:

Updated Magento 2 connector (module) for PWA configuration and "development mode"
Testing and documentation (as appropriate)

**Comment by awilcoxa** [comment]
closing during backlog cleanup
