### ISSUE TITLE
Phone field is accepting characters as input at Checkout->Shipping Address page

### ISSUE THREAD

**Issue by pradeep-cedcoss** [magento-research/pwa-studio#1203]
**Environment :**
Magento : 2.3 version
Ubuntu :  18.04
node version : 12.1.0
npm version : 6.9

Description :
Phone number field on Checkout-> Shipping details page accepts characters as input 
To recreate Scenario  :
1. Add a Product to cart 
2. Click on Checkout and enter Shipping details but enter characters in Phone number field 
3. Click on Use address

Expected Result :
Validation error must have been thrown for Phone Number Field

Result Found : 
Saved Shipping address 

![image](https://user-images.githubusercontent.com/41564476/57178820-164ef800-6e94-11e9-9b14-ad59fd270c1b.png)

**Comment by tjwiebell** [comment]
Venia matches the schema of our Magento backing system, and phone fields are `varchar` to support extensions or phone notes (`512.123.4567 ext. 8910 (call after 5pm)`). Appreciate the contribution, but this is not a validation we should implement.
