### ISSUE TITLE
magento-venia.now.sh and veniapwa.com are broken 

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/pwa-studio#1206]
Steps - 
1. Go to https://magento-venia.now.sh or https://veniapwa.com/
2. Try to sign-in, create account or add product to cart and try placing order.

Issue: On clicking buttons submit (create account, forgot password) , Sign In, Use address (checkout flow)  nothing happens.
Expected - User should be able to complete above flows without any errors.

**Comment by supernova-at** [comment]
Confirmed that the issue exists locally using the latest from the `develop` branch.
