### ISSUE TITLE
Create index of root components for Venia (development mode)

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#121]
## This issue is for the following packages:

[ ] `venia-concept`
[X] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[X] `pwa-devdocs`

## This issue is a:

[ ] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a developer, I want to have a basic understanding of the Venia components in an easily understandable way so that I can start development and contribute to the project.

Discovery for navigation in GraphQL
Create developer facing index of views

## Expected result:

Updates build and development tools (creation of index) for Studio
Testing and documentation (as appropriate)

**Comment by awilcoxa** [comment]
Closed during backlog cleanup. New work will be logged against a new epic.
