### ISSUE TITLE
[feature]: PWA Studio Overview (Infographic) 

### ISSUE THREAD

**Issue by awilcoxa** [magento-research/pwa-studio#1212]
As a newcomer to PWA, I want to be able to quickly understand the various parts and tools within the studio so that I can learn and begin applying working with the studio.

 It's important that the new concepts (and 3rd party tools) that are introduced through the PWA studio are relatable to not just developers but also to business users (ex. Product or Project Managers) who are attempting to understand how they need to plan for and use PWA Studio. There is a need for education around the studio and it's tools to help with understanding and, ultimately, adoption. The infographic should be able to quickly answer questions (in a single page), like: 

* So what is PWA Studio? 
* What technologies are being used? 
* How do all of the components/tools fit together? 
* What is the purpose of UPWARD/Venia/Peregrine and how does it fit in to the larger picture? 
* Can you give me examples of the output of each tool?

**Comment by jcalcaben** [comment]
![pwa-studio-overview](https://user-images.githubusercontent.com/4692281/57463083-bc598400-723f-11e9-84e1-c349178a97cd.png)

**Comment by supernova-at** [comment]
Looks cool! Only minor tweak would be to try the Legend over on the far right (under "Resources").

I think it checks these boxes but @awilcoxa should probably review for acceptance as well:

- [ ] So what is PWA Studio?
- [x] What technologies are being used?
- [x] How do all of the components/tools fit together?
- [x] What is the purpose of UPWARD/Venia/Peregrine and how does it fit in to the larger picture?
- [x] Can you give me examples of the output of each tool?

I'm not sure someone viewing this document for the first time would be able to answer "So what is PWA Studio", but I think all the elements are there.

**Comment by jcalcaben** [comment]
![pwa-studio-developer-overview2](https://user-images.githubusercontent.com/4692281/57630751-ce9b3100-7563-11e9-9db6-c24d70d9b5fd.png)
