### ISSUE TITLE
Discovery for navigation in GraphQL [SPIKE]

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#122]
## This issue is for the following packages:

[ ] `venia-concept`
[X] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[X] `pwa-devdocs`

## This issue is a:

[ ] Bug
[X] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a developer, I want to understand navigation for GraphQL in Magento 2 in development so that I can create a summary of components to build a successful PWA themes.

## Expected result:

Summary of discovery activities around GraphQL (wiki)
Review and contribution to GraphQL workstream
Demo and examples (as appropriate)

**Comment by awilcoxa** [comment]
closing during backlog cleanup
