### ISSUE TITLE
[bug]: Unwanted content displayed in search suggestion box when there are no results for search

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/pwa-studio#1223]
Steps - 
1. Go to Venia store front and click on search icon.
2. Enter search string which should not return any results. example - afgdsgedf

Expected -  Search suggestion box should just display "No results were found."
Actual - Its displaying some extra content  with above message.

![image.png](https://images.zenhubusercontent.com/5c585c5aecb0076f3e898431/7d462275-0f83-40be-b948-d4cd04df088b)

**Comment by dpatil-magento** [comment]
Note for QA - When this bug gets fixed, Need to un-comment lines in AssertNoResultsInSuggestionBox action group of MFTF tests. QA resource will take care of it.

**Comment by Jordaneisenburger** [comment]
When i check https://magento-venia.now.sh I can't reproduce the issue, but when i setup venia locally i can reproduce it. I'd like to take ownership of this issue but want to be sure that it's still an actual problem ?

**Comment by dpatil-magento** [comment]
@Jordaneisenburger  https://magento-venia.now.sh  has PWA 2.1.0 release.  Please check on develop branch i.e. https://develop.pwa-venia.com

**Comment by Jordaneisenburger** [comment]
@dpatil-magento I'd like to take ownership of this issue.

**Comment by tjwiebell** [comment]
Looks like a community member submitted a PR for this already (#1252)

**Comment by khoa-le** [comment]
Yes, I created my first PR on pwa-studio 2 weeks ago. Can you review and give me feedback?

**Comment by supernova-at** [comment]
@khoa-le Taking a look at your #1252 now :thumbsup:
