### ISSUE TITLE
Create developer facing index of views

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#123]
## This issue is for the following packages:

[ ] `venia-concept`
[X] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[X] `pwa-devdocs`

## This issue is a:

[ ] Bug
[X] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a developer, I want a summary of root components available in Venia so that I can create and maintain a successful PWA theme in Magento 2 using the PWA Studio.

## Expected result:

Updates to development and build tools (as appropriate)
Documentation and examples (showing components)

**Comment by awilcoxa** [comment]
closing during backlog cleanup
