### ISSUE TITLE
[bug]: thumbnails are requested twice in desktop mode

### ISSUE THREAD

**Issue by sirugh** [magento-research/pwa-studio#1231]
**Describe the bug**
When you click on a thumbnail in a PDP the thumbnails are requested twice.

**To Reproduce**
1. Go to a PDP like https://magento-venia-concept-0uff3.local.pwadev:8210/pomona-skirt.html
2. Open the network tab and click on a thumbnail.
3. See that the thumbnails are requested twice!
**Expected behavior**

**Screenshots**
[![Image from Gyazo](https://i.gyazo.com/e55511b89531f45120764edfb3d5595e.gif)](https://gyazo.com/e55511b89531f45120764edfb3d5595e)

**Additional context**
I looked into this a bit and believe this is related to the [use of state](https://github.com/magento-research/pwa-studio/blob/develop/packages/venia-concept/src/components/ProductImageCarousel/carousel.js#L117) to render a placeholder image. When the main image loads it re-renders all children too, which mean re-rendering the thumbnail images. This was added by _me_ 😢 in #1055.

**Possible solutions**
* Revert the placeholder work
* Refactor the thumbnails to be a sibling of the carousel within `ProductFullDetail`. This will take some work since the thumbnail component also renders as the little dots below the image on mobile view.

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by sirugh** [comment]
While we're at it, we also request images multiple times in the `miniCart` when toggling between checkout and back: 

[![Image from Gyazo](https://i.gyazo.com/03d25def8e1cfd571ec2648a2ef95b33.gif)](https://gyazo.com/03d25def8e1cfd571ec2648a2ef95b33)

**Comment by supernova-at** [comment]
> While we're at it, we also request images multiple times in the miniCart when toggling between checkout and back

I broke this out into its own issue: #1365.

**Comment by awilcoxa** [comment]
@sirugh are you actually working on this now?

**Comment by sirugh** [comment]
@awilcoxa this issue, #1231, will be resolved by #1268.
