### ISSUE TITLE
[bug]: Payments module shows error when installing PWA via package.json on cloud environment.

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/pwa-studio#1236]
Steps - 
1. Follow instructions https://github.com/magento-research/magento2-upward-connector 

Expected - PWA storefront should be working without any issues.
Actual - While checkout, payment module shows error.  Braintree token related.

**Comment by tjwiebell** [comment]
Created #1247 that captures the issue at hand with the current installation steps. Requires some questions answered by PO/Arch, so I'll let @awilcoxa prioritize as needed. The steps in the repo assume you have your own node application that you're trying to deploy, Venia is just a reference, and the steps are accurate assuming your bundle doesn't contain the same type of bug as #1247. Closing this out in favor of resolution in #1247.
