### ISSUE TITLE
Improve PWA Studio environment and setup process

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#124]
## This issue is for the following packages:

[ ] `venia-concept`
[X] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[X] `pwa-devdocs`

## This issue is a:

[ ] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a developer, I want to a simple environment and setup process regardless of my configuration so that I can quickly start developing in PWA Studio and contribute to the project.

Implement prerequisite check with suggestions
Discovery for Docker environment with containers [SPIKE]
Optimization for environment setup

## Expected result:

Creation of Docker friendly container and process for PWA Studio
Updated build and development tools for simple setup
Testing and documentation (as appropriate)

**Comment by sharkySharks** [comment]
Adding myself here as this is something I want to look into over the coming weeks.

**Comment by sharkySharks** [comment]
docker work being tracked under #734

**Comment by cherdman** [comment]
Closing in favor of #196
