### ISSUE TITLE
[bug]: A short, simple sentence describing the bug

### ISSUE THREAD

**Issue by threescs** [magento-research/pwa-studio#1243]
Try using pwa studio in magento 2.3.0, I want a copy of pwa studio 2.0.0 documentation Thank you

**Comment by jcalcaben** [comment]
Hi @threescs is there a version specific topic you are looking for?

**Comment by threescs** [comment]
Hello, I want to confirm two things, first, whether magento2.3.0 is compatible with pwa studio, and second, can I carry out secondary development on Venia, what is the release process?

**Comment by threescs** [comment]
> Hi @threescs is there a version specific topic you are looking for?

We are using the luma theme magento version 2.3.0

**Comment by threescs** [comment]
> Hi @threescs is there a version specific topic you are looking for?

Hello, I want to confirm two things, first, whether magento2.3.0 is compatible with pwa studio, and second, can I carry out secondary development on Venia, what is the release process?

**Comment by jcalcaben** [comment]
These questions are more appropriate for our community slack channel:
https://magentocommeng.slack.com/messages/C71HNKYS2

Closing issue.
