### ISSUE TITLE
Discovery: Improve Peregrine Documentation

### ISSUE THREAD

**Issue by supernova-at** [magento-research/pwa-studio#1245]
Discovery issue for current gaps in Peregrine documentation. Output of this discovery is a project plan to address specific gaps in Peregrine documentation with issues created to address dev docs, tutorials, etc. 

Additional items: 
Review Storybook coverage for Peregrine
...

**Comment by awilcoxa** [comment]
@supernova-at: Since Peregrine components and hooks are meant for reuse, we need to ensure that folks know how to use them in the first place.

Ideally each hook and component has a summary of what it is and what it accomplishes, and example code to go with it.

**Comment by jcalcaben** [comment]
Internal wiki link for review: [Documentation audit results](https://wiki.corp.magento.com/display/FF/2019+Documentation+Roadmap#id-2019DocumentationRoadmap-Documentationauditresult(2019-06-11))

**Comment by supernova-at** [comment]
I think this is good but the acceptance criteria includes

> with issues created

So I think if you can actually create the issues (and link them on that wiki page), we'd be :thumbsup:.

**Comment by jcalcaben** [comment]
Issues created and linked in wiki
