### ISSUE TITLE
Implement prerequisite check with suggestions

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#125]
## This issue is for the following packages:

[ ] `venia-concept`
[X] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[X] `pwa-devdocs`

## This issue is a:

[ ] Bug
[X] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a developer, I want to understand the technical requirements and prerequisites of PWA Studio during setup so that I can create and maintain PWA themes in Magento 2 using our build and development tools.

## Expected result:

Review and summary of prerequisites needed for PWA Studio
Updates to development and build tools (as appropriate)
Documentation and examples (showing components)

**Comment by awilcoxa** [comment]
closing during backlog cleanup
