### ISSUE TITLE
[bug]: Search Suggetion result image thumbnail view broken

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/pwa-studio#1250]
Pre-condition -
Fastly should not be Enabled.

Steps - (Cloud with upward_php)
1. Install PWA on Magento Cloud with Sample data.
2. Enter valid sku say VT10 on search field and wait for search suggestions to display.

Expected - Search suggestion should be displayed without any UI issues.
Actual - Search suggestion UI is broken as Full image is being shows instead of resized thumbnail.

**To reproduce the issue on local with upward_js : **
1. Clone latest develop branch pwa_studio.
2. packages/pwa-buildpack/src/Utilities/addImgOptMiddleware.js  in this file chaneg line # 50 to    " if (true) { "
3. Install and go to venia storefront and valid sku say VT10 on search field .

![image.png](https://images.zenhubusercontent.com/5c585c5aecb0076f3e898431/f88f3fa0-24c0-4a2b-975c-b3dbd3fda77f)

**Comment by tjwiebell** [comment]
To clarify a little bit; this is an issue when there is no image optimization happening (`backend` via Fastly, or `onboard` via middleware/sharp/shrinkray/whateva). Those steps to reproduce with `upward-js` are to disable onboard image opt. Should just need to add some `max-*` CSS to keep the image bound to the container.
