### ISSUE TITLE
[bug]: Magento-2.3.2 - PDP page does not display configurable options.

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/pwa-studio#1251]
Pre-condition - 
1- Backend instance should be Magento 2.3.2
2 - Sample data installed

Steps - 
1. Navigate to Product details page of configurable product.

Expected - Product should show configurable options.
Actual - Product does not display configurable options. Looks like simple product.

![image.png](https://images.zenhubusercontent.com/5c585c5aecb0076f3e898431/7bd85ef6-906d-4a54-90b9-942e1e3141b0)

**Comment by tjwiebell** [comment]
I believe this is a GraphQL bug, which can be tracked here: https://github.com/magento/graphql-ce/issues/715.

Will leave this open on the off chance they're not willing to resolve, and we need to come up with a work around in the scope of this issue.

**Comment by awilcoxa** [comment]
Blocked/Hold pending resolution of ce#715 by Graphql team

**Comment by tjwiebell** [comment]
Closed via magento/graphql-ce#715
