### ISSUE TITLE
I am trying to modify the ui component under venia-concept, and the page refresh error is reported after saving.

### ISSUE THREAD

**Issue by threescs** [magento-research/pwa-studio#1254]
![image](https://user-images.githubusercontent.com/29721759/57993798-10405480-7aed-11e9-8bbf-c6903184df34.png)

Expected: Normal compilation run
Actual: The page reported that the js under dist could not be found.

**Comment by niklas-wolf** [comment]
https://github.com/magento-research/pwa-studio/issues/1256 It's the exact same Bug ;)

**Comment by awilcoxa** [comment]
closing this issue as a duplicate of #1256
