### ISSUE TITLE
[bug]: JS-Resources can't be loaded on subcategories

### ISSUE THREAD

**Issue by niklas-wolf** [magento-research/pwa-studio#1256]
**Describe the bug**
When you try to reload a subcategory page, e.g. _/venia-tops/venia-blouses.html_, the corresponding JS-resources can not be loaded. That's because it trys to reload the resources from _/venia-tops/js_ instead of just _/js_ .

**To Reproduce**
1. Go to https://magento-venia.now.sh/venia-tops/venia-blouses.html or a similar route on your local environment.
2. Open Developer Tools and see the wrong paths for the resources.

**Expected behavior**
Resources should be loaded from root.

**Possible solutions**
Add trailing slash in mustache templates where resources get included.

**Please complete the following device information:**
 - PWA Studio Version: develop

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by niklas-wolf** [comment]
I can provide a PR for this in the next couple of hours.

**Comment by awilcoxa** [comment]
thanks @niklas-wolf we'll take a look at this in next week's grooming.
