### ISSUE TITLE
Discovery for Docker environment with containers [SPIKE]

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#126]
## This issue is for the following packages:

[ ] `venia-concept`
[X] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[X] `pwa-devdocs`

## This issue is a:

[ ] Bug
[X] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a developer, I want to utilize Docker to quickly get started with development for PWA Studio regardless of my environment and potentially contribute to the project.

## Expected result:

Discovery for continuously updated Docker container for PWA Studio environment 
Review and summary of Docker findings and process
Additional user stories/epics for implementation
Example and demo (as appropriate)

**Comment by pcvonz** [comment]
Mentioned this in Slack, didn't know there was an issue for it. 

Forked a Magento 2 docker image and made it pull from the 2.3-develop branch. Also added a script to install Venia. The docker image also comes with a self signed cert so magento can be served through HTTPS (default for the venia-concept). Installing venia is documented in the readme [here](https://github.com/pcvonz/docker-magento2#setting-up-venia)

Link to the repo: https://github.com/pcvonz/docker-magento2

There is one stumbling block that I can think of: The `composer.json` in the venia package needs a version number for the `install-venia` script to work. Also at times trying to run venia with the packages that exist on npm can be troublesome, so I usually resort to installing packages locally (ex: `npm i ../pwa-buildback && npm i ../peregrine`). But that's unrelated to the docker image. 

There is a little bit of cruft from the version of the image I forked, notably the developer / integrator folders. Those aren't relevant anymore. They can probably be removed and we could use just one dockerfile. It doesn't clutter up the actual image and I just wanted to start contributing to Venia :smiley: 

To build the `dockerfile` right now you need to use node. (shouldn't be necessary in the future)

- Edit `dockerfile.hbs` and then run `node update.js`. 
- A dockerfile will be built in the `integrator` and the `developer` folder. 
- The `cron` file and the `dockerfile` need to be moved from `integrator` folder into same folder as the docker-compose.yml. 
- Edit the `docker-compose.yml` file and change the line from `- image: something/something` to build `- build: .`
- Now run `docker-compose up -d` and it will attempt to build a new image with your changes to the dockerfile

Left to do:

- [ ] Set up automatic builds
- [ ] Remove unnecessary code / files / folders from the version I forked

**Comment by ericerway** [comment]
Kamino cloned this issue to [magento-research/pwa-studio](https://github.com/magento-research/pwa-studio/issues/312)

**Comment by sharkySharks** [comment]
work being picked up under #734
