### ISSUE TITLE
[feature]: Group ContextProviders into PeregrineContextProvider

### ISSUE THREAD

**Issue by zetlen** [magento-research/pwa-studio#1262]
## Description
Create a single component which injects all contexts for the various Peregrine hooks, so that app implementors can easily enable all Peregrine functionality that child components may use.

**Is your feature request related to a problem? Please describe.**
Many of our new Peregrine hooks use the React `useContext` hook.

So far, with #1192 merged #1218 about to be merged, we have this nested structure at top level:

```diff
<Adapter
        apiBase={apiBase}
        apollo={{ link: authLink.concat(Adapter.apolloLink(apiBase)) }}
        store={store}
    >
        <WindowSizeContextProvider>
+           <ToastContextProvider>
+               <ToastContainer />
                <App />
+           </ToastContextProvider>
        </WindowSizeContextProvider>
    </Adapter>
```

This doesn't bode well for usability, for two reasons:

1. There is no use case for using the individual context providers one by one. These apps will include descendent components that may use any Peregrine features, like toasts or window size. We shouldn't require top-level app authors, who are consuming Peregrine and Peregrine-using components, to remember to include all the context providers.

2. Nobody liked deep nesting; in fact, we think the React core team will probably come out with a way to group contexts to avoid this pattern. We might as well get ahead of the game and then later switch to the first-party solution when it comes out.

**Describe the solution you'd like**
A single PeregrineContextProvider, which optionally takes feature flags as props so you can turn _off_ features such as `toasts`. The ContextProvider would render its children inside a nested tree of contexts, so the downstream developer doesn't have to.

**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by tjwiebell** [comment]
Closing as duplicate in favor of #1312. Both seem to outline the same problem/solution, but I'll make a note to reference this issue in review/QA to make sure we covered both.
