### ISSUE TITLE
Basic setup and examples (scaffolding) for Venia theme

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#128]
## This issue is for the following packages:

[X] `venia-concept`
[X] `pwa-buildpack`
[X] `peregrine`
[ ] `pwa-module`
[X] `pwa-devdocs`

## This issue is a:

[ ] Bug
[X] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a developer, to have the ability to quickly see examples and connect to a Magento 2 storefront with PWA Studio so that I can start developing PWA themes and contribute to the project.

Enable prompting for "simple setup"
Establish connection to Magento 2 storefront
Implement auto-import of peregrine and buildpack

## Expected result:

Updated build and development tools for setup and examples (scaffolding)
Testing and documentation (as appropriate)

**Comment by awilcoxa** [comment]
Closing as complete
