### ISSUE TITLE
[bug]: Missing Shopping Cart Badge Indicator

### ISSUE THREAD

**Issue by supernova-at** [magento-research/pwa-studio#1285]
**Describe the bug**
The Shopping Cart in the Header doesn't show how many items are in the cart until the cart is opened.

**To Reproduce**
1. Add an item to your cart
1. Refresh the page
1. See that the Shopping Cart badge icon does not appear
1. Open your shopping cart
1. Close your shopping cart
1. See that the Shopping Cart badge icon appears and accurately indicates how many items are in the cart

**Expected behavior**
The Shopping Cart badge icon should show the number of items without the user first having to open the cart.

**Screenshots**
![Screen Shot 2019-05-31 at 1.25.32 PM.png](https://images.zenhubusercontent.com/5bef16763560017fb6812f47/7b9691ac-e810-4a3d-bac2-d133ba871f30)

![Screen Shot 2019-05-31 at 1.25.43 PM.png](https://images.zenhubusercontent.com/5bef16763560017fb6812f47/68ab9d80-d706-4c0f-bc4f-35a9059ad39f)

**Additional context**
It looks like the requests to get the cart info are not fired until the cart is opened:

![Screen Shot 2019-05-31 at 1.29.39 PM.png](https://images.zenhubusercontent.com/5bef16763560017fb6812f47/18cb124e-9bd5-4c82-9403-95c073c45d85)

**Possible solutions**
Query for the cart contents on initial page load.

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by shakyShane** [comment]
I've tested this, it appears to already to be fixed in the pwa-studio repo.

On page load, the cart is always requested now which makes this a none-issue :)

**Comment by supernova-at** [comment]
Confirmed that this is no longer an issue on both the latest release: https://veniapwa.com/, and on `develop`: https://magento-venia-develop.now.sh/.

Thanks @shakyShane !
