### ISSUE TITLE
Enable prompting for "simple setup" in PWA Studio

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#129]
## This issue is for the following packages:

[ ] `venia-concept`
[X] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[X] `pwa-devdocs`

## This issue is a:

[ ] Bug
[X] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a developer, I want the ability to enter a "simple setup" with PWA Studio that gives me examples and basic connections so that I can quickly get started with developing new PWA themes.

## Expected result:

Updated build and development tools (with optimizations)
Testing and documentation (as appropriate)

**Comment by awilcoxa** [comment]
closing during backlog cleanup
