### ISSUE TITLE
[bug]: Duplicate Image request calls on Category page

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/pwa-studio#1297]
**Describe the bug**
On Venia Category page every image has 2 image request calls instead of just one.

**Note**
Issue does not occur when Fastly enabled backend is used with `IMAGE_OPTIMIZING_ORIGIN=backend`

**To Reproduce**
1. Navigate to Venia Home page on develop branch https://magento-venia-develop.now.sh/
2. Open dev tools on chrome and click on any Category say - Tops.

**Expected behavior**
Category page should load with all images and on dev tool network tab image requests should have one call each image.

**Actual behavior**
Category page should load with all images and on dev tool network tab image requests have two calls each image.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5c585c5aecb0076f3e898431/77570105-9e42-44c6-a402-bcb1506cf1d3)If applicable, add screenshots to help explain your problem.

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]:
 - OS [e.g. iOS8.1, Windows 10]:
 - Browser [e.g. Chrome, Safari]:
 - Browser Version [e.g. 22]:
 - Magento Version:
 - PWA Studio Version:
 - NPM version `npm -v`:
 - Node Version `node -v`:

**Please let us know what packages this bug is in regards to:**
- `venia-concept`

**Comment by sirugh** [comment]
Looks like this is related to pagination. When a category page first loads without a `page` query param the code sets it to `1` although the actual `currentPage` is `0`. This forces the `useEffect` in the Category component to re-run, which re-queries!
