### ISSUE TITLE
Establish connection to Magento 2 storefront

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#130]
## This issue is for the following packages:

[ ] `venia-concept`
[X] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[X] `pwa-devdocs`

## This issue is a:

[ ] Bug
[X] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a developer, I want to establish a quick connection to my Magento 2 storefront from PWA Studio so that I can start developing and maintaining PWA themes.

## Expected result:

Updated build and development tools (with optimizations)
Testing and documentation (as appropriate)

**Comment by ericerway** [comment]
@zetlen can this be closed or did you have other goals for this issue? Thanks!

**Comment by zetlen** [comment]
This is definitely done!
