### ISSUE TITLE
[feature]: Missing paging configuration parameter description

### ISSUE THREAD

**Issue by threescs** [magento-research/pwa-studio#1305]
**Is your feature request related to a problem? Please describe.**
Here I see the url set page parameter refresh page action,
I want to know where the code for the route listener parameter is.

![image](https://user-images.githubusercontent.com/29721759/59025426-b8447480-8886-11e9-9128-b38558a1ab09.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Please let us know what packages this feature is in regards to:**
- ✅ `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by zetlen** [comment]
This is a good observation! Pagination should be handled entirely within the `usePagination` hook, with the URL query parameters never directly accessed. But "ownership" of that parameter is not entirely clear yet. We're having the discussion in #1381.
