### ISSUE TITLE
[bug]: continue shopping button background color and hover color 

### ISSUE THREAD

**Issue by speedy008** [magento-research/pwa-studio#1306]
**Describe the bug**
Continue shopping button background color and hover color fixed

**To Reproduce**
1. Minicart(Empty) check continue shopping button

**Expected behavior**
![expected1](https://user-images.githubusercontent.com/33230237/58155650-eaa08000-7c91-11e9-805b-5a3edaaf81da.png)
![expected2](https://user-images.githubusercontent.com/33230237/58155664-f12ef780-7c91-11e9-88e2-e7e7949bbb12.png)

**Actual behavior**
![actual1](https://user-images.githubusercontent.com/33230237/58155588-c80e6700-7c91-11e9-89ff-0b9ed7aae8a7.png)
![actual2](https://user-images.githubusercontent.com/33230237/58155596-cd6bb180-7c91-11e9-80f8-84e1e8e2dd08.png)

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by soumya-ashok** [comment]
@speedy008 - The desired state of the button is dark gray when static, and teal on hover or focus. I think this matches with the first two screenshots you've shared in this issue. If that's the case, we can consider this approved.
