### ISSUE TITLE
Implement WebAPI endpoint for CRUD on core configuration data

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#131]
## This issue is for the following packages:

[ ] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[X] `pwa-module` (or new package)
[ ] `pwa-devdocs`

## This issue is a:

[ ] Bug
[] Feature suggestion
[ ] Documentation issue
[X] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a developer I want to configure a PWA project to connect to a Magento 2 store with the store configured correctly for PWA development and deployment so that I can get started and begin development quickly.

## Expected result:

Rest API with OAUTH to query and mutate values in the core configuration data table and/or any system settings global to the Magento instance.
Testing and documentation (as appropriate)

**Comment by zetlen** [comment]
Relevant PRs:
https://github.com/magento/graphql-ce/pull/126
https://github.com/magento/graphql-ce/pull/130
