### ISSUE TITLE
[bug]: Package `graphql-cli-validate-magento-pwa-queries` not published under @magento org in npm.

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/pwa-studio#1327]
**Describe the bug**
Package `graphql-cli-validate-magento-pwa-queries` is not published under @magento npm org.

**To Reproduce**
1. Login to npm and navigate to magento org.

**Expected behavior**
Package `graphql-cli-validate-magento-pwa-queries` should be present.

**Actual**
Package present outside @magento org.

**Possible solutions**
Update package.json "name" to be "@magento/graphql-cli-validate-magento-pwa-queries"  . Also add missing "publishConfig" section to be in sync with other packages.

**Comment by zetlen** [comment]
Unfortunately graphql-cli plugins can't be under scopes.
