### ISSUE TITLE
"Continue Shopping" button style in empty shopping cart

### ISSUE THREAD

**Issue by soumya-ashok** [magento-research/pwa-studio#1329]
Currently, the button looks like this -

![Screen Shot 2019-06-12 at 1.48.39 PM.png](https://images.zenhubusercontent.com/5b89562fba905a6006740695/317edd7c-e7da-4aa1-bd26-ef8346c39046)

The correct styling would be -

![Screen Shot 2019-06-12 at 1.51.32 PM.png](https://images.zenhubusercontent.com/5b89562fba905a6006740695/518795c9-d862-44da-8396-e45324a60b87)

with the button changing to the dark teal in the focused state without the dark gray border seen in the first screenshot.

**Comment by supernova-at** [comment]
@johnhughes1984 is going to pick this one up for `MM19UK` 💪

**Comment by sirugh** [comment]
This may already have a PR associated: https://github.com/magento-research/pwa-studio/pull/1264
