### ISSUE TITLE
Discovery for Redux async actions (pattern)

### ISSUE THREAD

**Issue by jimbo** [magento-research/pwa-studio#133]
## This issue is for the following packages:

[x] `venia-concept`
[ ] `pwa-buildpack`
[x] `peregrine`
[ ] `pwa-module`
[x] `pwa-devdocs`

## This issue is a:

[ ] Bug
[x] Feature suggestion
[x] Documentation issue
[ ] Other (Please Specify)

## Description

We need to select a pattern for dispatching and handling async actions. Redux doesn't provide a solution in the core library; [the official docs recommend](https://redux.js.org/advanced/async-actions#async-action-creators) using the first-party library, [redux-thunk](https://github.com/reduxjs/redux-thunk), but there are a number of alternative patterns and libraries we could use instead.

[As the official docs explain](https://redux.js.org/advanced/async-actions#actions), asynchronous scenarios in an application can be covered by a fairly consistent asynchronous action flow that includes three kinds of actions:

- An action indicating a request is in flight
- An action indicating a request has succeeded, possibly with a result
- An action indicating a request has failed, possibly with an error object

Developers in the React community tend to be opinionated, but not unified, on how to orchestrate this flow. We need to take into account the following when making our choice:

- Familiarity: are developers likely to be familiar with the pattern? a year from now?
- Simplicity: how quickly can the pattern be understood? what is its API footprint?
- Power: how well does the pattern cover advanced scenarios?
- Performance: is it fast? how large is the library?

It's also worth considering whether a pattern fits with our existing choices, such as Flux Standard Actions, but this choice may supersede other ones because it's so important.

## Expected result:

Middleware applied to the Redux store. This middleware should intercept certain actions, then asynchronously dispatch one or more other actions.

## Possible solutions:

- [redux-thunk](https://github.com/reduxjs/redux-thunk)
- [redux-saga](https://redux-saga.js.org/)
- [redux-promise](https://github.com/redux-utilities/redux-promise)
- others

**Comment by DrewML** [comment]
I'll advocate for `redux-promise`. I like the idea of leaning on the language's first class async primitive. Should be easy to follow for most when combined with `async`/`await`.
