### ISSUE TITLE
Spacing between image and text in product listing

### ISSUE THREAD

**Issue by soumya-ashok** [magento-research/pwa-studio#1330]
Current treatment -

![Screen Shot 2019-06-12 at 1.53.01 PM.png](https://images.zenhubusercontent.com/5b89562fba905a6006740695/978fcbb5-71a6-4eab-871d-e38e6f832a48)

The space between the bottom of the image and the product title needs to be increased.

**Comment by supernova-at** [comment]
@realchriswells is going to pick this one up! #mm19uk
