### ISSUE TITLE
Color tooltip needed on PD page

### ISSUE THREAD

**Issue by soumya-ashok** [magento-research/pwa-studio#1332]
Immediately upon color selection on the product detail page, this is the current state -

![Screen Shot 2019-06-12 at 2.01.13 PM.png](https://images.zenhubusercontent.com/5b89562fba905a6006740695/3b09e4c7-e928-4744-bdd0-961678172613)

The desired state is -

![Screen Shot 2019-06-12 at 2.03.00 PM.png](https://images.zenhubusercontent.com/5b89562fba905a6006740695/802722ef-3c76-45b2-85ca-b6de0b5f90a6)

**Comment by supernova-at** [comment]
Note: The desired UX is that the tooltip should appear for 2-3 seconds after click and then go away.

**Comment by supernova-at** [comment]
@realchriswells is going to pick this one up for `MM19UK` 💪

**Comment by supernova-at** [comment]
Closing in favor of #1390.
