### ISSUE TITLE
How can I integrate my custom magento2-module with venia theme (pwa-studio)

### ISSUE THREAD

**Issue by 0m3r** [magento-research/pwa-studio#1341]
I want to integration venia theme (pwa) and my custom module. But I can't find any documentation for this. No examples. No integration point in the code. Nothing.

Only https://github.com/Jordaneisenburger/fallback-studio

> I had no clue on how or where to start building my own storefront.

But I find many vue storefront module example

https://github.com/DivanteLtd/vue-storefront/blob/master/docs/guide/modules/introduction.md

https://github.com/frqnck/awesome-vue-storefront#front-end-modules

How can I create pwa-studio (venue) module?
How can I fluently add custom react component at the product page after description for example?
How can I run GraphQL query?
etc.

p.s. Which to use venia or vue storefront?

[Original stackoverflow question](https://magento.stackexchange.com/questions/278203/how-can-i-integrate-my-custom-module-with-venia-theme-pwa-studio)

**Comment by jcalcaben** [comment]
Hi @0m3r, we have many experienced community members who should be able to help answer these kinds of questions in our [#pwa slack channel](https://magentocommeng.slack.com/messages/C71HNKYS2).

**Comment by 0m3r** [comment]
Nice. You guys have pwa slack channel. But sorry I don't have a slack account.

**Comment by brendanfalkowski** [comment]
You can find info about signing up for the Slack here: https://devdocs.magento.com/community/resources/resources.html

**Comment by Bhavin-Adar** [comment]
AA barabar nathi proper guide karo.
