### ISSUE TITLE
yarn run buidl failed with exit code 127

### ISSUE THREAD

**Issue by VZeroCool** [magento-research/pwa-studio#1362]
I'm getting below error while build yarn 

OS : Ubuntu 16.04 , Magento 2.3 develop 

Any solutions to fix ??

**Comment by sirugh** [comment]
Can you provide more information? A screenshot or copy-paste of your terminal after running the command?

**Comment by VZeroCool** [comment]
Sorry @sirugh That was my bad. I get it resolved by changing URL variable from backend URL to base. 
Dont know read somehwhere but at almost all places told me to add backend URL and it throws error :(
