### ISSUE TITLE
MiniCart Product Images Issues Re-Requested

### ISSUE THREAD

**Issue by supernova-at** [magento-research/pwa-studio#1365]
**Describe the bug**
When you click on the checkout button in the minicart the product images are re-requested.

**To Reproduce**
1. Open the MiniCart with product(s) in it.
2. Open the network tab and click on the checkout button
3. See that the thumbnails are requested twice!

**Expected behavior**
The images should not be re-requested.

**Screenshots**
[![Image from Gyazo](https://i.gyazo.com/03d25def8e1cfd571ec2648a2ef95b33.gif)](https://gyazo.com/03d25def8e1cfd571ec2648a2ef95b33)

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by sirugh** [comment]
Fixed in #1231
