### ISSUE TITLE
Updated documentation for RootComponents and Shop By Category

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#137]
## This issue is for the following packages:

[ ] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[X] `pwa-devdocs`

## This issue is a:

[ ] Bug
[ ] Feature suggestion
[ ] Documentation issue
[X] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a developer, I want to have documentation for RootComponents and new development to support the Shop By Catetory and related homepage changes to Venia so that I can quickly get started and develop PWA themes.

## Expected result:

AC
Updated documentation and peer/technical review

**Comment by awilcoxa** [comment]
closing during backlog cleanup
