### ISSUE TITLE
CICD - AWS pipeline `pwa-stable` is failing on deploy step.

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/pwa-studio#1384]
Issue - `pwa-stable` is failing on deploy step. 
Expected - After push to `master` , this pipeline should be successful.

Issues might be because of aws.json pointing demo pipeline.

**Comment by threescs** [comment]
I also want to know, please let me know. Thank you.

**Comment by zetlen** [comment]
@dpatil-magento Is this still happening to you? It looks like the most recent deploy succeeded.

**Comment by dpatil-magento** [comment]
@zetlen I did quick play around too work. And long term fix is in cicd private repo. Waiting for @sharkySharks to review.
