### ISSUE TITLE
[bug]: loadingIndicator import in cartOptions.js is invalid

### ISSUE THREAD

**Issue by sirugh** [magento-research/pwa-studio#1385]
**Describe the bug**
We updated the loading indicator to export a `fullPageLoadingIndicator`. We missed one spot in merging in `cartOptions`.

```
WARNING in ./src/components/MiniCart/cartOptions.js 75:14-30
"export 'loadingIndicator' was not found in 'src/components/LoadingIndicator'
 @ ./src/components/MiniCart/editItem.js
 @ ./src/components/MiniCart/body.js
 @ ./src/components/MiniCart/miniCart.js
 @ ./src/components/MiniCart/container.js
 @ ./src/components/MiniCart/index.js
 @ ./src/components/App/app.js
 @ ./src/components/App/container.js
 @ ./src/components/App/index.js
 @ ./src/index.js
```

**To Reproduce**
Check out develop and `yarn install` and `yarn build`. You'll see the warning.
**Expected behavior**

**Possible solutions**
Update the imports to the proper name and double check whether a full page indicator is actually valid in cartOptions now.

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]:
 - OS [e.g. iOS8.1, Windows 10]:
 - Browser [e.g. Chrome, Safari]:
 - Browser Version [e.g. 22]:
 - Magento Version:
 - PWA Studio Version:
 - NPM version `npm -v`:
 - Node Version `node -v`:

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by zetlen** [comment]
My bad.
