### ISSUE TITLE
[feature]: Prevent PRs to master with Danger

### ISSUE THREAD

**Issue by tjwiebell** [magento-research/pwa-studio#1399]
**Is your feature request related to a problem? Please describe.**
Community and team members may accidentally create PRs to `master`, which can easily slip through if you're not paying close attention. There is no current use case to create *any* PR to `master`, so we should prevent the behavior entirely.

**Describe the solution you'd like**
Update Danger to detect PRs against `master` and automatically close them with a friendly message to re-create against `develop`. 

**Describe alternatives you've considered**
Checked branch protection, doesn't seem possible via GitHub.

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by sirugh** [comment]
https://github.com/magento/pwa-studio-cicd/pull/9 bingo bango bongo
