### ISSUE TITLE
[doc]: Minor doc updates needed. related to pr 1224

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/pwa-studio#1401]
**Describe the request**
#1224 made some changes which needs update to our dev docs.

1. Now .env is created as part of `yarn build`  and there is no `.env.dist` anymore.  
Remove - https://magento-research.github.io/pwa-studio/venia-pwa-concept/setup/     'cp packages/venia-concept/.env.dist packages/venia-concept/.env'  step.

2. upward file 'venia-upward.yml ' renamed to 'upward.yml'
Update - https://github.com/magento-research/magento2-upward-connector   `/app/node_modules/@magento/venia-concept/venia-upward.yml `  to `/app/node_modules/@magento/venia-concept/upward.yml `

**Comment by jcalcaben** [comment]
This issue will be closed when #1458 is merged
