### ISSUE TITLE
Node js version fixed to 10.x. bug or expected?

### ISSUE THREAD

**Issue by kelvin2200** [magento-research/pwa-studio#1479]
(some) Packages in pwa-studio have a node engine version fixed to 10.x... some require at least 10.x. Found this while trying to deploy on 12.6.0. Is this an expected behavior? Manually adjusting packages to use node ">=10.x" seems to work just fine, however, every deployment would require manual adjustment.

**Comment by sirugh** [comment]
We changed this recently but I'm not sure if we meant to explicitly require `10.x`. @zetlen I think you made this change -- if so do you recall why you used the specificity?

**Comment by kelvin2200** [comment]
I remember reading somewhere through the docs about something related to this (can't quite remember), but i think the specificity was intentional, in order to prevent (potential) node bugs with un-tested versions. Initially it was fixed to 8.x then after testing with other versions it was moved up to 10.x. I can confirm it works for 12.6.0 on a centos setup, and with a local magento api.
