### ISSUE TITLE
UX design and components for Mini Cart (Venia)

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#152]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[X] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## This issue is a:

[ ] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a shopper, I want a quick way to access the shopping cart on Venia so that I can make a purchase online with fewer steps in the process or access account information.

## Expected result:

Early sketches and prototype for Mini Cart (as appropriate) 
Documentation of component breakdown
Feedback from internal/external to validate

**Comment by soumya-ashok** [comment]
Cart with no items
Cart with items
Possible actions on a cart item

https://magento.invisionapp.com/share/87NRER0DE69
