### ISSUE TITLE
Implement CMS Page Component for Venia

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#160]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## This issue is a:

[ ] Bug
[X] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a developer I want to create a CMS page component for Venia so that can retrieve content from the Magento CMS.

- Examples could include sales promo and other content

Assumptions: successful setup and completion of Venia examples, sample data (mock data in JSON; not GraphQL dependent)

## Expected result:

AC
Displays CMS page component aligned with Venia design and prototype
Testing and documentation

**Comment by awilcoxa** [comment]
closed during backlog cleanup
