### ISSUE TITLE
Implement full Payments with Credit Card methods (Venia)

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#178]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## This issue is a:

[ ] Bug
[ ] Feature suggestion
[ ] Documentation issue
[X] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a shopper, I want to use a credit or debit card when making a purchase on Venia so that I can complete my order in addition to money order or check. Ability to retrieve payment methods.

**Possible spike on client-side security for REST

## Expected result:

Updates to payment in checkout using form field components; utilize REST API?
Basic validation of form fields (and error/success messages) appear visibly
Ability for form fields to be styled (best practices) 
Browser level auto-complete functionality; accessible labels and roles
Required fields and formatting (as noted)
Test and documentation (as appropriate)

**Comment by ericerway** [comment]
Duplicate with #349. Comments and notes migrated as needed.

**Comment by jlo2038** [comment]
any update?
