### ISSUE TITLE
[Documentation] Middle-tier architecture

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#181]
## This issue is for the following packages:

[ ] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[X] `pwa-devdocs`

## This issue is a:

[ ] Bug
[ ] Feature suggestion
[ ] Documentation issue
[X] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a developer I want to understand the impact of the updated middle-tier architecture changes for PWA Studio and how they affect developing and building storefronts including the Venia reference.

## Expected result:

Updated documentation
Internal and external review
Additional reference diagrams (as appropriate)

## Possible solutions:

Topics that cover the following:

* Basic concepts - provides information about concepts used by or introduced in UPWARD
* Context reference - Explains the global namespace, a.k.a. the context, and its usage in an UPWARD spec. Explains how to set/get values in the context. [Link to dev notes](https://github.com/magento-research/pwa-studio/tree/release/2.0/packages/upward-spec#context-reference).
* Resolver reference - Describes what a resolver does. Provides detailed descriptions/examples of the different types of resolvers. [Link to dev notes](https://github.com/magento-research/pwa-studio/tree/release/2.0/packages/upward-spec#resolver-reference)

**Comment by supernova-at** [comment]
Closing until we figure out what we want to do with UPWARD docs
