### ISSUE TITLE
Centralize code formatting configuration

### ISSUE THREAD

**Issue by zetlen** [magento-research/pwa-studio#189]
Make [EditorConfig](https://editorconfig.org/), [Prettier](https://prettier.io/), and [ESLint](https://eslint.org/) share common settings as much as possible from a single source of truth.

*Idea: EditorConfig is the simplest and smallest, so any settings that can be inherited from EditorConfig, should be. Use the Node `ini` package to load the .editorconfig file into `prettier.config.js` and `eslint.config.js` and `babel.config.js` files.*

**Comment by awilcoxa** [comment]
closing during backlog cleanup
