### ISSUE TITLE
Spike: Try release management tools

### ISSUE THREAD

**Issue by zetlen** [magento-research/pwa-studio#192]
PWA Studio needs a consistent release process which standardizes and documents changes over time, and pushes releases to different targets based on stability.

Tools that can automate parts of that include:
- [lerna](https://github.com/lerna/lerna) itself (consider turning off independent mode)
- [standard-version](https://github.com/conventional-changelog/standard-version) which enforces [Conventional Commits](https://conventionalcommits.org/) and therefore easily autogenerates good changelogs
- [Unleash](https://github.com/netflix/unleash) which seems to do a bunch of great stuff

**Comment by awilcoxa** [comment]
closing during backlog cleanup
