### ISSUE TITLE
Organize and standardize Labels for issues and PRs

### ISSUE THREAD

**Issue by zetlen** [magento-research/pwa-studio#194]
Large repositories with lots of activity have a system of labels for tagging issue and pull request objects. We have the beginnings of a system, but we need to improve and finalize it, and also bring it in accordance with Community Engineering guidelines.

Labels should be used to indicate:
- Issue type (bug/enhancement/etc)
- Issue priority and/or severity
- Estimated story size
- Relevant packages or areas of concern
- Skillsets required
- Target personas or scenarios supported or blocked by issue
- Relevance to community (good first issue? help wanted?)
- Rewards and achievements for contributors

**Comment by awilcoxa** [comment]
closing during backlog cleanup
