### ISSUE TITLE
Implement PaymentRequest powered shipping address entry at checkout

### ISSUE THREAD

**Issue by zetlen** [magento-research/pwa-studio#209]
## Description

As a shopper, I want to use my device's native personal information entry fields when checking out and completing a purchase in a PWA online store, so that I can feel more trust about the route and storage ofthat information.

## Expected result:

In presence of PaymentRequest at runtime, HTML Shipping Address field hides and is replaced by a launcher to Payment Request API.

Data the user enters into the Payment Request form populates into the quote.

**Comment by awilcoxa** [comment]
closing during backlog cleanup
