### ISSUE TITLE
Implement link to Product Details page in Category product list

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#218]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## Description

https://magento-research.github.io/pwa-studio/venia-pwa-concept/component/product-listing/

![image.png](https://images.zenhubusercontent.com/5a71f21a4b5806bc2bc51012/43798b26-a8b9-404f-bc04-6b85cb0ef31e)

**As a shopper, I want to easily move from a list item representing a product to details for the product, so I can learn more.**

The interaction of tapping or clicking a product listing in a Category or any other product list should navigate to the Product Details page. 

#### Assumptions
- Enhance the product listing currently implemented in Venia for Category pages
- Use the MagentoRouter-wrapped React Router in Peregrine and enhance where necessary
- Navigation should take place fully on the client side

## Tasks

- [ ] *Test that router navigation correctly triggers UrlResolver query*
- [ ] *Add tap handler*

**Comment by Serunde** [comment]
I submitted a pull request that should resolve this issue by wiring the category list component with links to the product full detail pages using their `url_key`. Welcoming any feedback!
https://github.com/magento-research/pwa-studio/pull/227

**Comment by ericerway** [comment]
Partially covered by PR# 254 from @shakyshane.

**Comment by ericerway** [comment]
@jimbo can we confirm which part of this is done already or needs to be groomed/updated as a separate story? I know we have linking now but unsure if this met your initial goals. Thanks!
