### ISSUE TITLE
Setting up PWA Studio on remote server

### ISSUE THREAD

**Issue by Kroonax** [magento-research/pwa-studio#243]
Having trouble setting up PWA Studio on a remote Magento 2.

## This issue is for the following packages:

[x] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## This issue is a:

[ ] Bug
[ ] Feature suggestion
[x] Documentation issue
[x] Other (Having difficulties setting up the whole reverse proxy thing in 'production mode')

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             | 2.2.5 |
| Operating System + version  | Debian 8 |
| node.js version (`node -v`) | 9.10.1 |
| npm version (`npm -v`)      | 5.6.0 |

## Description

When browsing on the Magento URL (let's say https://foo.bar/) the only thing I have is the "Magento" part of the theme, with the title and a white page.

The client.js request ends up in a 404 error.

## Expected result:

Loading the PWA content.

## Possible solutions:

I am trying to figure out a way to use Nginx to reverse proxy from Magento front to the Venia theme app but I cannot figure how to do it...

Does anybody know how to make it work remotely ? (with iptables or nginx or anything else)
If that is the case, could these informations be added to the documentation ?

Thanks in advance!

**Comment by ericerway** [comment]
Reviewing a few outstanding issues; @kroonax can you confirm if this is still happening with the recent UPWARD and 2.3.0 changes? Thanks!

**Comment by awilcoxa** [comment]
closing during backlog cleanup
