### ISSUE TITLE
error in production..

### ISSUE THREAD

**Issue by marcelowu** [magento-research/pwa-studio#257]
![capturar](https://user-images.githubusercontent.com/30912144/44811901-2fd4cd00-abac-11e8-8e7f-2c2731e38a7b.JPG)

**Comment by zetlen** [comment]
Thanks, @marcelowu, but we need more information to proceed. Looks like you have three separate issues; can you please use the Issue Template to tell us more about your operating system, version of Magento, the hostnames of Magento and your dev server?

**Comment by sirugh** [comment]
This issue is stale. Closing for now. @marcelowu or others, if you have this problem please open a new issue.
