### ISSUE TITLE
Integrating Venia sample data with PWA Studio

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#261]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## Description

As a shopper, I want to access Venia product catalog data including simple, complex, bundled, group and eventually bundled types so that I can make a purchase online.

Repository
{"type": "git", "url": "git@github.com:PMET-public/module-product-links-sample-data-venia.git"}
 
Require
"magento/module-product-links-sample-data-venia": "dev-master"

Related to pwa-studio#86 (documentation)

#### Assumptions
- Existing sample data from LUMA (as a backup)
- Extended use of sample data for open source (not just Commerce)

## Tasks

- [ ] Review Venia sample data in raw form (by type)
- [ ] Testing and documentation (as appropriate)

**Comment by ericerway** [comment]
Documentation effort; likely needs to be a metapack from source data.

**Comment by pcvonz** [comment]
Hey, I got a portion of this working. Here is what I added to my composer file:

```json

...
"require": {
        "magento/module-sales-sample-data-venia": "*",
        "magento/sample-data-media-venia": "*",
        "magento/module-product-links-sample-data-venia": "*"
}
"repositories": {
        "1": {
            "type": "git",
            "url": "https://github.com/PMET-public/module-product-links-sample-data-venia.git"
        },
        "2": {
            "type": "git",
            "url": "https://github.com/PMET-public/module-configurable-sample-data-venia.git"
        },
        "3": {
            "type": "git",
            "url": "https://github.com/PMET-public/module-catalog-sample-data-venia.git"
        },
        "4": {
            "type": "git",
            "url": "https://github.com/PMET-public/sample-data-media-venia.git"
        },
        "6": {
            "type": "git",
            "url": "https://github.com/firegento/FireGento_FastSimpleImport2.git"
        },
        "7": {
                "type": "git",
                "url": "https://github.com/PMET-public/module-sales-sample-data-venia.git"
        },
        "9": {
                "type": "git",
                "url": "https://github.com/PMET-public/module-customer-sample-data-venia.git"
        },
        "10": {
                "type": "git",
                "url": "https://github.com/PMET-public/module-tax-sample-data-venia.git"
        }
}
```

I tried adding the following modules as well, but I think they're in an older format. So, I tried the commands listed on [this page](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/declarative-schema/migration-commands.html), but they still caused Magento to crash.

```json

"require": {
        "magentoese/module-venia-catalog-sample-data": "*",
        "magentoese/module-venia-video-sample-data": "*"
}

"repositories": {
        "5": {
            "type": "git",
            "url": "https://github.com/pcvonz/module-venia-catalog-sample-data.git"
        },
        "8": {
                "type": "git",
                "url": "https://github.com/PMET-public/module-venia-video-sample-data.git"
        }
}

```

I think I'm still missing a fairly large portion of data (maybe related to the former packages?) This error is thrown in Venia when I try to go to any product category (ex: `https://magento-venia.local.pwadev:8001/venia-bottoms.html`)

```json
{
  "errors": [
    {
      "message": "Field \"small_image\" of type \"ProductImage\" must have a sub selection.",
      "category": "graphql",
      "locations": [
        {
          "line": 10,
          "column": 9
        }
      ]
    }
  ]
}
```

**Comment by zetlen** [comment]
Hey @pcvonz, thanks for working on this. There are two separate issues here.

1. I don't think you need all the repositories listed here, and definitely the `magentoese` modules aren't necessary. [The modules and repositories listed in this issue](https://github.com/magento-research/pwa-studio/issues/290#issue-361807461) should be all you need. I think the right solution is a shell script which uses the Composer CLI to add the repositories and then require the modules one by one, and then run `bin/magento setup:upgrade` to run their install scripts. That make sense?

2. Your GraphQL error is due to a schema change in the `2.3-develop` HEAD of Magento! Sounds like your instance was updated somehow. When I realized we'd be confronting this, I wrote and PRed a [validator script](https://github.com/magento-research/pwa-studio/pull/318) that would benefit from your review, if you have the time.

**Comment by pcvonz** [comment]
Makes sense.

I tried using the modules you linked, but there is one listed as `module-venia-catalog-sample-data` and links to [this repository](https://github.com/PMET-public/module-venia-catalog-sample-data) the module name is `magentoese/module-venia-catalog-sample-data`. Was this included by mistake?

**Comment by mhhansen** [comment]
hey guys! PR https://github.com/magento-research/pwa-studio/pull/329 has a script to install this sample data, easily with just a few steps.

1. copy the .sh into the Magento folder and give execution permissions.
2. run the script.
3. php bin/magento setup:upgrade && php bin/magento cache:clean

It will install and populate this modules:
```
Magento_CustomerSampleDataVenia
Magento_TaxSampleDataVenia
Magento_CatalogSampleDataVenia
Magento_ConfigurableSampleDataVenia
Magento_SalesSampleDataVenia
```
Not sure if this is the preferred way to ship the script, but I've just tried and works perfectly.

**Comment by bashizee** [comment]
in root folder of magento  rename auth.json.sample to auth.json
{
    "http-basic": {
        "repo.magento.com": {
            "username": "--------------",
            "password": "--------------"
        }
    },
    "github-oauth": {
        "github.com": "-------------"
    }
}
add those details 
for username and password go to https://marketplace.magento.com/customer/account/
create access  key by clicking on market place tab->create new acces key , copy and paste public and private key
in github auth 
go to https://github.com/settings/tokens
and generate new token and paste it
