### ISSUE TITLE
Discovery for root components as main element (WIP)

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#273]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[X] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## Expected result:
Discovery work to support if routing (and loading experience) will be affected when address re-rendering of children happens today. This will help determine if header, other components and routing should occur in the app shell. This will validate and improve extensibility for PWA Studio.

Areas affected: category, CMS, product

Outcome will be a summary of findings and possible demo. Additional stories expected.

**Comment by awilcoxa** [comment]
closing during backlog cleanup
