### ISSUE TITLE
GraphQL product collection query does not support adequate pagination

### ISSUE THREAD

**Issue by zetlen** [magento-research/pwa-studio#282]
**This issue is a link to https://github.com/magento/graphql-ce/pull/175 so that PWA issues can link it as a blocking dependency.**

### Description

New PR as requested here: https://github.com/magento/magento2/pull/17953 

Fixed pagination exception which used to display the wrong number on error, used the total number of pages instead of the current one.

Added pagination information by returning the total pages, making it easier to render navigation using GraphQL.

### Fixed Issues (if relevant)
None

### Manual testing scenarios

1. Create GraphQL product query and query all the page_info fields, total_pages should be the number of pages available
```
page_info {
      page_size
      current_page
      total_pages
    }
```

2. Query products with a currentPage higher than the amount of available pages. You should get an exception message containing the requested page number and the total available pages

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

**Comment by cherdman** [comment]
PR mentioned above has been merged.
