### ISSUE TITLE
Use Renovate for automated dependency updates instead of Greenkeeper

### ISSUE THREAD

**Issue by zetlen** [magento-research/pwa-studio#286]
Our efforts to integrate Greenkeeper and greenkeeper-lockfile have been unsuccessful, but we need some automation to help us manage updates to our many NPM dependencies. We should try [Renovate](https://github.com/marketplace/renovate).

### Greenkeeper downsides

- Requires CI to build every branch, greatly lengthening our build times and causing issues with DangerCI
- Requires a complex CircleCI configuration, producing a confusing build process
- Requires a separate tool, greenkeeper-lockfile, to manage package-lock, causing confusion
- Bot is not whitelisted with our CLA process, so it requires manual administrator merge

### Renovate upsides

- Uses the new Checks feature of Github
- Auto-rebases
- Can merge its own PRs

A couple of other major projects have done this switch.
https://github.com/googleapis/nodejs-common/issues/59
https://bugzilla.mozilla.org/show_bug.cgi?id=1409778

## This issue is for the following packages:

[x] `venia-concept`
[x] `pwa-buildpack`
[x] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## This issue is a:

[ ] Bug
[ ] Feature suggestion
[ ] Documentation issue
[x] Other (Please Specify)

This is a devops chore issue.

**Comment by awilcoxa** [comment]
closing during backlog cleanup
