### ISSUE TITLE
M2ApiResponseError -- `captureStackTrace is not a function`

### ISSUE THREAD

**Issue by pcvonz** [magento-research/pwa-studio#287]
## This issue is for the following packages:

[ ] `venia-concept`
[ ] `pwa-buildpack`
[x] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## This issue is a:

[x] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

`Error.captureStackTrace` is not a method on the `Error` object in Firefox. 

## Expected result:

As a user of Firefox I want an an error returned from a failed request. 

## Possible solutions:

This is straight from the MDN:

```js
// Maintains proper stack trace for where our error was thrown (only available on V8)
// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error
if (Error.captureStackTrace) {
  Error.captureStackTrace(this, CustomError);
}
```

**Comment by zetlen** [comment]
Close by #288.
