### ISSUE TITLE
Use https://github.com/kandy/dev-docker as our official Docker solution

### ISSUE THREAD

**Issue by karlhass15** [magento-research/pwa-studio#290]
Issues with local setup on docker during pulls after approximately 9/17/2018

## This issue is for the following packages:

[x] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## This issue is a:

[ ] Bug
[x] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

Docker

## Expected result:

Docker Local Environment running smoother for fresh pull of master 9/19/2018

## Possible solutions:

- Use https://github.com/kandy/dev-docker as our official Docker solution
- Add a script to install the Venia sample data:

 Current Composer additions
 
Repositories
        {"type": "git", "url": "git@github.com:PMET-public/module-catalog-sample-data-venia.git"},
        {"type": "git", "url": "git@github.com:PMET-public/module-configurable-sample-data-venia.git"},
        {"type": "git", "url": "git@github.com:PMET-public/module-customer-sample-data-venia.git"},
        {"type": "git", "url": "git@github.com:PMET-public/module-sales-sample-data-venia.git"},
        {"type": "git", "url": "git@github.com:PMET-public/module-tax-sample-data-venia.git"},
        {"type": "git", "url": "git@github.com:PMET-public/sample-data-media-venia.git"}
 
Require
        "magento/module-catalog-sample-data-venia": "dev-master",
        "magento/module-configurable-sample-data-venia": "dev-master",
        "magento/module-customer-sample-data-venia": "dev-master",
        "magento/module-sales-sample-data-venia": "dev-master",
        "magento/module-tax-sample-data-venia": "dev-master",
        "magento/sample-data-media-venia": "dev-master"

**Comment by Stolr** [comment]
Hi guys ,  Not sure this docker-compose would be good for development.

I think containers for development need clean images minimalist. This docker-compose is a bit too much I think. 

The base is pretty cool with script and stuff but can be optimized for development.

For example , no  point of adding nfs / samba on development environment. 

Is there any project running for having some containers for dev and for prod ? Also having k8s deployment helm chart for exemple ? I'd be glad to help

**Comment by zetlen** [comment]
@Stolr I know there is some disagreement on how well docker-compose works for development. I want something clean and minimal too--and we'd love your help!

Currently there is no project for a general-purpose k8s deployment configuration. The Magento Enterprise Cloud team is working on a deployment configuration with our internal tools, but it won't be exportable. If you'd like to help us by creating some images, we'd be very grateful.

**Comment by awilcoxa** [comment]
Given @sharkySharks work for docker solution, would propose closing this issue. Want Kayden to weigh in prior to any action.

**Comment by sharkySharks** [comment]
moving forward with docker-compose for local setup. I am a fan of K8 but may not be the best use case at this time. Happy to see folks contribute to the container solutions as we expand them though 👌
