### ISSUE TITLE
[Documentation] Add a "Last Updated" feature

### ISSUE THREAD

**Issue by jcalcaben** [magento-research/pwa-studio#321]
## This issue is for the following packages:

[ ] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[x] `pwa-devdocs`

## This issue is a:

[ ] Bug
[x] Feature suggestion
[x] Documentation issue
[ ] Other (Please Specify)

## Description

Create a "Last Updated" feature that shows when a documentation topic has been last updated.

This feature request is the result of usability testing feedback.

## Expected result:

Topics in the documentation site shows when each topic has been last updated.

**Comment by awilcoxa** [comment]
Closing as low priority, we'll revisit/reopen if needed in the future.
