### ISSUE TITLE
For not logged in users each route change triggers a minicart update

### ISSUE THREAD

**Issue by Igloczek** [magento-research/pwa-studio#335]
## This issue is for the following packages:

[x] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## This issue is a:

[x ] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

## Description

While the user is not logged in, each route change triggers a minicart update, so two kinda pointless requests.

## Expected result:

Ask for these data once, cache them, update only on specified actions.

**Comment by zetlen** [comment]
Yes, this is very annoying! It has to do with the entire view regenerating on navigation. We should implement some `shouldComponentUpdate` methods to make that happen less.

**Comment by pcvonz** [comment]
Since @jimbo created the `app.js`, miniCart doesn't re render on every route change. This is a non issue as far as I know.
When the `miniCart` is opened, it does trigger those two requests still. Can I get a confirmation that this is still something that should be worked on, or is that desired behavior?

**Comment by zetlen** [comment]
That's desired behavior; if the minicart changed in another tab or session, then this session won't know until it requests new data. Basically, cart data is volatile and should be regularly re-checked.

**Comment by zetlen** [comment]
And you're right--this was fixed by @jimbo in #268.

**Comment by ericerway** [comment]
Marking as closed; this is fixed with #268 -- @pcvonz let us know if this continues to be an issue. Thanks!
