### ISSUE TITLE
Can't find pwa-module when cloning repo

### ISSUE THREAD

**Issue by ltdolan** [magento-research/pwa-studio#336]
## This issue is for the following packages:

[ ] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[x ] `pwa-module`
[ ] `pwa-devdocs`

## This issue is a:

[ ] Bug
[ ] Feature suggestion
[ ] Documentation issue
[X ] Other (Please Specify)

Either incorrect setup instructions or missing module....

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             | 2.3 |
| Operating System + version  | Ubuntu 14.04  |
| node.js version (`node -v`) | 8.12 |
| npm version (`npm -v`)      | 6.4.1 |

## Description

Used the following to clone :

git clone https://github.com/magento-research/pwa-studio.git

## Expected result:

Expect for there to be a "/pwa-studio/packages/pwa-module folder, however, this appears blank, and I don't see it in the repo anymore.

Not sure if the steps to set up have changed (in which case the instructions at https://magento-research.github.io/pwa-studio/venia-pwa-concept/setup/  are no longer correct).
-->

**Comment by mhhansen** [comment]
as part of UPWARD `release/2.0` that package (pwa-module) is no longer included.
ensure first you are @ `release/2.0` branch. (I think you should, since when you clone the repo you land in that branch).

then, while being at the project root folder, you can:
```
npm run clean:all
npm install
npm run build
npm run watch:venia
```
`clean:all` will remove all `dist/` + `node_modules/` folders

btw: docs were updated a few mins ago :)

**Comment by zetlen** [comment]
Thanks for the report and sorry that the transition was rough. I'm closing this issue for now because `pwa-module` is removed, but if you have any further questions, please don't hesitate to reopen!
