### ISSUE TITLE
Failures when `MAGENTO_BACKEND_DOMAIN` does not have trailing slash

### ISSUE THREAD

**Issue by DrewML** [magento-research/pwa-studio#337]
Currently, you get failures when `MAGENTO_BACKEND_DOMAIN` does not have a trailing `/` at the end. The name of the field has `DOMAIN`, which makes it surprising a `/` is required. The code should be updated to drop this requirement/bug.

**Comment by rowan-m** [comment]
This should be changed to `MAGENTO_BACKEND_URL` to more correctly describe what it is. Trailing slash should be optional. Path should be taken into account in case someone is running their back-end under a path.

**Comment by zetlen** [comment]
All true. I'll update #339 to change this variable and print a warning.
