### ISSUE TITLE
Need more actionable error message when `MAGENTO_BACKEND_DOMAIN` is not defined

### ISSUE THREAD

**Issue by DrewML** [magento-research/pwa-studio#342]
Steps to replicate:
1. Copy `example.env` in `venia-concept` to `.env`
2. Do _not_ uncomment `MAGENTO_BACKEND_DOMAIN`

The error you get it:

```sh
BuildpackValidationError: PWADevServer: Invalid configuration object. .configure(config) was called with a configuration object that has the following problems:
	- backendDomain must be of type string
```

For users setting up for the first time, this error does not provide easy instructions to get fixed.

**Comment by awilcoxa** [comment]
closing during backlog cleanup
