### ISSUE TITLE
Peregrine publish to npm doesn't include code

### ISSUE THREAD

**Issue by DrewML** [magento-research/pwa-studio#343]
https://unpkg.com/@magento/peregrine@2.0.0-rc2.0.5/

![image](https://user-images.githubusercontent.com/5233399/46666667-90055880-cbc7-11e8-8c6d-4f6448d85b38.png)

**Reported in Slack**
![image](https://user-images.githubusercontent.com/5233399/46666672-9562a300-cbc7-11e8-8e82-13f1eab7488e.png)

**Comment by real34** [comment]
Similar to what happened with upward-js package last week.

I think https://github.com/magento-research/pwa-studio/blob/a4c8c5a7327457e8f2c8f08b8e17399b4b8ee382/packages/peregrine/package.json#L20 should be executed using `npx` (see fix for upward made in https://github.com/magento-research/pwa-studio/commit/06e2f907826586d2b399271784b59545ff4031de#diff-85fd7ec16271bfcd3b7a870b232a7915R9)
