### ISSUE TITLE
Country details blocking Shipping Address saving on Venia PWA

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#345]
![image](https://user-images.githubusercontent.com/2686596/46667657-93e6aa00-cbca-11e8-9536-18ce2b97fe27.png)

Checkout is blocked when using UK-based Cloud of 2.3.0 (https://mage23.merewood.org) on Venia PWA which affects "country" and disables how a Shipping Address is saved. Screenshot attached.

Upon resolution this should allow a complete purchase.

**Comment by ericerway** [comment]
> I took a look at our code and found the reason of the issue, I am going to create a pull request.
> Also right now we implemented support only for regions code, so after my fix if you enter MI it should work. Do we also need to add support of full region names, we just need to edit this line https://github.com/magento-research/pwa-studio/blob/release/2.0/packages/venia-concept/src/actions/checkout/asyncActions.js#L119?
> 
> Pull request #383

Thanks @Starotitorov - for MVP let's keep to US but need to expand to a global form right after this release. As a reference storefront this can be extended to any region we are just providing an example here. Thanks again!

**Comment by Starotitorov** [comment]
Eric, now we support not only US, we support other countries too. But we search region information using only state code that consists of 2 letters, we can also implement searching by full state name.

**Comment by ericerway** [comment]
Understood, thanks for the clarification with the new reducer. Looking forward to seeing this tested and merged. Thanks!

**Comment by zetlen** [comment]
Closed by #383.

**Comment by zetlen** [comment]
That is, fixed by it. Thanks @Starotitorov !
