### ISSUE TITLE
Feedback on page: /pwa-buildpack/project-setup/create-theme-files/

### ISSUE THREAD

**Issue by michaelbakertup** [magento-research/pwa-studio#356]
On theme.xml (and registration.php) in these code examples, there is a space at the start. If one just copies these without removing that space by using the copy feature on this page, then magento throws and error when going to the admin pages complaining about xml can only be at the start of document.

## This issue is for the following packages:

[ ] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[ ] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

**Comment by ericerway** [comment]
Thanks @michaelbakertup! -- we will take a look at it /cc @zetlen

**Comment by zetlen** [comment]
Thanks, @michaelbakertup. We are recreating the code examples now that we are no longer relying on Magento Theme XML, so those files are no longer part of the project. See #181, #322, and #323.
