### ISSUE TITLE
Homepage thumbnail images for Categories in Venia (PWA)

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#364]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[X] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

Thumbnail images are missing from each of the Venia categories. These can replaced programmatically by the first image in each category.

## Expected result:

Thumbnail images shown.

## Possible solutions:

Possible GraphQL/REST API coverage needs. Need to review options.

**Comment by zetlen** [comment]
Noting that on today's Venia sample data conference call, the SC team said they would explore adding category images to the default data set.

**Comment by Jordaneisenburger** [comment]
Hi,

I've also encountered this issue and resolved it by removing `pub` from `/pub/media/catalog/category/` in `components/CategoryList/categoryList.js` not sure if this is the right approach but it works.

**Comment by zetlen** [comment]
Thanks, @Jordaneisenburger. We do need to remove `/pub` from our media URLs, but this is also an issue where the standard Venia sample data doesn't include category images. We've got a workaround in #402.
