### ISSUE TITLE
[Spike] Adding of URL for drawers. R&D

### ISSUE THREAD

**Issue by dmtrkad** [magento-research/pwa-studio#367]
As a developer, I want to initiate an investigation process of adding direct URLs to Sign in/Sign up forms.

As a result, we do decide whether we need to implement separate URLs for this forms.

In case we make a decision to go with this solution, a **demo scenario** will be 

1. We will implement URLs for separate states of the navigation drawer (Left)

**Acceptance criteria:** 

1.  Application will have URLs for separate states of the navigation drawer.
2. Users' roles configuration differences will be specified after finishing with the research part of this spike 

**Original estimate: 18h**  

_Originally posted by @Starotitorov in https://github.com/magento-research/pwa-studio/issues/267#issuecomment-428565928_

**Comment by awilcoxa** [comment]
closing during backlog cleanup
