### ISSUE TITLE
npm run watch:all does not work

### ISSUE THREAD

**Issue by php4umagento** [magento-research/pwa-studio#389]
## This issue is for the following packages:

[X ] main 

## This issue is a:

[ X] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             | regardless |
| Operating System + version  |Ubuntu 18.04.1 LTS |
| node.js version (`node -v`) | v8.10.0 |
| npm version (`npm -v`)      | 6.4.1 |

## Description

after running `npm run watch:all` there is a fatal error

```
> node scripts/watch-all.js

module.js:549
    throw err;
    ^

Error: Cannot find module 'execa'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/xxx/Projects/pwa-studio/scripts/watch-all.js:3:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @magento/pwa-studio@1.1.0 watch:all: `node scripts/watch-all.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @magento/pwa-studio@1.1.0 watch:all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxx/.npm/_logs/2018-10-18T14_10_44_009Z-debug.log
```

## Expected result:

command is executed without an error

## Possible solutions:

missing dependency execa

**Comment by mhhansen** [comment]
hey @php4umagento did you get all the dependencies for the project before running the `watch:all` script? you can do that by running `npm install` in the project root.

tried to reproduce this with an updated `release/2.0` local branch, and was able only without running the install. `execa` it's a dependency from `pwa-builpack` package, and gets installed when you run `npm install`. let us know if that's not the case, thanks!

**Comment by php4umagento** [comment]
@mhhansen hey, this is weird. I promise that I did npm install before. I did that again and now everything is  in order.

**Comment by mhhansen** [comment]
cool, glad to hear it's working now!
