### ISSUE TITLE
Update mail templates for Venia (PWA)

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#390]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## Description

![image](https://user-images.githubusercontent.com/2686596/47172464-2ecd3b80-d2d1-11e8-9cdd-894372ba0926.png)

As a shopper, I want a Venia branded email for password reset and subscriptions so that I can trust that it's coming from a trusted source.

- Reset your Venia Store password (requested on Venia storefront)
- Welcome to Venia Store (subscription)

#### Assumptions
- Existing LUMA mail templates for password reset and subscriptions

## Tasks
[ ] Find and replace LUMA artwork and text/copy instances with Venia (Magento 2)
[ ] Review and update links to password, account and others with Venia storefront
[ ] Testing and documentation (https://github.com/magento-research/pwa-studio/wiki/Documentation-Guidelines)

**Comment by dmtrkad** [comment]
@ericerway , @zetlen, @awilcoxa Probably we need a find a solution  as a 1st step

**Comment by zetlen** [comment]
For now, email templates should be implemented manually using the same original assets used to build the PWA. We need to talk about what kind of email workflow is acceptable; Magento frontend developers who maintain local instances can edit email templates directly, but if you're working from a remote instance in our new workflow, the story is less clear. Adding labels to indicate that further discussion is required.
