### ISSUE TITLE
redux-thunk issues with installing PWA development server (cannot GET /)

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#406]
## This issue is for the following packages:

[ ] `venia-concept`
[ ] `pwa-buildpack`
[X] `peregrine`
[ ] `pwa-devdocs`
[X] `upward-js`
[ ] `upward-spec`

## This issue is a:

[ ] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

Thanks , now having the error  `Module not found: Error: Can't resolve '@magento/peregrine' in '/var/www/magento23/src/pwa-theme/src'
` So I copied the packages from venia concept to my node module ,

And now :

`Module not found: Error: Can't resolve 'redux-thunk' in '/var/www/magento23/src/pwa-theme/node_modules/@magento/peregrine/dist/store/middleware'`

I tried to run npm install inside peregrine node module but doesn't seems to resolve the issue 

add "redux-thunk": "^2.3.0" to the package.json from @magento/peregrine and install it

if you run `npm start` it should compile but give blank page with `cannot get /`

## Expected result:

No issues when installing PWA development server.

**Comment by Jordaneisenburger** [comment]
This issue is related to #343 since the src code is not included inside the publish to npm
