### ISSUE TITLE
All the images from magento fallback 404 on venia

### ISSUE THREAD

**Issue by thanhdv2811** [magento-research/pwa-studio#413]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[X] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             | 2.3 |
| Operating System + version  | Mac Os 10.14 + Apache 2.4 + Php 7.1.23 |
| node.js version (`node -v`) | 10.8.0 |
| npm version (`npm -v`)      | 6.2.0 |

## Description

I installed magento 2.3 by cloning the code from GitHub and PWA studio by following this document https://magento-research.github.io/pwa-studio/venia-pwa-concept/setup/
![screenshot at oct 23 20-17-55](https://user-images.githubusercontent.com/20705278/47401705-a5a08380-d76c-11e8-9d24-c633d40f953a.png)
After that, I opened the browser to access the PWA page but all the product images are getting 404 error. The button filter/sort on category page can't be clickable also.
<img width="1264" alt="screenshot at oct 23 20-20-02" src="https://user-images.githubusercontent.com/20705278/47401754-d385c800-d76c-11e8-9bcf-d9a33aecde06.png">

## Expected result:

The image is fully loaded from magento and the filter/sort button can be clickable.

**Comment by tungdtisobat** [comment]
I have the same problem when install latest version. When i ran bin/magento catalog:image:resize, a message throw: File '/home/cloudpanel/htdocs/magento23eepwa.demo/pub/media/catalog/product/v/a/va11-sg_main.jpg' does not exist.

**Comment by Kroonax** [comment]
Same problem here, did you find a solution ?

**Comment by jcodo** [comment]
I resolved this issue by copying the contents of `vendor/magento/sample-data-media-venia/catalog` to `pub/media/catalog`. Hope this helps.

**Comment by deepanshu27193** [comment]
Same Here.

**Comment by thanhdv2811** [comment]
> I resolved this issue by copying the contents of `vendor/magento/sample-data-media-venia/catalog` to `pub/media/catalog`. Hope this helps.

It didn't solve my problem.
I still can reproduce it in magento 2.3 release version and pwa-studio tag v2.0.0-rc.14

**Comment by deepanshu27193** [comment]
At my end, It's working perfect with the default cloud URL.
Only changing the MAGENTO_BACKEND_URL to local codebase gives the problem.

I have found the code which is expecting Magento to be hosted from the pub directory rather than from the root directory. 
Issue is at: 
https://github.com/magento-research/pwa-studio/blob/release/2.0/packages/venia-concept/src/util/makeMediaPath.js#L19

Solution:
Create a virtual host and point it to the pub directory instead of the root directory.

Now no more 404 on category and product images.
Everything seems to be working now.

**Comment by awilcoxa** [comment]
closing during backlog cleanup, if issues still exists please reopen for future prioritization.

**Comment by chakravarthykalyan90** [comment]
I am facing the same issue with recently cloned PWA Studio repo, not able to find this file "https://github.com/magento-research/pwa-studio/blob/release/2.0/packages/venia-concept/src/util/makeMediaPath.js#L19"

I have the virtual host pointing to /pub directory and https enabled. Please help.

**Comment by tjwiebell** [comment]
@chakravarthykalyan90 - 'makeMediaPath' was replaced by `makeUrl` in `2.0.0`, this error does not indicate you have the latest code, which would now be `2.1.0`. Try a fresh clone or make sure your environment is clean, and let us know if you're still encountering issues.
