### ISSUE TITLE
[Documentation]: Create "Known Issues" Page

### ISSUE THREAD

**Issue by awilcoxa** [magento-research/pwa-studio#415]
## This issue is for the following packages:

[ ] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ x] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[ ] Bug
[ ] Feature suggestion
[ x] Documentation issue
[ ] Other (Please Specify)

## Description

Documentation currently lacks an aggregate list of known issues. This would be helpful to address community/customer questions regarding implementation details or issues, which currently costs dev/PdM cycles to address. Maintaining a living document of "known issues" as we continue to move forward with PWA development can help to proactively address questions and will create a single reference point for distribution/sharing. 

## Expected result:

Create a page within public facing documentation to track known issues, bugs, or design gaps that can be easily referenced for the community. We should be able to quickly update/modify to ensure the document is timely and relevant at all times.

**Comment by ericerway** [comment]
Let's investigate methods this can be done with automation.

**Comment by jcalcaben** [comment]
Talked with @awilcoxa and came to an agreement to close this issue as it would require too much maintenance to stay relevant.

Open to revisiting this if anyone can come up with a more automated/maintainable way of generating and updating the information.
