### ISSUE TITLE
[Bug] Common Input does not handle initial value correctly 

### ISSUE THREAD

**Issue by Starotitorov** [magento-research/pwa-studio#416]
## This issue is for the following packages:

[x] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[x] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             | 2.3  |
| Operating System + version  | Ubuntu 18.04  |
| node.js version (`node -v`) | 8.12.0  |
| npm version (`npm -v`)      | 6.4.1  |

## Description

The issue related to order confirmation page story https://github.com/magento-research/pwa-studio/issues/267 .When user clicks create account button we navigate user to create account screen with form, some of the form fields are prefilled with email, first name and last name from order information, but user can not submit form, because local state of the form does not contain values that were passed as initial values to input components.

![create-account-form](https://user-images.githubusercontent.com/11873143/47444819-03aa8680-d7c0-11e8-8582-97205bc68fd4.PNG)

I pass initialValue to each of our Input components inside create account form, but the Input component does not handle initial values properly, it does not call onChange callback in this case.

## Expected result:

User should be able to submit create account form with prefilled email, first name, last name when he fills other fields.

## Possible solutions:

We need to handle initialValue in our common Input component properly.

**Comment by JStein92** [comment]
Good catch - thanks for finding this.

**Comment by awilcoxa** [comment]
PR #592 is merged
