### ISSUE TITLE
[Bug] Can not scroll create account form when open it in drawer

### ISSUE THREAD

**Issue by Starotitorov** [magento-research/pwa-studio#421]
## This issue is for the following packages:

[x] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[x] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

User can not scroll create account form when open it in drawer.

Screenshot for Iphone5.

![create-account-iphone5](https://user-images.githubusercontent.com/11873143/47489686-e02f1c80-d84f-11e8-8c07-8ea09c44d56b.PNG)

It looks strange when you try to reproduce the issue on Iphone7, you enter some invalid data and after submitting the form you can see validation error, which is displayed below the submit button.

![create-account-iphone7](https://user-images.githubusercontent.com/11873143/47489812-25ebe500-d850-11e8-94ff-4806a2ff5c3e.PNG)

@ericerway, @zetlen, please approve that this is a bug and should be fixed.

## Expected result:

User should be able to scroll create account form in drawer.

**Comment by codeAdrian** [comment]
Hello @zetlen @ericerway , I would like to work on fixing this issue. I suggest fixing it by applying CSS to allow scroll in all drawers (navigation, minicart, etc.).

**Comment by codeAdrian** [comment]
Hi @JStein92 , I was waiting for a go-ahead, but if you have created a PR, feel free to take this. Thank you.

**Comment by zetlen** [comment]
Closed by #590.
