### ISSUE TITLE
[Improvement] Collect all rest API requests from application and implement restService

### ISSUE THREAD

**Issue by Starotitorov** [magento-research/pwa-studio#423]
## This issue is for the following packages:

[x] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[ ] Bug
[x] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             | 2.3  |
| Operating System + version  | Ubuntu 18.04  |
| node.js version (`node -v`) | 8.12.0  |
| npm version (`npm -v`)      | 6.4.1  |

## Description

Right now, for example, we can not change rest API version globally by changing only one constant, also it is impossible to update some request urls globally.

## Expected result:

It is better to store all code related to api requests in one place. We should be able to easily change API version globally and update urls for some request.

## Possible solutions:

I propose to implement restService with methods signIn, createAccount, createGuestCart, addItemToCart and hide some implementation details inside this service, it will increase maintainability of the code. 

```
// in restService.js

const API_VERSION = 'V1'

const addItemToCart= (cartId, item) => {
  return request(
        `/rest/${API_VERSION}/guest-carts/${cartId}/items`,
        {
            method: 'POST',
            body: JSON.stringify({
                cartItem: item
            })
        }
    );
  }
}

export default {
  api: {
    addItemToCart,
    // Other methods will be here
  }
}
```

@awilcoxa, @ericerway, @zetlen, @jimbo, I guess we need to do this.

**Comment by zetlen** [comment]
We are deliberately not making any efforts to further integrate REST APIs into our codebase. Under any other circumstances, this would be a great idea. But our project strongly prefers GraphQL as a data access layer, and we want to maintain pressure on the Magento GraphQL effort to add coverage. So we don't want to make it more convenient to use REST.

We have to strike a balance between feature implementation velocity, app performance, and our desire to make REST work "stand out" so we all remain conscious of the missing areas of GraphQL coverage. So we have made this conscious decision to leave REST code paths un-optimized.

I know this is an unusual choice, and we appreciate your efforts to improve the codebase.
