### ISSUE TITLE
Test Framework: TestCafe Implementation

### ISSUE THREAD

**Issue by awilcoxa** [magento-research/pwa-studio#440]
## This issue is for the following packages:

[ ] `venia-concept`
[ x] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[ ] Bug
[x ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

## Description

Implement a new integration testing framework (testcafe) in order to improve {@james to help fill in details}. This effort should include discovery to determine the full impact of this new library including benefits/risks and level of effort of implementing. 

## Expected result:

Integration test approach is fully developed and implemented into PWA. Approach should be fully validated from all necessary internal stakeholders. 

## Possible solutions:

{@james to fill in details with EPAM team}

**Comment by vitalics** [comment]
AT tasks:

- [ ] one test implementation
- [ ] integrate into CI/CD
- [ ] docs

**Comment by vitalics** [comment]
currently we try to use MFTF, for testing existing application
