### ISSUE TITLE
PWA Style and Components Guidelines

### ISSUE THREAD

**Issue by awilcoxa** [magento-research/pwa-studio#445]
## This issue is for the following packages:

[ x] `venia-concept`
[ ] `pwa-buildpack`
[x ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[ ] Bug
[ ] Feature suggestion
[ x] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

In order to ensure consistency across component and UX/UI, we should create documentation around design specifications that allows for developers that are new to the project to adhere to accepted design patterns. This documentation should be lightweight in nature and should create a common foundation for component use and styling.

**Comment by ericerway** [comment]
Tentative estimate of 3 points - @jcalcaben let me know if this should be updated. Thanks!

**Comment by jcalcaben** [comment]
I think this can be closed as a copy of #517
