### ISSUE TITLE
[Feature] Integrate Lighthouse CI into current CI/CD process

### ISSUE THREAD

**Issue by vitalics** [magento-research/pwa-studio#447]
## This issue is for the following packages:

[x] `venia-concept`
[x] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[ ] Bug
[x] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

Use lighthouse-ci for every PR and integrate into CD/CD. It will be add pwa statistic, such as performance, accessibility, best practicies. Also in future we can add required value.

https://github.com/ebidel/lighthouse-ci

**Comment by vitalics** [comment]
for now we need to limit it to the default branch and not to PRs, since PRs are not deployed.

**Comment by cherdman** [comment]
Looking into CI/CD improvements, including integrating Lighthouse, Sauce Labs, and Web Page Test: https://app.zenhub.com/workspaces/pwa-studio-5b23bf79d195c635a1a218ce/issues/magento-research/pwa-studio/1185
