### ISSUE TITLE
[Bug]: HOC without wrapper name. Name is undefined

### ISSUE THREAD

**Issue by vitalics** [magento-research/pwa-studio#449]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[X] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description
HOC without wrapper component. Name is undefined
![image](https://user-images.githubusercontent.com/8816260/47998292-da6aee00-e10f-11e8-9b52-208a224591a7.png)

## Expected result:
HOC with naming. In this case: `Classify(Section)`

**Comment by supernova-at** [comment]
Closed by #667.
