### ISSUE TITLE
[Bug]: Main page can not be loaded

### ISSUE THREAD

**Issue by vitalics** [magento-research/pwa-studio#456]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[X] `upward-js`
[ ] `upward-spec`

## This issue is a:

[X] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description
Phantom bug. When user load image, upward.js return error, since `JSON.parse()` is failed
![image](https://user-images.githubusercontent.com/8816260/48063221-6a26a000-e1d5-11e8-9087-4e1a96553aac.png)

## Expected result:
Main page is loaded without upward error

## Possible solutions:
`venia` can send not valid JSON, and `upward` return an error

**Comment by zetlen** [comment]
This error is not well surfaced by the staging server's debug middleware. I think this exposes a need to improve stack traces and error behavior in UPWARD and upward-js. For instance, if a GraphQL endpoint provides an invalid response (which is what caused this error), and there is no recovery path in the UPWARD tree, the server should respond with an [HTTP 502](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502).

**Comment by ericerway** [comment]
@vitalics can you confirm if this is still happening with the recent changes? Thanks.

**Comment by vitalics** [comment]
@ericerway it happens, when something wrong with backend side. I suppose that Magento cache is full and cannot put the new objects. The issue is not in PWA-Studio, it can be Magento internal issue

**Comment by vitalics** [comment]
@ericerway Same error is visible if Magento backend is failed and not respond for venia rest requests

**Comment by ericerway** [comment]
OK, we'll keep open for now and find a better approach to handle failed Venia REST requests then. Thanks @vitalics.

**Comment by zetlen** [comment]
@ericerway @vitalics The upward-js library needs better error handling, with pointers to source code and virtual stack traces. The best way to accomplish this is with a concrete syntax tree, and I have a small project to refactor UPWARD to include one. I just opened https://github.com/magento-research/pwa-studio/issues/645 to track this.

**Comment by vitalics** [comment]
I suppose we can close this issue.
Reason: a new story just opened
