### ISSUE TITLE
Venia stock photography review/replace (non-catalog)

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#460]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[ ] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

Review and replacement of Venia stock photography (non-catalog) with royalty free selections as appropriate. Selections should match style and tone of product photography. This is a dependency of the CMS work for MVP, affecting homepage and other areas.

## Expected result:

List of recommended photography, mapping of what should be replaced.

**Comment by soumya-ashok** [comment]
Adobe does have some good stock photo options, but none of those would be royalty free. For a start, maybe we could leverage an existing Venia lifestyle image such as this one - https://master-7rqtwti-a6terwtbk67os.demo.magentosite.cloud/media/gene-cms/v/e/venia_outfit-3_0943_2.jpg for one of the home page images.

It does not really match the tone / aesthetic we have at the moment, but satisfies the royalty-free consideration.

**Comment by ericerway** [comment]
@soumya-ashok thanks for your help; let's add this as a homepage image below the categories for now to demonstrate the CMS. We can link to venia-skirts when ready but this can be static for now. Thanks!

**Comment by soumya-ashok** [comment]
40% off banner on the home page now has the Venia lifestyle image - https://magento.invisionapp.com/share/K5P65T3HVRQ
