### ISSUE TITLE
Saving address in Checkout freezes without correct State abbreviation

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#462]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[X] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

When entering a SHIPPING ADDRESS in the Venia checkout, if the State is not a valid two-letter abbreviation (MI for Michigan) the SAVE functionality will freeze without details shared to customers.

![image.png](https://images.zenhubusercontent.com/5a71f21a4b5806bc2bc51012/d9715f95-6fd4-4fe3-9491-ec58c6c38560)

![image.png](https://images.zenhubusercontent.com/5a71f21a4b5806bc2bc51012/0aeefa64-f1ce-443d-8552-41f7c01fbfdc)

## Expected result:

Messaging or handling of improper typed form data including State.

**Comment by AlexeyKaryka** [comment]
@soumya-ashok could you please provide me styles for the state field and validation block when state has validation error?

**Comment by AlexeyKaryka** [comment]
@jimbo could you please clarify where I should place common styles for incorrectly filled fields and for validation blocks?

**Comment by soumya-ashok** [comment]
@AlexeyKaryka - I have made some changes to form field styles based on a detailed discussion with @jimbo and @jcalcaben today. I will share the updated error one with you shortly.

**Comment by soumya-ashok** [comment]
Required form field, when the input is active and there is an error -
![form-field-active-required-error](https://user-images.githubusercontent.com/25960021/48644969-d78eb980-e9a9-11e8-8c70-f53899e2597c.png)

Required form field, when the field is not active and there is an error -
![form-field-static-required-error](https://user-images.githubusercontent.com/25960021/48644973-dbbad700-e9a9-11e8-8e69-81e00f26d9e7.png)

**Comment by pcvonz** [comment]
@AlexeyKaryka Hey, how far did you get in this issue? @JStein92 Already created a lot of the styles. I migrated them into a new component `<InputWrapper />`. You can take a look at what I've done [here](https://github.com/bargreenellingson/pwa-studio/tree/shipping-address-validation-454). Hopefully we didn't duplicate a lot of work :wink:
![address](https://user-images.githubusercontent.com/6378569/49317336-ef396800-f4a8-11e8-9083-2244a4bc23d6.gif)

**Comment by AlexeyKaryka** [comment]
@pcvonz Hi, I worked with this issue about 4 days. You can take a look at my pr https://github.com/magento-research/pwa-studio/pull/492
As I see from attached animation you've changed placement of address form fields from 2 fields per row to 1

**Comment by pcvonz** [comment]
Yeah, that's the layout from this mockup: https://magento.invisionapp.com/share/WQN5F7BYBPG#/screens/326530316

**Comment by AlexeyKaryka** [comment]
@pcvonz As far as I see there are now issues to implement this mockup

**Comment by awilcoxa** [comment]
PR is merged, existing bug is being tracked through separate issue #735
