### ISSUE TITLE
Navigate user from order confirmation page to create account page

### ISSUE THREAD

**Issue by Starotitorov** [magento-research/pwa-studio#502]
## This issue is for the following packages:

[x] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[ ] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

When user clicks on 'Create an Account' button, we need to redirect him to create account page.

**Comment by Starotitorov** [comment]
https://github.com/magento-research/pwa-studio/pull/496

**Comment by dmtrkad** [comment]
@zetlen , @jimbo , @supernova-at Could you please review a PR in order to continue with next steps ?
