### ISSUE TITLE
[Improvement] Add support of empty and loading states to List from peregrine

### ISSUE THREAD

**Issue by Starotitorov** [magento-research/pwa-studio#503]
## This issue is for the following packages:

[ ] `venia-concept`
[ ] `pwa-buildpack`
[x] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[ ] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

We need to add support of empty and loading states to List component from '@magento/peregrine'.

**Comment by awilcoxa** [comment]
closing during backlog cleanup, if issues still exists please reopen for future prioritization.
