### ISSUE TITLE
Implement endpoints to fetch data for purchase history and order details pages

### ISSUE THREAD

**Issue by Starotitorov** [magento-research/pwa-studio#506]
## This issue is for the following packages:

[ ] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[x] `upward-js`
[ ] `upward-spec`

## Description

Right now Magento allows to fetch data about orders only for admin role. We need to use /orders endpoint to fetch data for the purchase history page https://github.com/magento-research/pwa-studio/issues/294. We also need /orders/:orderId endpoint for order details page https://github.com/magento-research/pwa-studio/issues/350.

We need to implement resolver for our upward server to implement fetching of real data for this pages. So, we need to implement endpoints on upward side which will add admin authorization token and generate query to filter orders by customer. This endpoints also requires security check of customer authorization token, in this case user will be able to fetch only information about his orders.  

## Tasks
- [ ] Implement endpoints on upward server side to fetch information about all orders and each separate order for the particular customer.

**Comment by ericerway** [comment]
@tjwiebell @jimbo @zetlen or @supernova-at can we verify if this is still needed with new GraphQL coverage in 2.3.1 or should we close? Cleaning up a few dependencies as we unlock a few partially complete Venia experiences. Thanks.

**Comment by zetlen** [comment]
@ericerway Thanks for reminding us. I think we can close this for now, as GraphQL coverage is proceeding adequately for our feature development and we'd much prefer to do it that way. UPWARD will need to be able to use REST soon, but I think that's a more general use case than this.
