### ISSUE TITLE
Implement some kind of server-side rendering for SEO

### ISSUE THREAD

**Issue by Kroonax** [magento-research/pwa-studio#510]
Referencing #247 , we need to have some kind of content generated/served by the server.

## This issue is for the following packages:

[x] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[ ] Bug
[x] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             | 2.3 |
| Operating System + version  | Not relevant |
| node.js version (`node -v`) | Not relevant |
| npm version (`npm -v`)      | Not relevant |

## Description

At the moment, any SEO bot will fetch the PWA as it is without Javascript : An empty HTML page.
Considering the fact that e-commerce is typically SEO-heavy (and rightfully needs SEO-heavy pages) and a lot of users of e-commerce require top-notch indexing. This is temporarily a dead-end.

SEO bots are stupid, we cannot deny that. We are here in 2018 with low end hardware outclassing high end hardware from 6 years ago and 2018 smartphones outclassing laptops from 5 years ago. Yet SEO bots and indexers still require/needs the server to render and serve everything. Those same bots companies developing JS technologies that are not SEO friendly either.

## Expected result:

User gets served server-side rendered static HTML + Javascript.

## Possible solutions:

Using React-DOM and React-Helmet to render the JSX server-side and serve it to client the using a minimized version of Redux to manage the state from client ? Kind of sounds like Meteor to me.

Do some of you actually gave it a successful try ?

**Comment by ericerway** [comment]
Closing this issue in favor of #1110 which proposes additional SSR improvements to UPWARD. Thanks for submitting!
