### ISSUE TITLE
Discovery for Account details in Venia (MVP+)

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#514]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## Description

As a shopper I want to view account details on Venia including contact, address, orders and other related information so that I can make an informed, accurate or repeat purchase in the future.

#### Assumptions
- Discovery will be timeboxed to be part of a larger effort; three (3) points max
- Account and authentication coverage in GraphQL/REST API
- Discovery for this task is READ ONLY at this time; assume basic LUMA presentation
- Utilize page vs. slider for Account details w/r/t/ Account menu
- Focus on content and address details first; orders, wish list may require new issue

## Tasks
[ ] Discovery for GraphQL/REST API coverage with authentication and account
[ ] Discovery for Purchase History work complete w/r/t/ Recent Orders (read only)
[ ] Implement basic readout of Account details on new Category page (read only)
[ ] Testing and documentation (http://bit.ly/pwadocsguide)

**Comment by Starotitorov** [comment]
@ericerway Do we have mockups for the story?

**Comment by Starotitorov** [comment]
According to REST API docs we have an endpoint to fetch information about the current customer: `/V1/customers/me` The response contains such fields as email, firstname, lastname and array of addresses. I guess we can use this endpoint for the story.

**Comment by Starotitorov** [comment]
We need to finish this story https://github.com/magento-research/pwa-studio/issues/506 to fetch information about orders.

**Comment by ericerway** [comment]
> @ericerway Do we have mockups for the story? In this case it will be easier to understand what information we need to display.

Not for discovery, we discussed in grooming that we can use the basic LUMA layout/details for this particular story in VIEW ONLY mode. We'll address editing in the future. Thanks.

![image](https://user-images.githubusercontent.com/2686596/49018980-6a6de780-f152-11e8-8f6a-6a844933750f.png)

**Comment by ericerway** [comment]
For this discovery story/spike we should implement all of them and create stories for those that are not possible. Read only mode. We'll be pulling from the data within Magento 2 already for Veronica Costello in this case. Thanks.

**Comment by Starotitorov** [comment]
@ericerway, @soumya-ashok  Should I use styling from Luma theme or it is better to try to use Venia styling and some common components from venia-concept package?

**Comment by soumya-ashok** [comment]
@Starotitorov I think that the reference image is more for content. Styling should be based on Venia. I can create a mockup with Venia styling if that would be helpful.

**Comment by Starotitorov** [comment]
@soumya-ashok It will be great if you provide a mockup for the page. Right now I used Luma page and just changed Luma colors to our Venia theme colors.

![my-account](https://user-images.githubusercontent.com/11873143/49163801-f47aa380-f33e-11e8-97b1-4edbcba2b777.PNG)

![addresses](https://user-images.githubusercontent.com/11873143/49163810-f80e2a80-f33e-11e8-8afb-ea0a404e3d03.PNG)

**Comment by soumya-ashok** [comment]
@Starotitorov - What you have is good for a start, but it needs some adjustment based on the styles we're defining for Venia. I am currently reviewing the styles, and will send you feedback.

**Comment by Starotitorov** [comment]
@ericerway, @awilcoxa As I mentioned before, we will not be able to finish this task until this issue https://github.com/magento-research/pwa-studio/issues/506 is resolved. So, am I right that it will be better not to include static markup for "Recent Orders" section to this page and move the implementation of the static markup for this particular section and data fetching in separate story?

Also, I have some more questions:
1. Should I add my wishlist to the page as a part of this story?
2. Should I add subscribe form to the page as a part of this story?

@soumya-ashok I need mockups to finish implementation of the story.

**Comment by soumya-ashok** [comment]
@ericerway and I had a talk yesterday, and I won't be providing a mockup for this at this time, I am marking your screenshots up with feedback for changes @Starotitorov . Hope that clarifies things. Thanks!

**Comment by Starotitorov** [comment]
@soumya-ashok, ok, understood, thank you. When will you be able to provide the feedback?

**Comment by soumya-ashok** [comment]
@Starotitorov - Please use the suggested content and specs to make changes to your existing page and let me know if you have questions.

![venia-myacc](https://user-images.githubusercontent.com/25960021/49237991-1a4a8b80-f3c5-11e8-92fe-32abe47b8178.jpg)

**Comment by dmtrkad** [comment]
@ericerway . looks like  https://github.com/magento-research/pwa-studio/issues/573 is still blocked. Is that a priority to finish it or we could unlink it and make a progress on this PBI (https://github.com/magento-research/pwa-studio/issues/514)

**Comment by Starotitorov** [comment]
@soumya-ashok, I addressed your comment in this pull request https://github.com/magento-research/pwa-studio/pull/570, the pull request is waiting for a code review.

**Comment by sirugh** [comment]
Is this something we still want to do @soumya-ashok @awilcoxa? The mocks [here](https://magento.invisionapp.com/share/WQN5F7BYBPG#/screens/322904233) don't contain anything for these pages.

If this is outdated or part of some prior sprint that got tabled we can close this IMO.

**Comment by sirugh** [comment]
Per discussion yesterday it seems the discovery has been done and we know what we can get from the API. We are going to close the PR for now and if we decide to prioritize this work we can revisit it.
