### ISSUE TITLE
Add instrumentation to work with E2E WebDrivers

### ISSUE THREAD

**Issue by zetlen** [magento-research/pwa-studio#515]
## This issue is for the following packages:

[x] `venia-concept`
[ ] `pwa-buildpack`
[x] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[ ] Bug
[x] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

## Description

**As an end-to-end testing automation engineer, I want to be able to detect when the the React PWA has finished loading any particular state, using WebDriver remote APIs, so that I can write reliable tests for Venia multi-step scenarios.**

As an official Magento offering, PWA Studio must be covered by end-to-end tests as part of Magento's definition of quality. The core PWA Studio team and the Magento QA team are working on end-to-end testing for PWA Studio and Venia. Magento Functional Test Framework (MFTF) is their preferred solution, but they are open to other approaches. Nevertheless, all end-to-end test frameworks run in a "headless browser" with limited access to the JavaScript environment of the page under test.

## Acceptance Criteria

- QA Automation engineers must be able to run WebDriver methods which return true when the UI has loaded a particular scenario.
- Both routed scenarios (represented by a given URL) and non-routed scenarios (such as a drawer opening, or a form rendering an invalid state) must be detectable.
- WebDriver must be able to detect when a particular scenario is in the process of loading, as well as when it has fully loaded.
- Using timeouts (for a hardcoded number of seconds) can work sometimes, but it's a very brittle approach and would not satisfy this story's requirements:
   - If the server under test is slower than usual, a timeout may cause a false negative test result
   - If the scenario becomes much faster than it was when the test was implemented, a timeout may add unnecessary time to the test run

## Possible solutions:

- Test-only RootComponent functionality (eliminated at build by wrapping in a NODE_ENV test) which build a representative tree in global state
- Using the same approach as React Developer Tools
- Researching [Cypress](https://www.cypress.io/), which has a different runtime than WebDriver and may be an alternate solution for our core automation engineers

**Comment by dpatil-magento** [comment]
We have this feature working now.
