### ISSUE TITLE
Venia basic component specs

### ISSUE THREAD

**Issue by soumya-ashok** [magento-research/pwa-studio#517]
Description of visual specs for a set of basic Venia UI components

Color
Typography
Buttons
Form fields
Shopping cart icon
------------------------
![venia-component-specs.jpg](https://images.zenhubusercontent.com/5b89562fba905a6006740695/7bee369e-6e09-4bff-83d9-fd81242ed071)

**Comment by awilcoxa** [comment]
@soumya-ashok @jcalcaben any progress update here?
