### ISSUE TITLE
[Feature] Integrate bundlesize for current CI/CD process

### ISSUE THREAD

**Issue by vitalics** [magento-research/pwa-studio#521]
## This issue is for the following packages:

[x] `venia-concept`
[x] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[ ] Bug
[x] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description
[bundlesize](https://github.com/siddharthkp/bundlesize) - lib for analyze output bundle size
project requirement link for [definition of quality](https://github.com/magento-research/pwa-studio/wiki/Definition-of-Quality) 

## Expected result:
increase quality of product

**Comment by awilcoxa** [comment]
Closed as PR is merged
