### ISSUE TITLE
NPM run build error

### ISSUE THREAD

**Issue by ennostuurman** [magento-research/pwa-studio#522]
## This issue is for the following packages:

[x] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[x] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             | Magento 2.3 dev branch (latest) |
| Operating System + version  | Ubuntu Bionic |
| node.js version (`node -v`) | v.8.11.3 |
| npm version (`npm -v`)      | v6.4.1 |

## Description

"npm run build" errors at GraphQL query mismatch indicating that I either have
- an outdated Magento 2.3 develop (which is up-to-date, latest commit 2.3 dev branch 069d5cd ) - 
- or have an outdated Venia / PWA-studio repo (which is also up-to-date latest release 2.0. commit 2173bd1 ). 

Full CLI output:

```
/.../Projects/pwa-studio/packages/venia-concept/src/queries/getCategoryList.graphql
  11:21  error  Field "small_image" of type "ProductImage" must have a selection of subfields. Did you mean "small_image { ... }"?  graphql/template-strings

/.../Projects/pwa-studio/packages/venia-concept/src/queries/getProductDetail.graphql
  14:13  error  Field "description" of type "ComplexTextValue" must have a selection of subfields. Did you mean "description { ... }"?  graphql/template-strings

/.../Projects/pwa-studio/packages/venia-concept/src/RootComponents/Category/category.js
  19:21  error  Field "small_image" of type "ProductImage" must have a selection of subfields. Did you mean "small_image { ... }"?  graphql/template-strings

✖ 3 problems (3 errors, 0 warnings)

  These errors may indicate:
  -  an out-of-date Magento 2.3 codebase running at "https://www.m2dev23.local/"
  -  an out-of-date project codebase whose queries need updating

```

## Expected result:

"npm run build" should 'build' without errors

## Possible solutions:

Adding the appropriate query fields in the reported files (adding url to small_image and html to description ) solves the issue. See attached screenprint of successful build after suggested changes.

![magento-pwa-studio-npm-run-build-success](https://user-images.githubusercontent.com/1906257/48708660-73673200-ec03-11e8-84f4-e75dba06aa52.png)

p.s. Happy to make a PR for this.

**Comment by adrian-martinez-interactiv4** [comment]
When you install through composer, create your project from version: `2.3.0-beta32`, GraphQL schema seems to have breaking changes in `2.3-develop`

**Comment by ennostuurman** [comment]
@adrian-martinez-interactiv4 yes thank you this fixes the build issue. Would be nice to have this requirement in the setup docs under "Prerequisites"  as well , see https://github.com/magento-research/pwa-studio/blob/release/2.0/pwa-devdocs/src/venia-pwa-concept/setup/index.md so if you agree I will issue a PR for this.

**Comment by jcalcaben** [comment]
@ennostuurman I think it would be helpful to include that information on the setup page. Let me know when you create a PR for this change and I will review.

**Comment by ennostuurman** [comment]
@jcalcaben issued PR ^^
