### ISSUE TITLE
Component Display Names

### ISSUE THREAD

**Issue by supernova-at** [magento-research/pwa-studio#537]
## This issue is for the following packages:

[x] `venia-concept`
[ ] `pwa-buildpack`
[x] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[ ] Bug
[x] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

n/a

## Description

The [React Developer Tools extension](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en) is a great debugging resource for React applications.

Unfortunately our application does not make it easy to view our component hierarchy (notice all the `undefined`s):

<img width="617" alt="screen shot 2018-11-21 at 11 45 12 am" src="https://user-images.githubusercontent.com/13182778/48859554-f3b4a100-ed83-11e8-99ff-f108463a2e8a.png">

The React Developer Tools extension uses a component's `displayName` when showing the component tree above.

From the [React docs on displayName](https://reactjs.org/docs/react-component.html#displayname):

> The displayName string is used in debugging messages. Usually, you don’t need to set it explicitly because it’s inferred from the name of the function or class that defines the component. You might want to set it explicitly if you want to display a different name for debugging purposes or when you create a higher-order component

And in fact, that's exactly what happens in our [`Classify` higher order component](https://github.com/magento-research/pwa-studio/blob/release/2.0/packages/venia-concept/src/classify.js#L7):

```js
static displayName = `Classify(${WrappedComponent.displayName})`;
```

Because many `WrappedComponent`s don't have their `displayName` set, we see a lot of `undefined`s in the Dev Tools component tree.

## Expected result:

Components should show up in the React Developer Tools component tree with their `displayName` instead of `undefined`.

#### Class Components

```js
class Foo extends Component {
  static displayName = 'Foo';
  // ...The rest of the Foo component...
}
```

#### Stateless Functional Components

```js
const Bar = () => <span>Hello World</span>;
Bar.displayName = 'Bar';
```

### Posible Solution: A `displayName` Helper Function

The [React Docs](https://reactjs.org/docs/higher-order-components.html#convention-wrap-the-display-name-for-easy-debugging) suggest an alternate approach: create a helper function.

```js
function getDisplayName(WrappedComponent) {
  return WrappedComponent.displayName || WrappedComponent.name || 'Component';
}
```

We'd then just have to be sure to update `src/classify.js` to use this function:

```js
static displayName = `Classify(${getDisplayName(WrappedComponent)})`;
```

**Comment by vitalics** [comment]
@supernova-at duplicate #449

**Comment by supernova-at** [comment]
@vitalics oops! We'll sort them next grooming it looks like - thanks!
