### ISSUE TITLE
Venia homepage thumbnails are skewed

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#545]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[X] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

Thumbnails on Venia homepage are now skewed and do not fit the circle/crop originally part of the design. Likely part of recent image/compression work but need to double check. Thanks!

![image.png](https://images.zenhubusercontent.com/5a71f21a4b5806bc2bc51012/a059d113-b7aa-4f75-a96c-d54d30b1755c)

## Expected result:

Updated thumbnails with correct size/ratio.

**Comment by Jordaneisenburger** [comment]
It's not because of image compression:

**change this:**
```
.categoryTile-image-1yp {
    border-radius: 50%;
    height: auto;
    max-height: 100%;
    max-width: 100%;
    width: auto;
}
```
**To**
```
.categoryTile-image-1yp {
    border-radius: 50%;
    height: 100%;
    width: 100%;
}
```
