### ISSUE TITLE
GraphQL queries in .graphql files get stuck in Babel cache

### ISSUE THREAD

**Issue by zetlen** [magento-research/pwa-studio#552]
## This issue is for the following packages:

[x] `venia-concept`
[x] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[x] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

## Description

As observed by @jimbo in https://github.com/magento-research/pwa-studio/pull/550#discussion_r236769512, changes to `.graphql` files don't show up in builds, even after quitting and restarting the dev server or doing `npm run clean:dist`.

The problem lies with `babel-plugin-import-graphql` and is documented here: https://github.com/detrohutt/babel-plugin-import-graphql/blob/master/README.md#install

We only use this Babel plugin so we don't have to separately add `.graphql` file handling to Webpack and Jest, but this is a dealbreaker. We should remove this plugin and use the `graphql-tag/loader` Webpack plugin instead (and https://github.com/remind101/jest-transform-graphql for tests).

**Comment by jcodo** [comment]
👍

**Comment by ericerway** [comment]
Marking as closed w/r/t #568 #601 #533 - @zetlen please confirm if this is not fully addressed and we can reopen. Thanks!
