### ISSUE TITLE
Add variant information to cart item display

### ISSUE THREAD

**Issue by zetlen** [magento-research/pwa-studio#553]
## This issue is for the following packages:

[x] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[ ] Bug
[x] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

## Description

With the merging of #550 the storefront supports configurable products, but the cart item display doesn't reflect the chosen configuration:

![image](https://user-images.githubusercontent.com/1643758/49111379-8b6b3100-f255-11e8-98db-94640412d0a0.png)

As a shopper, I want to see my chosen configuration options in my cart, so I can keep track of what I'm purchasing.

@soumya-ashok has made a visual comp: https://magento.invisionapp.com/share/HNPBRBHP29D#/screens

**Comment by ericerway** [comment]
Assigned to @JStein92 - let's groom this in realtime based on your interested in taking it.

**Comment by ennostuurman** [comment]
hey @JStein92 I have created PR #582 for this . Understood from @ericerway that you'd been doing work for this already as well which I wasn't aware off.  I definitely would like to compare our results or maybe we could even combine both?

**Comment by ericerway** [comment]
I'd love for @JStein92 to finish this out but get a quick review from @ennostuurman who appeared to show interest at the same time in an effort to work on a quick starter story. We'll find more "good first issue" stories for everyone -- good problem to have. Thanks!

**Comment by JStein92** [comment]
Ok, just pushed a prettier pass to #558 (whoops) - looking forward to a review :)
