### ISSUE TITLE
Add Storybook back to Venia

### ISSUE THREAD

**Issue by pcvonz** [magento-research/pwa-studio#555]
## This issue is for the following packages:

[x] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[ ] Bug
[x] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

[Storybook](https://github.com/storybooks/storybook) is missing from Venia. There are a few hurdles to getting it up and running again: 

- Common `webpack` configuration should be added to a separate file that both `./storybook/webpack.config.js` and `./webpack.config.js` import.
- `FETCH_ROOT_COMPONENT` is imported via a [virtual-module](https://github.com/rmarscher/virtual-module-webpack-plugin). Storybook will crash when it encounters this import.

Would be fantastic to get input from @zetlen and @jimbo. Especially on the `FETCH_ROOT_COMPONENT` bit.

**Comment by zetlen** [comment]
@pcvonz Your first bullet point answers your second! The `FETCH_ROOT_COMPONENT` module is provided by the `MagentoRootComponentsPlugin`, so our shared Webpack config can just add that plugin and Storybook should resolve the virtual module just fine.

As we work, we want to migrate code from `webpack.config.js` into Buildpack plugins, just like we want to migrate Venia UI into Peregrine. Creating a webpack commons file would be a good first step, and I encourage it!
