### ISSUE TITLE
Entire app is being re-rendered on navigation|minicart toggle.

### ISSUE THREAD

**Issue by boguskrzysiek** [magento-research/pwa-studio#560]
## This issue is for the following packages:

[x] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[x] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

## Description

Toggling minicart or navigation causes re-render of the entire application. 

## Expected result:

Toggling minicart|navigation should not cause entire app being re-rendered.

**Comment by boguskrzysiek** [comment]
Actually the entire app is being re-rendered on nav | minicart toggle.

**Comment by awilcoxa** [comment]
Unable to replicate, closing issue.
