### ISSUE TITLE
Cannot find module 'envalid'

### ISSUE THREAD

**Issue by vphat28** [magento-research/pwa-studio#561]
Hi
I followed this guide https://magento-research.github.io/pwa-studio/venia-pwa-concept/setup/ to install Venia but when I was trying to run "npm run build" command I get this error in the output

@magento/venia-concept: Cannot find module 'envalid'

## This issue is for the following packages:

[ x] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[x ] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             2.30
| Operating System + version  | Ubuntu 16.04  |
| node.js version (`node -v`) | v10.14.0 |
| npm version (`npm -v`)      | v6.4.1|

## Description
I followed this guide https://magento-research.github.io/pwa-studio/venia-pwa-concept/setup/ to install Venia but when I was trying to run "npm run build" command I get this error in the output
@magento/venia-concept: Cannot find module 'envalid'
## Expected result:
The server should be up and running and there should be an url of server output in command line

**Comment by magefan** [comment]
@vphat28 , please try to run
`npm install envalid`
before 
`npm run build`

**Comment by AndreyChorniy** [comment]
Thank you @magefan
