### ISSUE TITLE
State management refactor for navigation drawer

### ISSUE THREAD

**Issue by Starotitorov** [magento-research/pwa-studio#563]
## This issue is for the following packages:

[x] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[ ] Bug
[ ] Feature suggestion
[ ] Documentation issue
[x] Tech Debt

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

Right now we do not reset field values for sign in and sign up forms when user closes the navigation drawer. Also, we do not reset state of our navigation drawer.

It will be easier to manage local states in case we unmount and mount this forms in the drawer instead of hiding them using CSS `display` property. In this case we need to use react-transition-group for animating components when a React component enters or leaves the DOM.

Our navigation drawer has a lot of separate states, to manage them we use plenty of boolean flags like         isSignedIn, isCreateAccountOpen, isSignInOpen, isForgotPasswordOpen.

## Expected result:

Navigation drawer state is reseted when use closes the drawer. Form fields should be reseted too.

## Possible solutions:

Add react-transition-group for animating when a component enters or leaves the DOM.
Implement some kind of state machine pattern to handle drawer states.

**Comment by ericerway** [comment]
Updated with more descriptive title for issue. Thanks!

**Comment by awilcoxa** [comment]
closing during backlog cleanup, if issues still exists please reopen for future prioritization.
