### ISSUE TITLE
Error in Swatches prevents Installation of Sample Data

### ISSUE THREAD

**Issue by dwirt** [magento-research/pwa-studio#569]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[X] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             | 2.3.0-beta32 |
| Operating System + version  | ubuntu 14.04 |
| node.js version (`node -v`) | 8.9.4 |
| npm version (`npm -v`)      | 5.6.0 |

## Description

Follow the exact instructions on https://magento-research.github.io/pwa-studio/venia-pwa-concept/setup/

before step 4, try to install the sample data as described in:
https://magento-research.github.io/pwa-studio/venia-pwa-concept/install-sample-data/

on step 3 when running the setup:upgrade script it finishes with the following error:
`
Module 'Magento_ConfigurableSampleDataVenia':
 in /var/www/magento2.3.0/vendor/magento/module-configurable-sample-data-venia/Setup/Swatches.php on line 116
`

## Expected result:

sample data installs without problems

## Possible solutions:

The error line contains this code, which would indeed not work if the array doesn't have the given value.
```
else if ($this->colorMap[$optionValue]) {
```
so it should be 
```
else if ( array_key_exists($optionValue, $this->colorMap) ) {
```
unfortunately this just reveals another issue:

`
Module 'Magento_ConfigurableSampleDataVenia':
Notice: Undefined index: White in /var/www/magento2.3.0/vendor/magento/module-configurable-sample-data-venia/Setup/Swatches.php on line 119
`
the `$colorMap` array doesn't have that value as you can see in line 18:

```
    protected $colorMap = [
        'Peach'     => '#fee1d2', // PE
        'Khaki'     => '#f9efe5', // KH
        'Lilac'     => '#dcd5e1', // LL
        'Rain'      => '#d4e3ec', // RN
        'Mint'      => '#d8f0d8', // MT
        'Lily'      => '#f0f0c0', // LY
        'Latte'     => '#C0a890', // LA
        'Gold'      => '#D4AF37', // GO
        'Silver'    => '#cdd0d7', // SI
        'Cocoa'     => '#3E1803'  // CO
    ];
```
it doesn't matter if you add white to the colorMap or replace white with peach, i ended up with the following error:

`Module 'Magento_ConfigurableSampleDataVenia':
Error in data structure: entity values are mixed`

(the output is the same even when running with `-vvv`)

i added a `var_dump($optionSwatch)` to the `getOptionSwatchVisual` function, but i don't see a problem here:

```
Module 'Magento_ConfigurableSampleDataVenia':
/var/www/magento2.3.0/vendor/magento/module-configurable-sample-data-venia/Setup/Swatches.php:122:
array(1) {
  'value' =>
  array(11) {
    [5] =>
    string(7) "#fee1d2"
    [429] =>
    string(7) "#fee1d2"
    [430] =>
    string(7) "#fee1d2"
    [6] =>
    string(7) "#cdd0d7"
    [431] =>
    string(7) "#fee1d2"
    [432] =>
    string(7) "#fee1d2"
    [433] =>
    string(7) "#fee1d2"
    [434] =>
    string(7) "#fee1d2"
    [435] =>
    string(7) "#fee1d2"
    [436] =>
    string(7) "#fee1d2"
    [437] =>
    string(7) "#3E1803"
  }
}
/var/www/magento2.3.0/vendor/magento/module-configurable-sample-data-venia/Setup/Swatches.php:122:
array(1) {
  'value' =>
  array(11) {
    [5] =>
    string(7) "#fee1d2"
    [429] =>
    string(7) "#fee1d2"
    [430] =>
    string(7) "#fee1d2"
    [6] =>
    string(7) "#cdd0d7"
    [431] =>
    string(7) "#fee1d2"
    [432] =>
    string(7) "#fee1d2"
    [433] =>
    string(7) "#fee1d2"
    [434] =>
    string(7) "#fee1d2"
    [435] =>
    string(7) "#fee1d2"
    [436] =>
    string(7) "#fee1d2"
    [437] =>
    string(7) "#3E1803"
  }
}
Error in data structure: entity values are mixed
```

**Comment by ennostuurman** [comment]
hey @dwirt just a quick reply to get you started

- the advised Magento instance is the latest release of M2.3 (not the beta32) . Docs will be updated, see PR #577
- you read the sample docs so probably an unnecessary question but just to be sure: are you running PHP 7.1 ? As there are issues with PHP 7.2 (not sure if related to yours tho) , see https://magento-research.github.io/pwa-studio/venia-pwa-concept/install-sample-data/
- to get you started with PWA Studio without Venia sample data. You don't have to run PWA Studio with a local Magento as backend as you probably know already (using the distributed .env in venia-concept will proxy to external Magento 2.3 instance as backend) .  But if you want to test out how tie PWA Studio to a local Magento instance you could also add sample data with Magento fixtures *)  instead of Venia sample data (although that will cause data fetch errors on PDP because of hard coded configurable options in the Venia theme).

*) Magento fixtures: https://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-perf-data.html

**Comment by ennostuurman** [comment]
hello @dwirt did you manage to get PWA Studio running based upon my last weeks advise?

**Comment by dwirt** [comment]
I got it working on a different machine, so the problem was probably with the environment

thanks!

**Comment by ennostuurman** [comment]
hi @dwirt glad you managed to get PWA Studio up and running. Thank you for the confirmation and closing the issue!

**Comment by riddhishbhayani** [comment]
Hello @ennostuurman  I am facing the same issue. tried with multiple setups but still cant figure out the root cause. I am using WAMP in Windows is that the issue ?
