### ISSUE TITLE
Fix up checkout form right shift

### ISSUE THREAD

**Issue by AlexeyKaryka** [magento-research/pwa-studio#571]
## This issue is for the following packages:

[ X ] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[ X ] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

After latest updates checkout form has become a little bit shifted to the right.It affected close button and address form
![image](https://user-images.githubusercontent.com/25349273/49292833-67128d00-f4bf-11e8-88f8-e5b1e8ca3b87.png)

## Expected result:

Drawer's close button shouldn't be cutted and should has margin from the container. Address form should has same margins from left and right sides

**Comment by vitalics** [comment]
duplicate #565
