### ISSUE TITLE
Implement recent orders section on account details page

### ISSUE THREAD

**Issue by Starotitorov** [magento-research/pwa-studio#573]
## This issue is for the following packages:

[x] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[ ] Bug
[x] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

Implement recent orders section on account details page https://github.com/magento-research/pwa-studio/issues/514. We need to finish the implementation of https://github.com/magento-research/pwa-studio/issues/506.

**Comment by Starotitorov** [comment]
It is required to implement required endpoints https://github.com/magento-research/pwa-studio/issues/506 to start the implementation

**Comment by awilcoxa** [comment]
closing as dupe of #294
