### ISSUE TITLE
iOS Icon & Loading/Splash Screen Support

### ISSUE THREAD

**Issue by gil--** [magento-research/pwa-studio#576]
## This issue is for the following packages:

[X ] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[X ] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             | 2.3.0 |
| Operating System + version  | iOS 12 |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

iOS Safari does not currently support the WebAppManifest which causes the app icons to not show and initial loading experience of the app to show as a white blank screen:

![img_9148](https://user-images.githubusercontent.com/3484527/49299955-05d2c580-f48f-11e8-92be-234c0e4e6031.PNG)

## Expected result:

App icons should show on homescreen like Android and loading screen show be presented with a [splash screen](https://developers.google.com/web/fundamentals/web-app-manifest/#splash-screen)

## Possible solutions:

We will need to utilize additional header tags until webappmanifest support is available on iOS:

```html
<link rel="apple-touch-icon" href="touch-icon-iphone.png">
--
<link rel="apple-touch-icon" sizes="152x152" href="touch-icon-ipad.png">
<link rel="apple-touch-icon" sizes="180x180" href="touch-icon-iphone-retina.png">
<link rel="apple-touch-icon" sizes="167x167" href="touch-icon-ipad-retina.png">
```

And launch screen:

```html
<link rel="apple-touch-startup-image" href="/launch.png">
```

See: https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

**Comment by ericerway** [comment]
Thanks @gil-- this is great and would be a great addition to what we currently have for Venia. Let's make sure to include @rowan-m on the review and use a simulator for testing vs. Chrome DevTools..
