### ISSUE TITLE
Overview content for pwa-studio monorepo wiki

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#58]
## This issue is for the following packages:

[ ] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[X] `pwa-devdocs`

## This issue is a:

[ ] Bug
[X] Feature suggestion
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

Creation and review of Overview and Approach level content for pwa-studio content with migration to monorepo in Github wiki format. Goal is for any contributor to review this in Github and know exactly how to get started, the purpose and status of the project and other relevant links. Content will likely be a light version of what we have in pwa-docs currently but needs to be shown in Github.

Example can be found with graphql-ce: https://github.com/magento/graphql-ce/wiki

**Comment by jcalcaben** [comment]
@ericerway 
Please review: https://github.com/magento-research/pwa-studio/wiki

**Comment by ericerway** [comment]
@jcalcaben 
Looks great. We'll add roadmap shortly and "Approach" when ready. Thanks!
