### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by senthil134** [magento-research/pwa-studio#584]
We are trying to build the project by using "**npm run build**" command. We are getting following error 

from root folder :
![image](https://user-images.githubusercontent.com/8088538/49380152-eeb60100-f736-11e8-8180-ec9a0e1b90ca.png)

from pwa-studio-release-2.0\pwa-studio-release-2.0\packages\venia-concept folder:

![screenshot](https://user-images.githubusercontent.com/8088538/49431570-d942e480-f7d3-11e8-8750-06efd66fcf58.png)

**Comment by Jordaneisenburger** [comment]
I've also ran into this exact issue, although i forgot how i've fixed it. I will try to reproduce and fix again.

**Comment by 472756921** [comment]
@Jordaneisenburger Do you have a solution?

**Comment by dmtrkad** [comment]
@sharkySharks , Could you please have a look on it as well in order to put it on work to Devops queque ?

**Comment by senthil134** [comment]
> For now i can't reproduce it anymore, but a word of advice is to not run it on a windows machine for now. Try linux based systems or what i prefer macOS. Also make sure you run the right NodeJs versions.

Thank you for ur comment. 

We are getting same error in macOS. Please let us know your config details.(NodeJs version, npm)

**Comment by Jordaneisenburger** [comment]
Valet+ 1.0.21 (make sure you don't use a higher version because it will break on certificate)
NodeJS v8.12.0
Npm 6.4.1

Hope this helps

**Comment by senthil134** [comment]
> Valet+ 1.0.21 (make sure you don't use a higher version because it will break on certificate)
> NodeJS v8.12.0
> Npm 6.4.1
> 
> Hope this helps

Thank you @Jordaneisenburger It's working fine in macOS
