### ISSUE TITLE
Add pre-push git hook for quicker dev feedback and reduce CI failures

### ISSUE THREAD

**Issue by sharkySharks** [magento-research/pwa-studio#585]
Add `pre-push` hook to repo to reduce common issues that fail in CI when submitting pull requests, notably: `npm run prettier`, `npm run lint`, and `npm test`.

## This issue is for the following packages:

[ ] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`
[X]  repo level

## This issue is a:

[ ] Bug
[X] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

Developers should get quick feedback before pushing changes to the repo for a pull request. Quick feedback should be on testing, linting, and other small tasks that also run in the CI environment.

## Expected result:

When a developer tries to push code to the repo they have a series of quick scripts run to validate their changes.

## Possible solutions:

add `pre-push` git hook and initialize it such that it does not need to be configured locally to work, but is already configured in the repo upon cloning/pulling/etc.

**Comment by Starotitorov** [comment]
https://github.com/magento-research/pwa-studio/issues/605

**Comment by sharkySharks** [comment]
Already being covered in PR #610

**Comment by sharkySharks** [comment]
Closing as duplicate
