### ISSUE TITLE
Need deployment environment with shared credential manager and AWS access control group for team

### ISSUE THREAD

**Issue by sharkySharks** [magento-research/pwa-studio#587]
Need to have a deployment environment that integrates with CI outside of individual credentials held by @zetlen . Also should have credentials in a shareable credential manager for those who need/are given access.

_Update:_
With IAM roles you can create different access groups for individual logins, this seems to be the best way forward since the credential manager would be mostly for CI access. Can also use AWS secrets manager to hold other secrets, like access tokens, etc.

## This issue is for the following packages:

[ ] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`
[ ] ci deployments

## This issue is a:

[ ] Bug
[ ] Feature suggestion
[ ] Documentation issue
[X] Other - CI improvements

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

Should have an environment for deployments for testing on pull requests that has shared credentials held in a password manager.

## Expected result:

CI should work the same as expected but be deployed to a new environment where the credentials are shared via password manager.

## Possible solutions:

Need to sync with internal devops team to discuss deployment environments, but the credential manager could be stored in passwordsafe, or another manager where the internal team can troubleshoot when necessary.

**Comment by zetlen** [comment]
@sharkySharks What kind of shared credential manager do you recommend? In our Cloud instances, we have shareable and inheritable environment variables, and that seems like a good start. But CircleCI also needs access to these environment variables.

One thing we could do is make our own cloud instance handle the push webhook, and use the CircleCI to dispatch new CI builds. This requires a lot of new code, and may not reach feature parity with Circle's nice and neat GitHub hook, but it would achieve full centralization of credentials. How important is it? I defer to your expertise here.

**Comment by sharkySharks** [comment]
credential store set up in AWS, easy to add credentials to for team reference. [AWS Systems Manager](https://console.aws.amazon.com/systems-manager/home?region=us-east-1)

**Comment by sharkySharks** [comment]
`PWADevelopers`  IAM group setup in AWS account with full access to all services being used in pipelines, plus Lambda for Dev to use for testing. 

![Screen Shot 2019-04-04 at 4 10 02 PM](https://user-images.githubusercontent.com/7784948/55588741-34d69d80-56f4-11e9-99f2-0c3374046f73.png)

Chris Burton will need to sign off on adding individuals to the AWS account and the IAM group policies for the group.

cc: @cherdman

**Comment by sharkySharks** [comment]
using the Systems Manager in #1087
