### ISSUE TITLE
Reset navigation drawer state when user closes it

### ISSUE THREAD

**Issue by Starotitorov** [magento-research/pwa-studio#603]
## This issue is for the following packages:

- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [x] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

Right now when user closes navigation drawer we do not reset it state, so when user opens drawer again he can see some forms instead of main menu.

@ericerway, @awilcoxa, @soumya-ashok, please, approve that it is a bug.

## Expected result:

When user interacts with the drawer and close it, we need to render main menu when user opens the drawer again.

## Possible solutions:

https://github.com/magento-research/pwa-studio/issues/563

**Comment by soumya-ashok** [comment]
@Starotitorov There are situations in which resetting the drawer to show the main menu would be applicable, but I am not sure that it would apply to every single use case. Will discuss with @jimbo and send an update.

**Comment by jimbo** [comment]
This is working as intended, in general.
