### ISSUE TITLE
Add git pre-push hook

### ISSUE THREAD

**Issue by Starotitorov** [magento-research/pwa-studio#605]
## This issue is for the following packages:

- [ ] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [ ] Bug
- [x] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

Add husky https://github.com/typicode/husky and implement pre-push hook to run prettier, eslint and test automatically before pushing changes. Right now we have to run this scripts manually.

@zetlen, @ericerway, please, approve.

**Comment by ericerway** [comment]
Defer to @zetlen on issue priority. Unsure the business value over other priorities. Thanks.

**Comment by Starotitorov** [comment]
I have implemented this today and created a pull request https://github.com/magento-research/pwa-studio/pull/610.

**Comment by sharkySharks** [comment]
This has been implemented.
