### ISSUE TITLE
[Bug]: Carousel without indicator and styles and logic

### ISSUE THREAD

**Issue by vitalics** [magento-research/pwa-studio#606]
## This issue is for the following packages:

- [X] `venia-concept`
- [ ] `pwa-buildpack`
- [X] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [X] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description
no indicator for carousel which provided on `Product page`:
![image](https://user-images.githubusercontent.com/8816260/49588311-738f5d80-f977-11e8-9aa5-b5a8c78cecc7.png)

## Expected result:
indicator must be show current image prosition from queue
also indicator must be shown under product
![image](https://user-images.githubusercontent.com/8816260/49588376-991c6700-f977-11e8-9ac2-31c2278eb090.png)

## Possible solutions:
- for indicator must be shown under product must provide images with free spaces below. It helps for better displaying

## Additional information:
- has dependency with stories: #471 and #162 

## Actions:
- approve from FE architect perspective (@zetlen )
- approve from PO perspective (@ericerway or @awilcoxa )

**Comment by awilcoxa** [comment]
closing as PR is merged
