### ISSUE TITLE
[Bug]: Product image carousel does not update to reflect variant config

### ISSUE THREAD

**Issue by vitalics** [magento-research/pwa-studio#607]
## This issue is for the following packages:

- [X] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [X] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description
when the user chooses a color for `configurable product` and click `add to cart` button, the user sees a product in cart with the correct image:
![image](https://user-images.githubusercontent.com/8816260/49588862-e9e08f80-f978-11e8-8be4-74fa1e3feb41.png)
at the same time, the product image was not changed:  
![image](https://user-images.githubusercontent.com/8816260/49588931-1bf1f180-f979-11e8-9b2a-570929e90532.png)
As a user, I was confused 😖 

## Expected result:
Image for `configurable product` must changes when the user chooses a color type for this product.

## Possible solutions:
- research possibility on back-end side to implement this solution
- research about graphql schema, and if the previous point is possible -> implement new schema

## Actions
- approve from FE architect perspective (@zetlen )
- approve from PO perspective (@ericerway or @awilcoxa )

**Comment by Starotitorov** [comment]
@vitalics, @ericerway Right now for each product we receive an array of `media_gallery_entries` with images for different views of the product. Also, for configurable products we receive an array of `variants`. Each `product` inside `variant` object contains `media_gallery_entries` array, but each media_gallery_entry contains only one image with label "Main" now. In general, we can implement this, but we need to configure data in Magento CMS first.

@ericerway, @awilcoxa please, approve and prioritize this.

**Comment by dpatil-magento** [comment]
Verified this on https://veniapwa.com and it is fixed. Hence closing this one.
