### ISSUE TITLE
No way to close "checkout" panel in minicart

### ISSUE THREAD

**Issue by JStein92** [magento-research/pwa-studio#608]
## This issue is for the following packages:

- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [x] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

## Description

When a user selects "checkout", they are locked into the checkout process and can not close out of the panel.

![image](https://user-images.githubusercontent.com/27716099/49590613-2c767d80-f921-11e8-917c-c887fc1f38a4.png)

## Expected result:

A user should be able to back out of the checkout/selection process, especially since it covers the bottom half of the minicart.

@soumya-ashok @jimbo Please confirm if this is a bug, or an intended feature. Feel free to close if this is not a bug. :)

**Comment by tjwiebell** [comment]
Issue resolved by delivery of #799.
