### ISSUE TITLE
Feedback on page: /venia-pwa-concept/component/filter/

### ISSUE THREAD

**Issue by hervebackstage** [magento-research/pwa-studio#614]
## This issue is for the following packages:

- [x] `venia-concept`

## This issue is a:

- [x] Bug
- [x] Documentation issue

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |2.3.0 |
| Operating System + version  | Ubuntu 19.04.1 LTS |
| node.js version (`node -v`) | v8.12.0 |
| npm version (`npm -v`)      | 6.4.1 |

## Description

following the PWA setup instruction (see: https://magento-research.github.io/pwa-studio/venia-pwa-concept/setup/), I have now the envrionment working and can place successfully some orders with it.

- However, I have noticed the category listing is not working as expected: particularly, I see the buttons 'filter', 'sort' and 'show more' do not trigger any action (in fact, the code does not show any onclick action hooked.

## Expected result:

As per the PWA documentation (see: https://magento-research.github.io/pwa-studio/venia-pwa-concept/component/filter/), I'd expect to see a dropdown appearing when clicking on the filter button and instead I have an idle button doing nothing.

## Possible solutions:

Are you able to confirm the documentation is showing how the filter widget should look like but that the PWA has not implemented this filter widget yet?

**Comment by ericerway** [comment]
Thanks for reporting! Good timing, sorting and filtering is coming soon (work is partial) as we review the new GraphQL work after 2.3.0 but we just merged a fix that removes these for now in #531 until they return. Closing for but happy to reopen if you still have questions. Thanks again.
