### ISSUE TITLE
Component status for PWA Studio (Venia) *WIP*

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#618]
## This issue is for the following packages:

- [ ] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [ ] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

**Comment by awilcoxa** [comment]
closing during backlog cleanup, if issues still exists please reopen for future prioritization.
