### ISSUE TITLE
Kebab button does not work in certain browsers (non-chromium?)

### ISSUE THREAD

**Issue by gil--** [magento-research/pwa-studio#625]
Minicart Kebab button currently uses `onFocus` which seems to not work in Firefox and Safari (iOS & Desktop).

## This issue is for the following packages:

- [X] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [X] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             | 2.3.x |
| Operating System + version  | iOS & OSX |
| node.js version (`node -v`) | n/a |
| npm version (`npm -v`)      | n/a |

## Description

When clicking the kebab button in the minicart, it does not open the dropdown menu when using iOS Safari, Desktop Safari, or Firefox. It currently uses `onFocus` to fire the event. 

Changing to `onClick` resolve the issue for all tested browsers. However, this introduces a new issue in how to address closing the dropdown menu since the current logic uses onBlur to close the menu but we're no longer using onFocus. 

the kebab button is the 3 circles vertically stacked:

<img width="129" alt="screen shot 2018-12-07 at 4 42 04 pm" src="https://user-images.githubusercontent.com/3484527/49674192-1232c180-fa3f-11e8-86bc-d348e5987049.png">

## Expected result:

Clicking the kebab button in any browser makes the dropdown open. Clicking outside the kebab or changing focus would close the dropdown menu.

## Possible solutions:

Change to onClick to open and onMouseDown or clicking outside of kebab, dropdown closes? Could also look into using something like React Reach Menu-Button which handles similar functionality with accessibility baked in.

**Comment by gil--** [comment]
As an aside, when debugging this, I found it odd that the kebab button was located within the minicart component folder. It seems like it would be a useful global component in the future such as for wishlist, etc. Might be ideal to move it to a more global scope than within minicart.

**Comment by gil--** [comment]
Also, some of the issues I'm seeing are related to cross-browser issues. Not sure if the Magento team does cross-browser internal testing but it may be interesting to incorporate [cypress]https://www.cypress.io/) test cases especially whenever they added Firefox support as that would provided automated browser testing in Chrome & Firefox and ensure these sorts of bugs get caught via CI than human. 

I know we currently use Jest + Enzyme but if there's interest, I'd be up to explore the creation of test cases for at least core UI elements using Cypress.

**Comment by ericerway** [comment]
Thanks for the report! Marking this for grooming to address the kebab and tagging @sharkySharks to incorporate in a separate spike/issue on browser testing with automation.

**Comment by awilcoxa** [comment]
closing as PR is merged
