### ISSUE TITLE
Clarification request on layout loader, communication and app shell

### ISSUE THREAD

**Issue by leon0v** [magento-research/pwa-studio#63]
## This issue is for the following packages:

[ ] `venia-concept`
[ X ] `pwa-buildpack`
[ ] `peregrine`
[ X ] `pwa-module`

## This issue is a:

[ ] Bug
[ ] Feature suggestion
[ X ] Other: Clarification request

## Description

I'd like some clarification on certain topics.

1. I watched the [video](https://www.youtube.com/watch?v=8vKkQPzJCnk) and read the [docs](https://github.com/magento-research/pwa-studio/blob/master/packages/pwa-buildpack/docs/magento-layout-loader.md) about the Magento Layout Loader. I understand that this API is in an early development stage and should be considered unstable. The docs say:

> It gives Magento modules/extensions the ability to inject or remove content blocks in a layout without modifying theme source files.

But I don't really understand for what purpose this functionality will be used.

I guess what i'm asking is how are you planning to implement the communication between the PWA front-end and the Magento back-end for modules and extensions. At first I thought this communication would go through the GraphQL API, but I can't really see the purpose of the magento layout loader in this.

2. Why have you chosen to serve the app shell from the Magento back-end and not from the front-end? If you would generate the app shell with webpack, you could use webpack plugins. For example, you could use the [HtmlWebpackPlugin](https://webpack.js.org/plugins/html-webpack-plugin/) for generating <script> tags:

> This is especially useful for webpack bundles that include a hash in the filename which changes every compilation.

I get that it is up to the users to implement such aspects the way they want, but maybe i don't see certain reasons why you chose this approach.

## Expected result:

Possessing more knowledge.

**Comment by DrewML** [comment]
> But I don't really understand for what purpose this functionality will be used.

Marketplace extensions modifying UI, similar to how it's done with layout XML today. You as a developer will have the option of importing an extension and consuming it in your theme. However, extension authors would like to maintain the ability to automatically inject their extensions into the UI without requiring a developer do that.

> Why have you chosen to serve the app shell from the Magento back-end and not from the front-end? If you would generate the app shell with webpack, you could use webpack plugins. For example, you could use the HtmlWebpackPlugin for generating <script> tags

We need to server render important metadata about the page in the `<head />` of the document, and we want to leave the possibility open to full SSR in the future. This could also be done with a Node.js server, but then we're still not just serving a static document generated by webpack.
