### ISSUE TITLE
[Bug]: SignIn header is not change after login

### ISSUE THREAD

**Issue by vitalics** [magento-research/pwa-studio#631]
## This issue is for the following packages:

- [X] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [X] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description
When login header is `SIGN IN`:
![image](https://user-images.githubusercontent.com/8816260/49738403-638dbb80-fca0-11e8-83c9-3d028e43890c.png)
And after submitting this form header is not change. Expected `MAIN MENU`:
![image](https://user-images.githubusercontent.com/8816260/49738478-8ae48880-fca0-11e8-9371-75c8e567970d.png)

## Expected result:
After submitting the form. the header for the left menu displayed `MAIN MENU` as provided on the screenshot:
![image](https://user-images.githubusercontent.com/8816260/49738570-b9626380-fca0-11e8-81d2-2c9e10582d9f.png)

## Possible solutions:
for `navHeader_NavHeader` component not change `isSignInOpen` state.
After submit set `isSignInOpen` variable to `false`.
![image](https://user-images.githubusercontent.com/8816260/49739054-fd099d00-fca1-11e8-8fa6-16a7ccffad9a.png)

**Comment by Starotitorov** [comment]
The problem with the logic we use to determine the title of the navigation panel:

```
const title = isCreateAccountOpen
    ? 'Create Account'
    : isSignInOpen
    ? 'Sign In'
    : 'Main Menu';
```

At the same time we make two checks to understand if we need to render Sing In and Create Account forms or not:

`const isOpen = !isSignedIn && isCreateAccountOpen;`

`const isOpen = !isSignedIn && isSignInOpen;`

In general, I believe it is better to refactor our navigation drawer, I created an issue https://github.com/magento-research/pwa-studio/issues/563

**Comment by awilcoxa** [comment]
@supernova-at to confirm that the referenced commit (7d4bae2) actually addresses this issue. If true, we'll close this ticket as resolved.

**Comment by supernova-at** [comment]
Confirmed that this is fixed on https://magento-venia.now.sh/ as of right now:

![jan-09-2019 11-39-44](https://user-images.githubusercontent.com/13182778/50917545-6563af80-1403-11e9-94c3-cf76ad70f172.gif)

Agreed that this logic could be made cleaner, but this bug is resolved.
