### ISSUE TITLE
[Bug]: Error message for configurable product

### ISSUE THREAD

**Issue by vitalics** [magento-research/pwa-studio#640]
## This issue is for the following packages:

- [X] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [X] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description
No any error messages displayed if user try to add configurable product in a cart with messing configuration. Flow:
1) navigate to: https://magento-venia.now.sh/helena-cardigan.html
2) choose color configuration only
3) click `add to cart` button
4) cart is empty:
![image](https://user-images.githubusercontent.com/8816260/49794294-4a404a00-fd48-11e8-9d8e-e3ed8527db61.png)
and request was failed
- general info: 
![image](https://user-images.githubusercontent.com/8816260/49794423-91c6d600-fd48-11e8-9e1f-b24e91a1f4e1.png)
- payload: 
![image](https://user-images.githubusercontent.com/8816260/49794460-ac00b400-fd48-11e8-9b66-9a245cc4bf66.png)
- response: 
![image](https://user-images.githubusercontent.com/8816260/49794479-bcb12a00-fd48-11e8-814d-a11c032da8c6.png)

## Expected result:
on the step 3 show error message for missing configuration 

## Possible solutions:
- Implement front-end validation for configurable product
- Implement back-end validation for configurable product (unsafe to show stack-trace in response, hacker can use this information and use them)

**Comment by awilcoxa** [comment]
discussed in grooming, there is a larger issue here for graceful fallback or error state for when similar conditions are met.  @zetlen for ticket to represent this larger issue and we will create dependency here.

**Comment by zetlen** [comment]
Now that #871 is almost landed, I think we should come back to this one. This bug is still pretty major; the change in #871 will display an "unexpected error" instead of absolutely nothing when you try to add an un-configured product to the cart, but that's still a pretty bad experience. It needs to say "You must configure the product first" in context. I recommend this for 2.0, because it's a pretty small fix; @awilcoxa @dpatil-magento @sharkySharks @magento-research/core-pwa-devs don't you think?

**Comment by supernova-at** [comment]
To update this discussion, #871 has now landed.

**Comment by awilcoxa** [comment]
While #871 landed it only covers a general error case, in order to properly resolve this  bug there should be a new PR opened against this issue to address specific error state/message.

**Comment by dani97** [comment]
Can we do a front end validation here? We can do validation before add to cart button is clicked.
