### ISSUE TITLE
Update pwa-studio to fix security vulnerabilities 12.6.18

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#656]
## This issue is for the following packages:

- [X] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [X] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

There are several known security vulnerabilities that need to be addressed with pwa-sudio per Github with "High Severity".

minimatch
opened 6 days ago by GitHub • pwa-devdocs/package-lock.json
high severity
lodash
opened 6 days ago by GitHub • pwa-devdocs/package-lock.json
high severity

https://github.com/magento-research/pwa-studio/network/alerts

## Expected result:

Review, upgrade and testing updates to minimatch, lodash and string dependencies. Instructions available on Github.

**Comment by AlexeyKaryka** [comment]
Unfortunately link https://github.com/magento-research/pwa-studio/network/alerts leads to 404 page

**Comment by ericerway** [comment]
Appears to be owner access only in GH and link is not 100% helpful. We just need to upgrade minimatch, lodash and string which are in pwa-devdocs -- vulnerabilities were found in the package-lock.json file. Thanks!

**Comment by AlexeyKaryka** [comment]
As far as I've found out there are no opportunities to update string, lodash and minimatch packages. Each of them are used in pwa-devdocs only as dependencies of other packages and a few of these packages require old minor version. Apart from that string package doesn't have any patches yet, so nothing to update; Lodash 4.17.5 which is recommended to update to isn't placed on npm yet, the lattest version is 4.17.11 which is already placed as required dependency for most of packages which require it. As for minimatch, several packages require an old version of minimatch and it will be possible to update minimatch when those packages update required version.
