### ISSUE TITLE
"Remove Item" in Minicart usability issue

### ISSUE THREAD

**Issue by codeAdrian** [magento-research/pwa-studio#661]
## This issue is for the following packages:

- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [x] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             | 2.3 |
| Operating System + version  | macOS 10.13.6 |
| node.js version (`node -v`) | v8.11.3 |
| npm version (`npm -v`)      | 5.6.0 |

## Description

There is an usability issue when user clicks on "Remove Item" in minicart. Steps to reproduce:

1. User adds 2 or more different items in cart. For example:
![screen shot 2018-12-13 at 1 49 39 pm](https://user-images.githubusercontent.com/11479290/49940202-311dd180-fedf-11e8-8622-231a8a0fe439.png)
2. For the last item in the list, user clicks "Remove item" from the actions list
3. The request is being sent in background, this takes some time.
4. While that is happening in the background, user can still interact with that minicart item, so user clicks on the "Remove item" several more times for the same item.
5. Now all products are removed from the cart, even though user kept clicking "Remove item" for the last item in the list.

## Expected result:

User shouldn't be able to interact with cart items (or the particular items which is being removed) while the request is processing.

## Possible solutions:

Overlay a spinner on top of the minicart items to visually indicate that the request is being processed and disallow users to interact with the minicart items. @soumya-ashok , feel free to suggest an alternative solution.

**Comment by DmitryShmaliuk** [comment]
Please, assigned to me.
