### ISSUE TITLE
[Bug]: Cannot Edit cart item

### ISSUE THREAD

**Issue by vitalics** [magento-research/pwa-studio#662]
## This issue is for the following packages:

- [X] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [X] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description
When User adds the configurable product to the cart and wants to edit them, menu with new configuration does not appear.
![image](https://user-images.githubusercontent.com/8816260/49948187-fbd7aa80-ff03-11e8-861e-d6accc919f44.png)
![image](https://user-images.githubusercontent.com/8816260/49948218-11e56b00-ff04-11e8-976d-bf3cffe5f08b.png)

## Expected result:
`Edit Cart Item` menu should show the possible configuration for the existing product

## Additional Information
`Update cart` not send any requests to the server

**Comment by Serunde** [comment]
`Edit Cart Item` is a hard-coded placeholder page. Now that the work on Configurable Products (#278) is complete, this page can be fully implemented. I think this issue might be more applicable as a feature request.

**Comment by ericerway** [comment]
Agreed. Let's groom this tomorrow as a feature request based on the details from the report. Thanks everyone!

**Comment by ericerway** [comment]
Kamino closed and cloned this issue to [magento-research/pwa-studio](https://github.com/magento-research/pwa-studio/issues/665)
