### ISSUE TITLE
Edit cart for configurable products in Venia PWA

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#665]
## This issue is for the following packages:

- [X] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [ ] Bug
- [X] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a shopper I want to edit items in my Venia shopping card that are configurable so that I have the same experience regardless of product type.

When User adds the configurable product to the cart and wants to edit them, menu with new configuration does not appear.
![image](https://user-images.githubusercontent.com/8816260/49948187-fbd7aa80-ff03-11e8-861e-d6accc919f44.png)
![image](https://user-images.githubusercontent.com/8816260/49948218-11e56b00-ff04-11e8-976d-bf3cffe5f08b.png)

## Expected result:
`Edit Cart Item` menu should show the possible configuration for the existing product

## Additional Information
`Update cart` not send any requests to the server

**Comment by ericerway** [comment]
@soumya-ashok we can move this to "In Progress" once you have a moment to add the correct image from the prototype. Thanks!

**Comment by soumya-ashok** [comment]
Mockup for reference
![mini cart - edit](https://user-images.githubusercontent.com/25960021/50032803-8b8c6000-ffbb-11e8-823e-4991aa2d56e9.jpg)

**Comment by tjwiebell** [comment]
Edit Item feature will be flagged for being hidden in 2.0 release, and this issue will be updated with reference to how that was accomplished.
