### ISSUE TITLE
Setup eslint to sort object properties and destructure keys alphabetically

### ISSUE THREAD

**Issue by Starotitorov** [magento-research/pwa-studio#683]
## This issue is for the following packages:

- [ ] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [ ] Bug
- [x] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

We can specify eslint rule [sort-keys](https://eslint.org/docs/rules/sort-keys) to require to sort properties alphabetically when defining objects.

We can think about adding a rule to the eslint config to require destructure keys to be sorted too. There is an eslint plugin for this [eslint-plugin-sort-destructure-keys](https://www.npmjs.com/package/eslint-plugin-sort-destructure-keys).

@supernova-at, [here](https://github.com/magento-research/pwa-studio/pull/591#discussion_r242986388) you asked us to sort destructure keys, so I guess in this case it is better to setup our code quality tools to check this, I can do this.

@jimbo, @supernova-at, what do you think?

**Comment by jimbo** [comment]
@supernova-at I generally don't ask people to sort things alphabetically in PR feedback. It's always been a thing where, if we care enough, we can apply lint rules (as suggested here).

@Starotitorov I'm hesitant to apply a lint rule to accomplish this because such rules tend to be overly strict. That said, I think the destructuring rule would be safe.

**Comment by jimbo** [comment]
We use [`@magento/eslint-config`](https://www.npmjs.com/package/@magento/eslint-config) for our lint rules.

**Comment by supernova-at** [comment]
> @supernova-at I generally don't ask people to sort things alphabetically in PR feedback. It's always been a thing where, if we care enough, we can apply lint rules (as suggested here).

🖖
