### ISSUE TITLE
Checkout layout is broken in safari

### ISSUE THREAD

**Issue by AlexeyKaryka** [magento-research/pwa-studio#684]
## This issue is for the following packages:

- [ X ] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [ X ] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

Checkout  layout in cart drower heads from bottom to top of the drower and a little cuts off
![image](https://user-images.githubusercontent.com/25349273/50292068-3bad0d80-0481-11e9-827a-7884fe7ce706.png)

## Expected result:

Checkout layout in safari should be the same as in chrome
![image](https://user-images.githubusercontent.com/25349273/50292101-52536480-0481-11e9-9ce5-bcf307649e15.png)

**Comment by awilcoxa** [comment]
closing as PR is merged
