### ISSUE TITLE
UAT: Sign In Button Style Incorrect

### ISSUE THREAD

**Issue by awilcoxa** [magento-research/pwa-studio#686]
The sign in button in the left drawer for Venia is incorrect. The styling should be corrected to ensure adherence to design spec. 

Issue #1 from: https://wiki.corp.magento.com/display/FF/Venia+UX+Issues

Button Location: 
1) Left Drawer, bottom 
2) Left Drawer > Sign In> Sign in form 

Fix to button should include: 
"Medium" size
Dark gray
Fill style

- [ x] `venia-concept`
- [ ] `pwa-buildpack`
- [x ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [ x] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

**Comment by awilcoxa** [comment]
Current: 
![image](https://user-images.githubusercontent.com/44207440/50295597-059a6a00-043e-11e9-859e-2924c4434584.png)

Fixed: 
![image](https://user-images.githubusercontent.com/44207440/50295624-164ae000-043e-11e9-858d-6d3e51af3399.png)

**Comment by AlexeyKaryka** [comment]
This issue is covered by this PR #708

**Comment by dmtrkad** [comment]
@jimbo , @supernova-at , Could you please review it ?
