### ISSUE TITLE
UAT: Correction to Required Field Indicator

### ISSUE THREAD

**Issue by awilcoxa** [magento-research/pwa-studio#687]
Required field indicator should be corrected in order to ensure adherence to current design. 

All fields should be corrected to apply correct styling. 

Issue #2: https://wiki.corp.magento.com/display/FF/Venia+UX+Issues

- [ x] `venia-concept`
- [ ] `pwa-buildpack`
- [ x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [x ] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

**Comment by awilcoxa** [comment]
Current Version: 
![image](https://user-images.githubusercontent.com/44207440/50295807-89eced00-043e-11e9-8f07-e3b8bd528e7d.png)


Fixed Version: 
![image](https://user-images.githubusercontent.com/44207440/50295823-92452800-043e-11e9-8239-1e411ee0c901.png)

**Comment by AlexeyKaryka** [comment]
This issue is covered by this PR #708

**Comment by dmtrkad** [comment]
@jimbo , @supernova-at Could you please review it ?
