### ISSUE TITLE
UAT: Correct "Create an Account" button

### ISSUE THREAD

**Issue by awilcoxa** [magento-research/pwa-studio#688]
Update styling to current version of "Create an Account" Button contained within the left drawer to apply updated design specs. 

Issue #4: https://wiki.corp.magento.com/display/FF/Venia+UX+Issues

- [x ] `venia-concept`
- [ ] `pwa-buildpack`
- [ x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [x ] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

**Comment by AlexeyKaryka** [comment]
This issue is covered by this PR #708
