### ISSUE TITLE
UAT: correct "Forgot Your Password Link" color

### ISSUE THREAD

**Issue by awilcoxa** [magento-research/pwa-studio#689]
Correct the text and color of the "forgot your password" link to adhere to current design spec. 

Corrections:
Update color to #C0123F 
Change text to read "Forgot password?"

Issue #5: https://wiki.corp.magento.com/display/FF/Venia+UX+Issues

## This issue is for the following packages:

- [ x] `venia-concept`
- [ ] `pwa-buildpack`
- [ x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [ x] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

**Comment by AlexeyKaryka** [comment]
This issue is covered by this PR #708
