### ISSUE TITLE
UAT: Category Pages Missing Title and Banner

### ISSUE THREAD

**Issue by awilcoxa** [magento-research/pwa-studio#691]
Category pages are currently missing the category title and hero banner. Title should be displayed as according to design spec. 

Isuse # 7: https://wiki.corp.magento.com/display/FF/Venia+UX+Issues

## This issue is for the following packages:

- [x ] `venia-concept`
- [ ] `pwa-buildpack`
- [ x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [x ] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

**Comment by awilcoxa** [comment]
Current version (as displayed on "Dresses" category): 
![image](https://user-images.githubusercontent.com/44207440/50296822-ee10b080-0440-11e9-9a72-bf7eb9cf753b.png)


Correct Version: 

![image](https://user-images.githubusercontent.com/44207440/50296854-fd8ff980-0440-11e9-9872-b568f1fc2b33.png)

**Comment by AlexeyKaryka** [comment]
It looks like GraphQL schemas on backend-side don't provide banner images for categories

**Comment by dmtrkad** [comment]
@jimbo , @supernova-at Could you please review it ?
