### ISSUE TITLE
UAT: Shopping Cart "More Actions" Indicator Corrections

### ISSUE THREAD

**Issue by awilcoxa** [magento-research/pwa-studio#692]
The "More Actions" (kebab) indicator within the Shopping Cart is currently not correct according to design. 

Issue # 8: https://wiki.corp.magento.com/display/FF/Venia+UX+Issues 

Corrections: 
Color #212121 
top-aligned to the text

## This issue is for the following packages:

- [x ] `venia-concept`
- [ ] `pwa-buildpack`
- [ x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [ x] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

**Comment by awilcoxa** [comment]
Current version: 
![image](https://user-images.githubusercontent.com/44207440/50297324-311f5380-0442-11e9-8142-76664c1c3d7c.png)

Updated version: 

![image](https://user-images.githubusercontent.com/44207440/50297345-3a102500-0442-11e9-8843-2c281c4c1209.png)

**Comment by AlexeyKaryka** [comment]
This issue is covered by this PR #708
