### ISSUE TITLE
UAT: Correction to Checkout Subtotal text

### ISSUE THREAD

**Issue by awilcoxa** [magento-research/pwa-studio#693]
Text and formatting for "Subtotal" are currently incorrect within the right nav drawer during checkout (when items are contained within cart). 

Issue 9:https://wiki.corp.magento.com/display/FF/Venia+UX+Issues

Current Version: "Subtotal (# Items) ($Amount)"
Correct version "Cart Total: ($Amount) (# Items)"

## This issue is for the following packages:

- [ x] `venia-concept`
- [ ] `pwa-buildpack`
- [x ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [ x] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

**Comment by awilcoxa** [comment]
Current Version: 
![image](https://user-images.githubusercontent.com/44207440/50297749-27e2b680-0443-11e9-95fb-dd251192c0b7.png)

Correct Version: 
![image](https://user-images.githubusercontent.com/44207440/50297765-316c1e80-0443-11e9-8ad2-69473d4620dd.png)

**Comment by AlexeyKaryka** [comment]
This issue is covered by this PR #708
