### ISSUE TITLE
UAT: Styling for "Checkout" Button is Incorrect

### ISSUE THREAD

**Issue by awilcoxa** [magento-research/pwa-studio#694]
The current styling for the "Checkout" button in the right hand nav drawer (when items are added to cart) is incorrectly not in adherence to design. 

Issue 10: https://wiki.corp.magento.com/display/FF/Venia+UX+Issues

Corrections to be applied: 
"Medium" size
Dark gray
Fill style 

## This issue is for the following packages:

- [x ] `venia-concept`
- [ ] `pwa-buildpack`
- [ x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [ x] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

**Comment by awilcoxa** [comment]
Current Version: 

![image](https://user-images.githubusercontent.com/44207440/50298000-bce5af80-0443-11e9-8bee-795ce55001c0.png)


Correct Version; 

![image](https://user-images.githubusercontent.com/44207440/50298015-c5d68100-0443-11e9-9ada-3f06614bedcf.png)

**Comment by dmtrkad** [comment]
@jimbo , @supernova-at Could you please review it ?
