### ISSUE TITLE
UAT: Checkout Drawer Incorrect Styling

### ISSUE THREAD

**Issue by awilcoxa** [magento-research/pwa-studio#695]
There are currently various inconsistencies within the checkout drawer, including text and styling issues. Issues should be resolved to adhere to current design. 

Issue 11: https://wiki.corp.magento.com/display/FF/Venia+UX+Issues 

Corrections Include: 
Prompt text color #C0123F
Get it by pre-populated with a default shipping method
Place order changed to "Confirm Order"
Disabled button style for "Confirm Order" updated to "medium" size, light gray, fill style
Cancel button added - this will lead the user back to the first cart state
Currently, the rows have to be filled in order from top to bottom. The original intent was for the user to be able to begin where they wanted to, so all rows should be clickable / editable
The confirm order button converts to an enabled state (dark gray fill) when all required information is filled out
Once a section is filled out, an edit icon needs to display next to it like on "get it by"

## This issue is for the following packages:

- [x ] `venia-concept`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [x ] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

**Comment by awilcoxa** [comment]
Current: 

![image](https://user-images.githubusercontent.com/44207440/50298319-7a70a280-0444-11e9-85d9-8ece7ceb7e35.png)

Correct: 

![image](https://user-images.githubusercontent.com/44207440/50298331-8197b080-0444-11e9-9206-7119c8b92f2a.png)

**Comment by supernova-at** [comment]
Assigning to myself, as I am taking over this ticket.
