### ISSUE TITLE
UAT: Site Header is not Sticky

### ISSUE THREAD

**Issue by awilcoxa** [magento-research/pwa-studio#698]
The current site header is not sticky throughout the entire Venia storefront. The site header should be sticky and should be in view during scroll interactions according to design spec. Issue applies to all pages. 

Issue 16: https://wiki.corp.magento.com/display/FF/Venia+UX+Issues 

## This issue is for the following packages:

- [ x] `venia-concept`
- [ ] `pwa-buildpack`
- [x ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [x ] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

**Comment by Starotitorov** [comment]
@awilcoxa, we do not have permissions to view the page https://wiki.corp.magento.com/display/FF/Venia+UX+Issues

**Comment by awilcoxa** [comment]
@Starotitorov the page doesn't have any additional information on this issue that isn't already contained here in the ticket. The invision prototype has additional screens for the concept of the "sticky header" see here: https://magento.invisionapp.com/share/YMO2OUHX84B#/screens/320124803 

the top menu/banner should be sticky during scrolling actions.

**Comment by Starotitorov** [comment]
@awilcoxa, thank you for the response, the bug was fixed in this pull request https://github.com/magento-research/pwa-studio/pull/711/files.

**Comment by awilcoxa** [comment]
Closing, PR is merged
