### ISSUE TITLE
UAT: Image Carousel Indicator Issues

### ISSUE THREAD

**Issue by awilcoxa** [magento-research/pwa-studio#699]
Image Carousel indicator is currently missing and does not correctly indicate state (carousel place). 
Carousel indicator (circle) should be filled according to user's current place within image carousel. 

Issue 17: https://wiki.corp.magento.com/display/FF/Venia+UX+Issues 

Image carousel Scrolling arrows are missing. Carousel should contain left and right arrows to indicate scrolling action. 

Issue 18: https://wiki.corp.magento.com/display/FF/Venia+UX+Issues 

## This issue is for the following packages:

- [ x] `venia-concept`
- [ ] `pwa-buildpack`
- [ x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [x ] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

**Comment by awilcoxa** [comment]
Current: 

![image](https://user-images.githubusercontent.com/44207440/50299209-a9881380-0446-11e9-97a8-7680789b469f.png)

Correct: 

![image](https://user-images.githubusercontent.com/44207440/50299221-b278e500-0446-11e9-9fb8-31b63c1a45fc.png)

**Comment by AlexeyKaryka** [comment]
This issue is covered by https://github.com/magento-research/pwa-studio/pull/615

**Comment by dmtrkad** [comment]
@jimbo , @supernova-at Could you please review it ?

**Comment by awilcoxa** [comment]
PR is merged
