### ISSUE TITLE
Checkout experience for Venia (PWA)

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#70]
## This issue is for the following packages:

[X] `venia-concept`
[X] `pwa-buildpack`
[X] `peregrine`
[X] `pwa-module`
[X] `pwa-devdocs`

## This issue is a:

[ ] Bug
[X] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a shopper, I want a fast and seamless checkout experience on Venia from my mobile and desktop device so that I can make purchases quickly and with confidence.

Checkout
Login / Register
Multiple Accounts
Billing Information
Shipping Address
Payment Method
Order Review
Order Placed

## Expected result:

Fully developed Checkout experience in Venia theme from checkout to confirmation
Testing and documentation as appropriate

**Comment by awilcoxa** [comment]
Closing as complete, there is still a single pending issue in Review/QA but otherwise consider current iteration of checkout to be done at this time.
