### ISSUE TITLE
UAT: Color Swatches Missing Tooltips

### ISSUE THREAD

**Issue by awilcoxa** [magento-research/pwa-studio#700]
On the Product Display Page when a product has color options/configurations and swatches are displayed, selecting a color does not correctly display a tooltip for color name. 

Issue 19: https://wiki.corp.magento.com/display/FF/Venia+UX+Issues

## This issue is for the following packages:

- [x ] `venia-concept`
- [ ] `pwa-buildpack`
- [x ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [x ] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

**Comment by dmtrkad** [comment]
@jimbo , @supernova-at Could you please review it ?
