### ISSUE TITLE
UAT: Quantity Selector Missing dropdown/selection Indicator

### ISSUE THREAD

**Issue by awilcoxa** [magento-research/pwa-studio#702]
On the Product Display Page, the quantity indicator currently does not contain the dropdown or selector indicator. This indicator should be displayed in order to indicate interaction. 

Issue 21: https://wiki.corp.magento.com/display/FF/Venia+UX+Issues

Correction: 
Apply dropdown arrow indicators to quantity field 

## This issue is for the following packages:

- [x ] `venia-concept`
- [ ] `pwa-buildpack`
- [ x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [ x] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

**Comment by awilcoxa** [comment]
Current: 

![image](https://user-images.githubusercontent.com/44207440/50299958-95ddac80-0448-11e9-97ca-291e8e06f7b6.png)

Correct: 

![image](https://user-images.githubusercontent.com/44207440/50299972-9f671480-0448-11e9-8846-17e666e8bceb.png)

**Comment by AlexeyKaryka** [comment]
Actually current state of quantity field provide indicator icon, it look as on screenshot:
![image](https://user-images.githubusercontent.com/25349273/50351331-d9bcd880-0552-11e9-82ba-32b77928c8e2.png)
So what is the actual and up-to-date design for this indicator? Like on my screen or like on screen in this issue?

**Comment by dmtrkad** [comment]
@jimbo , @supernova-at Could you please review it ?

**Comment by awilcoxa** [comment]
Closing as non-issue
