### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by premamdckap** [magento-research/pwa-studio#705]
While executing npm run build, getting the following error.

lerna ERR! npm run build -s exited 2 in '@magento/venia-concept'

node -v => 10.14.2
npm -v => 6.4.1
Magento => 2.3
Ubuntu => 16.04

Help me to resolve this issue!

**Comment by mhhansen** [comment]
Hey! couldn't be able to get a `npm run build exited 2 in '@magento/venia-concept'`
Can you provide a deeper spec of the error from console you're getting so others can take a look and jump in to assist you, or that's the only line you get?

**just in case**
Double check if your Magento is in `developer` mode (so instrospection is allowed). you can always use default url in the `.env` file, [from release/2.0 branch](https://github.com/magento-research/pwa-studio/blob/release/2.0/packages/venia-concept/.env.dist). ensure you're building `release/2.0` branch and also to have your `.env` up to date with the latest version.

**Comment by Jordaneisenburger** [comment]
Might also wanna try installing node 8.x.x since that's the one referred to in the docs

**Comment by awilcoxa** [comment]
closing during backlog cleanup, if issues still exists please reopen for future prioritization.
