### ISSUE TITLE
Error in executing command npm run build on windows

### ISSUE THREAD

**Issue by priyankagarg8** [magento-research/pwa-studio#706]
Log file:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.4.1
3 info using node@v11.5.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle @magento/pwa-studio@2.0.0~prebuild: @magento/pwa-studio@2.0.0
6 info lifecycle @magento/pwa-studio@2.0.0~build: @magento/pwa-studio@2.0.0
7 verbose lifecycle @magento/pwa-studio@2.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle @magento/pwa-studio@2.0.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\xampp\htdocs\pwa-studio\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;D:\Xampp\php;C:\Program Files (x86)\Bitvise SSH Client;C:\Program Files\TortoiseSVN\bin;C:\ProgramData\ComposerSetup\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files\PuTTY\;C:\Program Files\nodejs\;D:\python36\Scripts\;D:\python36\;C:\Users\Admin\AppData\Roaming\Composer\vendor\bin;C:\Users\Admin\AppData\Roaming\npm
9 verbose lifecycle @magento/pwa-studio@2.0.0~build: CWD: D:\xampp\htdocs\pwa-studio
10 silly lifecycle @magento/pwa-studio@2.0.0~build: Args: [ '/d /s /c', 'npx lerna run --stream build -- -s' ]
11 silly lifecycle @magento/pwa-studio@2.0.0~build: Returned: code: 1  signal: null
12 info lifecycle @magento/pwa-studio@2.0.0~build: Failed to exec build script
13 verbose stack Error: @magento/pwa-studio@2.0.0 build: `npx lerna run --stream build -- -s`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:978:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid @magento/pwa-studio@2.0.0
15 verbose cwd D:\xampp\htdocs\pwa-studio
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v11.5.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error @magento/pwa-studio@2.0.0 build: `npx lerna run --stream build -- -s`
22 error Exit status 1
23 error Failed at the @magento/pwa-studio@2.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by mhhansen** [comment]
Hey! currently you've to have unix based (linux/osx) to run and build pwa.
refer to the [issue 236](https://github.com/magento-research/pwa-studio/issues/236#issuecomment-424472546) for a side approach, installing ubuntu as a windows subsystem.

**Comment by awilcoxa** [comment]
closing during backlog cleanup, if issues still exists please reopen for future prioritization.
