### ISSUE TITLE
Product Details experience for Venia (PWA)

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#71]
## This issue is for the following packages:

[X] `venia-concept`
[X] `pwa-buildpack`
[X] `peregrine`
[X] `pwa-module`
[X] `pwa-devdocs`

## This issue is a:

[ ] Bug
[X] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a shopper, I want a fast and seamless product details on Venia from my mobile and desktop device so that I can be informed with the right level of detail and make confident purchases quickly in checkout.

Product Page
Compare Products

## Expected result:

Fully developed Product Details experience in Venia theme leading to Add to Cart
Testing and documentation as appropriate

**Comment by awilcoxa** [comment]
Closing as complete. Remaining or additional work will be logged against a new epic post FY19 planning.
