### ISSUE TITLE
npm run build error for default backend url

### ISSUE THREAD

**Issue by ranahemantkumar** [magento-research/pwa-studio#714]
I am trying npm run build command after successfully using npm install on pwa-studio on my local system
## This issue is for the following packages:

- [ ] `venia-concept`
- [# ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [# ] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             | 2.3 |
| Operating System + version  | windows 10 |
| node.js version (`node -v`) | 8.11.4 |
| npm version (`npm -v`)      | 6.5.0 |

## Description

I am trying to run npm run build command after successfully using npm install on windows OS(run as administrator). I have followed steps listed here: https://magento-research.github.io/pwa-studio/venia-pwa-concept/setup/ , copied .env.dist to .env and didn't made any changes so its running with default magento backend url and settings. **I am getting below error:**

@magento/pwa-buildpack: src\magento-layout-loader\__tests__\magento-layout-loader.spec.js -> dist\magento-layout-loader\__tests__\magento-layout-loader.spec.js
@magento/pwa-buildpack: src\magento-layout-loader\__tests__\validateConfig.spec.js -> dist\magento-layout-loader\__tests__\validateConfig.spec.js
@magento/pwa-buildpack: src/magento-layout-loader/__tests__/__fixtures__/only-entry/index.js: Unexpected token (4:11)
lerna ERR! npm run build -s exited 1 in '@magento/pwa-buildpack'
lerna ERR! npm run build -s stdout:
C:\Users\hemant.kumar\pwa-studio\pwa-studio\node_modules\rimraf\bin.js
C:\Users\hemant.kumar\pwa-studio\pwa-studio\node_modules\babel-cli\bin\babel.js
src\ExtensionComponentWrap\index.js -> dist\ExtensionComponentWrap\index.js
src\index.js -> dist\index.js
src\magento-layout-loader\babel-plugin-magento-layout.js -> dist\magento-layout-loader\babel-plugin-magento-layout.js
src\magento-layout-loader\index.js -> dist\magento-layout-loader\index.js
src\magento-layout-loader\validateConfig.js -> dist\magento-layout-loader\validateConfig.js
src\magento-layout-loader\__tests__\babel-plugin-magento-layout.spec.js -> dist\magento-layout-loader\__tests__\babel-plugin-magento-layout.spec.js
src\magento-layout-loader\__tests__\magento-layout-loader.spec.js -> dist\magento-layout-loader\__tests__\magento-layout-loader.spec.js
src\magento-layout-loader\__tests__\validateConfig.spec.js -> dist\magento-layout-loader\__tests__\validateConfig.spec.js

lerna ERR! npm run build -s stderr:
npx: installed 1 in 2.308s
Path must be a string. Received undefined
npx: installed 1 in 2.603s
Path must be a string. Received undefined
src/magento-layout-loader/__tests__/__fixtures__/only-entry/index.js: Unexpected token (4:11)

lerna ERR! npm run build -s exited 1 in '@magento/pwa-buildpack'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @magento/pwa-studio@2.0.0 build: `npx lerna run --stream build -- -s`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @magento/pwa-studio@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hemant.kumar\AppData\Roaming\npm-cache\_logs\2018-12-25T13_22_47_489Z-debug.log

**Content of log file is:** 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\hemant.kumar\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.5.0
3 info using node@v8.11.4
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle @magento/pwa-studio@2.0.0~prebuild: @magento/pwa-studio@2.0.0
6 info lifecycle @magento/pwa-studio@2.0.0~build: @magento/pwa-studio@2.0.0
7 verbose lifecycle @magento/pwa-studio@2.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle @magento/pwa-studio@2.0.0~build: PATH: C:\Users\hemant.kumar\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\hemant.kumar\pwa-studio\pwa-studio\node_modules\.bin;C:\Program Files\ImageMagick-7.0.7-Q16;C:\Program Files\Docker\Docker\Resources\bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\PuTTY\;C:\Program Files (x86)\Skype\Phone\;C:\ProgramData\ComposerSetup\bin;C:\Program Files\TortoiseGit\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\hemant.kumar\AppData\Roaming\Composer\vendor\bin;C:\Program Files\Microsoft VS Code\bin;C:\Users\hemant.kumar\AppData\Roaming\npm;C:\xampp72\php
9 verbose lifecycle @magento/pwa-studio@2.0.0~build: CWD: C:\Users\hemant.kumar\pwa-studio\pwa-studio
10 silly lifecycle @magento/pwa-studio@2.0.0~build: Args: [ '/d /s /c', 'npx lerna run --stream build -- -s' ]
11 silly lifecycle @magento/pwa-studio@2.0.0~build: Returned: code: 1  signal: null
12 info lifecycle @magento/pwa-studio@2.0.0~build: Failed to exec build script
13 verbose stack Error: @magento/pwa-studio@2.0.0 build: `npx lerna run --stream build -- -s`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\hemant.kumar\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\hemant.kumar\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid @magento/pwa-studio@2.0.0
15 verbose cwd C:\Users\hemant.kumar\pwa-studio\pwa-studio
16 verbose Windows_NT 10.0.10586
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hemant.kumar\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v8.11.4
19 verbose npm  v6.5.0
20 error code ELIFECYCLE
21 error errno 1
22 error @magento/pwa-studio@2.0.0 build: `npx lerna run --stream build -- -s`
22 error Exit status 1
23 error Failed at the @magento/pwa-studio@2.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

## Expected result:

npm run build should be executed without any errors.

**Comment by sathishkumar555** [comment]
I also facing the same issue

**Comment by Jordaneisenburger** [comment]
This most likely has to do with Windows best chances are switching to a UNIX (mac/linux) based system. Even if you fix this issue more will appear. I suggest waiting until it's more thoroughly tested on Windows or wait for docker support.

**Comment by ranahemantkumar** [comment]
Thanks @Jordaneisenburger . Closing it for now.
