### ISSUE TITLE
Cannot set shipping method in checkout

### ISSUE THREAD

**Issue by AlexeyKaryka** [magento-research/pwa-studio#715]
## This issue is for the following packages:

- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [x] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

Can't set shipping method in checkout  to only presented value - 'Flat rate', after accepting this option I get error message
![image](https://user-images.githubusercontent.com/25349273/50472049-3e9b8700-09c8-11e9-969c-3304b08c7243.png) and also value doesn't save if you go back to checkout points
![image](https://user-images.githubusercontent.com/25349273/50472089-6ee32580-09c8-11e9-9e90-1c96223172ce.png)

## Expected result:

Any presented shipping method available choice should be available to choose without errors and they should be saved in checkout flow.

**Comment by Starotitorov** [comment]
@AlexeyKaryka I can not reproduce the issue. Could you, please, check one more time? Maybe the issue has already been fixed. If you still faces the same issue, please, provide more details and steps to reproduce.

**Comment by AlexeyKaryka** [comment]
@Starotitorov I've rebased to the latest release/2.0 branch and looks like the error still remains, what I did: 
1) I've wiped cookies
2) Added item "Carmina Necklace" from the accessories category
![image](https://user-images.githubusercontent.com/25349273/50740292-79d65b00-11fd-11e9-95e4-6b537295c5b8.png)
3) Successfully filled "Ship To" and "Pay With" 
4) Chose "Flat Rate" item in "Get it by", clicked "Save", as a result I didn't moved to the main checkout page, so I manually clicked "Cancel" in order to get to it and saw that option didn't apply and I got the error.
![image](https://user-images.githubusercontent.com/25349273/50740311-bb670600-11fd-11e9-99f8-e5341b14fec7.png)

**Comment by awilcoxa** [comment]
closing during backlog cleanup, if issues still exists please reopen for future prioritization.
