### ISSUE TITLE
Cannot set static port in PWA studio

### ISSUE THREAD

**Issue by shaarif-titech** [magento-research/pwa-studio#719]
node version :11.0.0
npm version:6.4.1
magento version: 2.3
ubuntu version: 18.04.1 LTS

PWA not setting port.
Reffered url : https://magento-research.github.io/pwa-studio/pwa-buildpack/reference/pwa-dev-server/#specifying-a-port

Set PWA_STUDIO_PORTS_DEVELOPMENT=10010  in .env file but showing

Using environment variables from .env
[pwa-buildpack:WebpackTools:PWADevServer.js] This project's dev server is configured to run at pwa.magento23.venia.local:8097, but port 8097 is in use. The dev server will run temporarily on port 10002; you may see inconsistent ServiceWorker behavior.

**Comment by zetlen** [comment]
Uh oh! That should be working; can you please show me the output of `lsof -i :10010` on your system?

**Comment by awilcoxa** [comment]
closing during backlog cleanup, if issues still exists please reopen for future prioritization.
