### ISSUE TITLE
Shopping Cart experience for Venia (PWA)

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#72]
## This issue is for the following packages:

[X] `venia-concept`
[X] `pwa-buildpack`
[X] `peregrine`
[X] `pwa-module`
[X] `pwa-devdocs`

## This issue is a:

[ ] Bug
[X] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a shopper, I want a fast and seamless shopping cart experience on Venia from my mobile and desktop device that allows me to add, modify or delete items as appropriate of all product types.

## Expected result:

Fully developed Cart and Mini-Cart experience in Venia theme up through checkout including management of cart when added from a Product Details or Category page.
Testing and documentation as appropriate

**Comment by awilcoxa** [comment]
Calling complete as of PWA 2.0.
