### ISSUE TITLE
[Server Side] Vega Security Vulnerabilities

### ISSUE THREAD

**Issue by vitalics** [magento-research/pwa-studio#720]
## This issue is for the following packages:

- [ ] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [X] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [ ] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description
Vega - automation tool for analyze web apps. After scanning `magento-venia.now.sh` it takes this information: 
![image](https://user-images.githubusercontent.com/8816260/50599350-e6302200-0ebe-11e9-9cde-eafd6cfea57f.png)

## Possible solutions:
**medium vulnerability** `Local Filesystem Paths Found`:
![image](https://user-images.githubusercontent.com/8816260/50599435-298a9080-0ebf-11e9-88d5-272c3167fca5.png)

**medium vulnerability** `Possible Source Code Disclosure`:
![image](https://user-images.githubusercontent.com/8816260/50599487-50e15d80-0ebf-11e9-99fe-82b166e74590.png)

**info vulnerability** `Cookie Secure Falg Not Set`:
![image](https://user-images.githubusercontent.com/8816260/50599527-69517800-0ebf-11e9-81aa-428d4e6aa8ab.png)
about secure cookies:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Secure_and_HttpOnly_cookies

**info vulnerability** `X-Frame-Options Header Not Set`:
![image](https://user-images.githubusercontent.com/8816260/50599647-be8d8980-0ebf-11e9-9fdf-ae971f8b67ff.png)
Need set header for all requests this header: `X-Frame-Options: DENY, SAMEORIGIN, or ALLOW-FROM `

**Comment by awilcoxa** [comment]
@dpatil-magento @sharkySharks Can you take a look at this?

**Comment by dpatil-magento** [comment]
@awilcoxa @zetlen   Is this same as #957?

**Comment by zetlen** [comment]
Almost. It additionally tells us we need X-FRAME-OPTIONS, which is true. We also need a content security policy. They're quick to add. So this should stay open.

**Comment by zetlen** [comment]
Rather than integrating an additional third-party tool for security vulnerabilities, we will have a much more robust CICD process if we just work with GitHub's [automated security patches](https://help.github.com/en/articles/configuring-automated-security-fixes) when they hit mainline.
