### ISSUE TITLE
Replace lists in Venia with Peregrine list components

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#74]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[X] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## This issue is a:

[ ] Bug
[X] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a developer, I want to see examples in completed interfaces of Peregrine components in use.

(carryover from magento-research-backoffice#25)

## Expected result:

All lists which can be changed are changed to use Peregrine lists
Visual treatment is either unchanged or improved
Performance metrics increase in some measurable way

**Comment by jimbo** [comment]
Closed by #62.
