### ISSUE TITLE
[Bug] Redundant Configurable Product In Cart

### ISSUE THREAD

**Issue by Serunde** [magento-research/pwa-studio#740]
## This issue is for the following packages:

- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [x] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             | 2.3 |
| Operating System + version  | Ubuntu 18.04 |
| node.js version (`node -v`) | 8.15 |
| npm version (`npm -v`)      | 6.4.1 |

## Description

The order in which configurable options are selected is affecting which simple product variant will be added to the cart. As a result, two items can have the same selected options but will appear separately.

![screenshot from 2019-01-10 10-01-53](https://user-images.githubusercontent.com/17077852/50988102-76262b00-14c0-11e9-8d29-ec0107519e68.png)

## Expected result:

Identical products should be grouped together.

![screenshot from 2019-01-10 10-16-51](https://user-images.githubusercontent.com/17077852/50988244-dfa63980-14c0-11e9-8f3b-e400411f0660.png)

## Possible solutions:

A simple solution for this would be to sort the options payload by the `position` attribute of `ConfigurableProductOptions` before handing it to REST. Alternatively, GQL/REST could handle this ordering on its own.

**Comment by awilcoxa** [comment]
This is still an issue, steps to reproduce: 
1) select a product from category page with multiple product configuration (color/size)
2) Select color
3) Select Size
4) add to cart
5) close cart 
6) Back to category page
7) Select same product
8) Select Same Size
9) Select same color
10) Add to cart 

Result: Two unique products will exist in cart both have the same size/color but the two options will be in the order selected.

**Comment by tjwiebell** [comment]
Closing as obsolete, bug doesn't appear to be present in `develop` anymore.
