### ISSUE TITLE
npm run build error - GraphQL introspection is not allowed even in developer mode

### ISSUE THREAD

**Issue by renjith174** [magento-research/pwa-studio#746]
node version: v8.10.0
npm version: v3.5.2

magento/pwa-studio@2.0.0

error found even in developer mode

> Validating queries based on schema at http://pwa.mcfadyen.com/graphql...
> 
> lerna ERR! npm run build -s stderr:
> Using environment variables from .env
> Cannot validate queries because the configured Magento backend http://pwa.mcfadyen.com/ disallows introspection in "production" mode. If you can do so, set this Magento instance to "developer" mode.
> 
> The introspection query to http://pwa.mcfadyen.com/graphql failed with the following errors:
>         - GraphQL introspection is not allowed, but the query contained __schema or __type
>         - Max query depth should be 10 but got 11.
> 
> The current default backend for Venia development is:
> 
>         https://release-dev-rxvv2iq-zddsyhrdimyra.us-4.magentosite.cloud/
> 
> The configured MAGENTO_BACKEND_URL in the current environment is
> 
>         http://pwa.mcfadyen.com/
>

**Comment by brendanfalkowski** [comment]
May not solve the issue, but you need Node 10.14.1+ following some changes in the past few weeks. Probably a good idea to start off updating your Node version.

**Comment by renjith174** [comment]
@brendanfalkowski Thanks for your reply.
I have updated the node version to the latest stable version. But the issue still persists.

Thanks

**Comment by Jordaneisenburger** [comment]
You need to run Magento in developer mode. To check what you are running do this `bin/magento deploy:mode:show` if the results looks like `Current application mode: developer.` you need to run `bin/magento deploy:mode:set developer`

**Comment by renjith174** [comment]
@Jordaneisenburger 
I have already enabled developer mode and it's still not working.

**Comment by brendanfalkowski** [comment]
Not sure what to suggest, but maybe:

```
git pull
composer install
php bin/magento setup:upgrade
```

Things are still changing often here, so you could be in a "bad version" hole.

**Comment by brian-labelle** [comment]
Try enabling developer mode using a different approach. I was running into the same issue. I thought I was in developer mode, but I var_dumped `$this->appState->getMode()` and found that I was actually running in default mode, despite my nginx configs specifying that I should be running in developer mode.

You can check your mode by running `bin/magento deploy:mode:show`

You can change to developer mode by running
```bash
rm -rf <your Magento install dir>/generated/metadata/* <your Magento install dir>/generated/code/*
bin/magento deploy:mode:set developer
```

Introspection should be enabled for developer mode:

It we look at `Magento\GraphQl\Controller\GraphQl`, it calls `Magento\Framework\GraphQl\Query\QueryProcessor` method `process`

`Magento\Framework\GraphQl\Query\QueryProcessor::process` method contains the following code
```php
if  (!$this->exceptionFormatter->shouldShowDetail()) {
    DocumentValidator::addRule(new QueryDepth(10));
    DocumentValidator::addRule(new DisableIntrospection());
}
```
`Magento\Framework\GraphQl\Exception\ExceptionFormatter` method `shouldShowDetail` returns `true` if we are in developer mode

Once I enabled developer mode using the cli commands, I no longer received this error message running the build

**Comment by tjwiebell** [comment]
Magento 2.3.1 introduced introspection in production mode, so this should no longer be an issue. Please re-open if you're still having problems.
