### ISSUE TITLE
Category experience for Venia (PWA)

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#75]
## This issue is for the following packages:

[X] `venia-concept`
[X] `pwa-buildpack`
[X] `peregrine`
[X] `pwa-module`
[X] `pwa-devdocs`

## This issue is a:

[ ] Bug
[X] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a shopper, I want a fast and seamless category experience on Venia from my mobile and desktop device to that I have the right level of detail to make a confident purchase or find more information with Product Details.

Grid View
List View

## Expected result:

Fully developed Category experience in Venia theme leading to Product Details and Add to Cart
Testing and documentation as appropriate

**Comment by awilcoxa** [comment]
Closing as complete. Remaining or additional work will be logged against a new epic post FY19 planning.
