### ISSUE TITLE
Query validation in GraphQL Playground is broken

### ISSUE THREAD

**Issue by brendanfalkowski** [magento-research/pwa-studio#769]
While testing GraphQL endpoints I noticed that query validation in GraphQL Playground throws a false-negative for proper queries with query variables.

The validator fails but the query still runs.

## This issue is for the following packages:

- [ ] `venia-concept`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [x] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             | 2.3.0 |
| Operating System + version  | Mac 10.14 |
| node.js version (`node -v`) | 10.15.0 |
| npm version (`npm -v`)      | 6.4.1 |

## Description

I created a CMS Block named "sample" to test.

Screenshot from GraphQL Playground for the core `getCmsBlocks` query.

![screen shot 2019-01-18 at 4 18 39 pm](https://user-images.githubusercontent.com/214924/51419098-be86be00-1b3c-11e9-932c-ff559e89afc7.png)

Screenshot for the same query using the older `graphiql` tool via the ChromiQL extension. The validation is successful and the query runs:

![screen shot 2019-01-18 at 4 28 27 pm](https://user-images.githubusercontent.com/214924/51419291-225db680-1b3e-11e9-8026-1f154f8ffe8f.png)

I'm not sure if this is a GraphQL Playground bug or a problem with the schema not being validated properly.

## Expected result:

The validator should see the query variables are valid.

**Comment by tjwiebell** [comment]
Closing as obsolete, re-ran repro steps and didn't see validation error anymore.

![Screen Shot 2019-05-31 at 4 58 09 PM](https://user-images.githubusercontent.com/462953/58736965-5b981400-83c5-11e9-8070-38da0ad66fad.png)
