### ISSUE TITLE
Feedback on page: /venia-pwa-concept/setup/

### ISSUE THREAD

**Issue by Banhawy** [magento-research/pwa-studio#775]
## This issue is for the following packages:

- [ ] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [ ] Bug
- [ ] Feature suggestion
- [ x ] Documentation issue
- [ ] Other (Please Specify)

## Description

The documentation is very useful when it comes to setting up a development environment locally, but there is little mention of how to deploy PWA to production or on a remote server. I want to to have the Venia storefront PWA on a remote server which will talk to a Magento backend on another server. 

## Expected result:

I admit I am inexperienced when it comes to Magento and deployments but a litte guide or links to related documentations/articles about this use case would be a HUGE help to newcomers like me to get PWA Magento sites to production faster.

**Comment by Banhawy** [comment]
Found some relevant documentation here [https://magento-research.github.io/pwa-studio/pwa-buildpack/reference/pwa-dev-server/](url)

**Comment by haxim0r** [comment]
> 
> 
> Found some relevant documentation here [https://magento-research.github.io/pwa-studio/pwa-buildpack/reference/pwa-dev-server/](url)

I also wish to learn why I can't get PWA to work remotely, and would appreciate insight on production deployment.

The link from previous is dead (https://magento-research.github.io/pwa-studio/pwa-buildpack/reference/pwa-dev-server/) !
