### ISSUE TITLE
"[BUG] Full Screen Checkout Drawer"

### ISSUE THREAD

**Issue by supernova-at** [magento-research/pwa-studio#784]
Once the shopper taps into the checkout drawer, they should enter a "full screen" overlay where the shopping cart header is not seen.

Issues should be resolved to adhere to current design:  https://magento.invisionapp.com/share/HVP22925B2Q

## This issue is for the following packages:

- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [x] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

**Comment by DmitryShmaliuk** [comment]
Please, assign to me.

**Comment by DmitryShmaliuk** [comment]
Hi @supernova-at, at your request, i`m adding prioritized to be solve this issue:

- **Research**
- Finding a solution
- **Implementing solution to _venia-concept_ package**
- Testing this solution
- **Pull request**
