### ISSUE TITLE
item is undefined (PDP)[BUG]

### ISSUE THREAD

**Issue by cnu115** [magento-research/pwa-studio#811]
**Describe the bug**
I am having an issue in PDP page
when i am selecting the color and size and when i am click on "add to cart" button throwing an error item is undefined
any one can help this issue ???

**To Reproduce**
Magento sample data.

**Expected behavior**

**Screenshots**

**Please complete the following device information:**
 - Device: [e.g. iPhone6, PC]
 - OS: [e.g. iOS8.1, Windows 10]
 - Magento Version
 - NPM version `npm -v`
 - Node Version `node -v`

**Please let us know what packages this bug is in regards to:**
- [.] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Additional context**

**Possible solutions**
Add any ideas about possible solutions to the problem here.

**Comment by ennostuurman** [comment]
hey @cnu115 I believe this is the same issue https://github.com/magento-research/pwa-studio/issues/626#issuecomment-459288423 ? See my reply to that.

**Comment by cnu115** [comment]
Hi @ennostuurman Thanks for the response. I'll looking into that

**Comment by sirugh** [comment]
@cnu115 please let us know if your issue is resolved by #626.

**Comment by cnu115** [comment]
Pwa Studio it will work for only venia sample data ??. Or it will support Magento sample data also ??

I installed venia sample data then my issue reloved.But for Magento sample data still I am facing an issue.

**Comment by tjwiebell** [comment]
@cnu115 - Right now Venia PWA has a hard dependency on the Venia sample data, mostly around expected schema with extension attributes. I do have a task ear marked to verify the steps needed to support generated performance sample data and Luma sample data, and we'll document those steps if it's reasonably easy to get up and running.

Closing this issue as expected behavior.
