### ISSUE TITLE
 Unable to update quantity in shopping cart

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/pwa-studio#814]
Description:
After adding a product to cart user is unable update quantity via the text field or with the small triangle (increase/decrease) present side of text field.

1. Go to Venia storefront and a add product to cart.
2. Now try editing qty of product in cart (on right side drawer/panel )

Expected behavior:
User should be able to update quantity either by typing in text field or by using small little triangle icon present on side of text field.

Actual behaviour:
User is unable to update the quantity in cart.

Screen:

![image.png](https://images.zenhubusercontent.com/5c585c5aecb0076f3e898431/0df29b94-c9ed-463b-947b-7a5981eb8463)

**Comment by lewisvoncken** [comment]
@dpatil-magento I have just tested this and it is now possible by using the Edit item functionality as the screenshots explain below:

![image](https://user-images.githubusercontent.com/6040343/57733304-0f727300-7654-11e9-925e-d0c4d3d6ca25.png)

![image](https://user-images.githubusercontent.com/6040343/57733312-14cfbd80-7654-11e9-940d-74d30dc427fa.png)

**Comment by dpatil-magento** [comment]
@lewisvoncken agree, I no more see steppers in cart so should be good on this.
