### ISSUE TITLE
User ends up in blank screen when they click on checkout button and then try to remove item from the cart.

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/pwa-studio#821]
Description:
Add to Cart > Click on Checkout > Remove item from cart > Ends up in blank screen.

1. Go to Venia storefront and a add product to cart.
2. Click on Checkout button and now click on "remove item" option present under more options (3 vertical dots).

Expected behavior:
Shopping Cart right drawer should be displayed with message "There are no items in your shopping cart"

Actual - User gets a blank screen without any buttons.

Screen: 
![image.png](https://images.zenhubusercontent.com/5c585c5aecb0076f3e898431/776dc69a-c608-470f-acb4-9d1d0be60bc7)

![image.png](https://images.zenhubusercontent.com/5c585c5aecb0076f3e898431/81293823-f599-48c4-bab1-426e7adb92e2)

**Comment by tjwiebell** [comment]
Fixed by #806
