### ISSUE TITLE
User unable to remove items hidden behind checkout panel (Cart item scrolling area not getting auto adjusted when checkout section opens))

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/pwa-studio#826]
Description:
When user has say 5-7 item sin cart and clicks on checkout and wants to remove say 7th item from the cart, user cant do that action as scrolling area is not getting auto adjusted when checkout section is opened.

1. Navigate to Venia storefront and add say 6-7 items.
2. on Right drawer panel click on Checkout.
3. Now try to remove/edit/update cart item hidden behind checkout section.

Expected:  When Checkout section opens then cart item scrolling area should be auto adjusted allowing user to see all the cart item via scrolling.

Actual:
When checkout section opens the cart item scrolling area is not auto updated making it impossible for user to update bottom cart items as they are hidden behind checkout section.
    
Screen:  In below screen there are 5 items in cart but user cant take any action on 4 and 5th item

![image.png](https://images.zenhubusercontent.com/5c585c5aecb0076f3e898431/46d57fcb-86ca-42c5-8f7d-e37216a0184c)

**Comment by tjwiebell** [comment]
Fixed by #806
