### ISSUE TITLE
Page navigation First Page (<<) and Last page (>>) looks disbaled on first and last pages respctively but they are clickable.

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/pwa-studio#829]
Description:
First page and Last page navigators/anchors are looks disabled but on click they still perform same function as they are enabled. 

1. Go to Venia storefront and navigate to category which has say 4 pages.
2. Now when you are on 1st page scroll down and try to click on disabled first page anchor (<<)   or click on disabled last page anchor (>>) if you are on last page.

Expected behavior:
No action should be performed as user is already on First/Last page respectively.

Actual :
Page scrolls up (icons act as enabled)

**Comment by dani97** [comment]
@dpatil-magento I could not reproduce this issue

**Comment by dpatil-magento** [comment]
@dani97 I tried today on latest code and its working.
