### ISSUE TITLE
Routing resolve failed

### ISSUE THREAD

**Issue by codynguyen1** [magento-research/pwa-studio#83]
## This issue is for the following packages:

[x] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## This issue is a:

[ ] Bug
[ ] Feature suggestion
[ ] Documentation issue
[x] Other (Please Specify)
Installation problem
### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             | 2.3 |
| Operating System + version  |Localhost MacOS MAMP |
| node.js version (`node -v`) |v10.4.1|
| npm version (`npm -v`)      | 6.1.0|

## Description
I get the error:
Routing resolve failed
 Error: 404
    at MagentoRouteHandler.js:67
On console after run npm start

## Expected result:

Show the Venia theme.

**Comment by DrewML** [comment]
Thanks for the report @codynguyen1. Please fill out the "Environment" section of the issue template so we can help debug.

**Comment by codynguyen1** [comment]
Hi Drew,
I'm trying to install using localhost.
I updated the environment field.
Thank you!

**Comment by DrewML** [comment]
Can you open up the Network tab in DevTools, find the request to /graphql, and copy+paste the full response here?

**Comment by codynguyen1** [comment]
Hi @DrewML ,
The response is:
{"data":{"urlResolver":null}}
<img width="360" alt="screenshot at jun 25 08-39-11" src="https://user-images.githubusercontent.com/16347586/41826367-4d4b4eea-7853-11e8-9cdb-b314b38dc877.png">

**Comment by DrewML** [comment]
Thanks Cody. That likely means you're on a slightly outdated version of the 2.3-develop branch of m2. We merged a bug fix semi-recently to correct that. Try it out with the latest changes.

**Comment by codynguyen1** [comment]
Thank you @DrewML, It seems to be solved by now, but it's showing just showing 'CMS Page Stub' title, with no problem logged on the console, how can I navigate to other pages?
<img width="638" alt="1" src="https://user-images.githubusercontent.com/16347586/41838198-f1ea10a4-7889-11e8-8917-4adcd92c75ed.png">
<img width="637" alt="2" src="https://user-images.githubusercontent.com/16347586/41838199-f220fe7a-7889-11e8-93c5-347436a57d3a.png">
<img width="635" alt="3" src="https://user-images.githubusercontent.com/16347586/41838200-f2558262-7889-11e8-9fb4-f216412fce99.png">
<img width="640" alt="4" src="https://user-images.githubusercontent.com/16347586/41838201-f28a2fbc-7889-11e8-8be9-37cc8d642772.png">

**Comment by DrewML** [comment]
Right now, the only UI work that is in `master` is for the catalog page. You'll have to navigate to one of your known category URLs to render UI.

Glad it's working for you.

**Comment by codynguyen1** [comment]
Thank you, @DrewML , now the category is working with empty category I added, but not with the others (gear.html, what-is-new.html..)
I submitted another issue, thank you for your help!
