### ISSUE TITLE
After placing an order if user clicks on Create account button then create account page Email, First and last name field contains value as Null instead of values used during order placement.

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/pwa-studio#830]
Description:
Place an order as guest and click on "Create Account" button > Create account page displays with "null" as values for Email, First and Last name.

1. Go to Venia storefront as guest and Place an order.
2. Click on Create account button on order confirmation page.

Expected behavior:
Create account page should be displayed with pre-filled email, first and last name which are user for order placement.

Actual :
Create account page displayed with null values for email, first and last name.

Screen:

![image.png](https://images.zenhubusercontent.com/5c585c5aecb0076f3e898431/abe72719-1375-4a6d-a859-2b3ca54c4c73)

**Comment by awilcoxa** [comment]
fast follow for 2.0 release
