### ISSUE TITLE
[REFACTORING] Refactor the createAccount form

### ISSUE THREAD

**Issue by VitaliyBoyko** [magento-research/pwa-studio#833]
In order to follow the principle of least astonishment, providing refactoring of createAccount form component is required.
All hardcoded validators should be removed. Instead, utilize ```packages/venia-concept/src/util/formValidators.js``` as a single approach for validation. 
Basic implementation has been done in magento-research/pwa-studio#770.

**Comment by awilcoxa** [comment]
Moving to hold until team can discuss proposed changes
