### ISSUE TITLE
Add Additional Fields to Checkout Form

### ISSUE THREAD

**Issue by awilcoxa** [magento-research/pwa-studio#837]
**Please let us know what packages this feature is in regards to:**
- [x ] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

Currently, the checkout form for billing address inherits additional fields like first/last name from the "ship to section." While this was intentional by design, there is an edge case to consider where this could be poor user experience. Edge cases include: 
* Ship to address is different than billing user ("I'm shipping a gift to my friend") 
* Ship to person is different than billing ("I used my Mom's credit card" ) 

**Describe the solution you'd like**
We need to consider whether or not the additional fields should be present if the "billing address is different than shipping" is deselected. If so, add first/last name to the form.

**Comment by awilcoxa** [comment]
![image](https://user-images.githubusercontent.com/44207440/52353315-ee1a3f00-29f3-11e9-9505-4c7e937ba5a9.png)

**Comment by lewisvoncken** [comment]
@awilcoxa 
This is a duplicate issue and the other issue is more relevant so please close this one.

The following issue is more relevant:
https://github.com/magento-research/pwa-studio/issues/1154

**Comment by awilcoxa** [comment]
closing as a duplicate of #1154
