### ISSUE TITLE
Venia Unit Test Coverage for 2.0

### ISSUE THREAD

**Issue by sirugh** [magento-research/pwa-studio#839]
# What

Our test coverage for Venia is abysmal. This issue is to track our progress in updating the coverage numbers which, at time of writing, are less than 50%.

Additionally we should work to migrate tests from `enzyme` to `react-test-renderer` at the same time.

https://itnext.io/testing-react-16-3-components-with-react-test-renderer-without-enzyme-d9c65d689e88

# How

If you want to help, check out the Venia coverage by running `yarn test` from the root. Pick a file from `packages/venia-concept` with low/red coverage and add a comment here saying that you are going to work on it so that we don't double up.

For example, I would see the following and comment here that I am going to write tests for `TextArea`.

[![Image from Gyazo](https://i.gyazo.com/5a1ff717433e022d96d5f439bd1d5e2d.png)](https://gyazo.com/5a1ff717433e022d96d5f439bd1d5e2d)

While working on the tests I've found it easier to see the results by modifying both `package.json` and `jest.config.js` to make sure I'm only testing the files/components I care about. For example:

In *jest.config.js*, to only collect coverage for `ProductImageCarousel`:
```js
collectCoverageFrom: [
  ...
  'packages/*/{src,lib}/components/ProductImageCarousel/*.js', 
  ...
],
```

In *package.json*, to only test for `ProductImageCarousel`:
```js
"scripts": {
  ...
  "test:dev": "jest --watch packages/venia-concept/src/components/ProductImageCarousel",`
  ...
}
```

**Comment by sirugh** [comment]
Speaking of, I'll be writing coverage for `TextArea`!

**Comment by jimbo** [comment]
And if you reference this issue from a PR, make sure not to use a [keyword that would close it](https://help.github.com/articles/closing-issues-using-keywords/).

**Comment by sirugh** [comment]
Now writing tests for `ProductImageCarousel`.

**Comment by supernova-at** [comment]
I'll tackle `simplePersistence.js`.

**Comment by sirugh** [comment]
Now writing tests for `ProductOptions`.

**Comment by supernova-at** [comment]
Writing tests for `UpwardServerError.js`.

**Comment by supernova-at** [comment]
Writing tests for `packages/venia-concept/src/RootComponents/CMS/CMS.js`

**Comment by supernova-at** [comment]
Picking up `catalog/asyncActions.js`: #873.

**Comment by sirugh** [comment]
Now writing tests for `Checkout` 😨

**Comment by supernova-at** [comment]
Picking up `util/getQueryParameterValue` and `util/getSearchParams`

**Comment by supernova-at** [comment]
On to `src/actions/createAccountPage/`

**Comment by supernova-at** [comment]
Picking up `purchaseHistory`

**Comment by sirugh** [comment]
Now writing tests for `SearchBar`!

**Comment by supernova-at** [comment]
Picking up #919: unit tests for all the reducers.

**Comment by awilcoxa** [comment]
Converted this issue into an Epic that can be moved into "in progress" all issues related to the increase of test coverage should be tied to this initiative/epic and we can define an explicit definition of done related to % test coverage
