### ISSUE TITLE
Content and extension support for PWA Studio

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#84]
## This issue is for the following packages:

[X] `venia-concept`
[X] `pwa-buildpack`
[X] `peregrine`
[X] `pwa-module`
[X] `pwa-devdocs`

## This issue is a:

[ ] Bug
[X] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a developer I want to create and modify Magento 2 content extensions to work seamlessly with PWA Studio so that merchants and partners can use them in a production environment. 

Scenarios:
Support for extensions (relative to Magento)
Content security policy (interceptors)
Support for PWA and non-PWA themes

## Expected result:

Demos and examples of extension support with GraphQL and REST options
Updates to Magento 2 to support new policy and mixed (non-PWA) themes
Documentation and testing (as appropriate)

**Comment by awilcoxa** [comment]
Closing previous epic, remaining effort will be tracked against a new epic pending FY19 planning/kickoff discussions.
