### ISSUE TITLE
Dynamically display store name and year in Footer

### ISSUE THREAD

**Issue by awilcoxa** [magento-research/pwa-studio#843]

**Comment by LucasCalazans** [comment]
@awilcoxa Could you provide more details about that? I searched for a layout like this at the guideline and there is no Store name/Year in the footer
https://magento-research.github.io/pwa-studio/venia-pwa-concept/component/footer/
https://magento.invisionapp.com/share/WQN5F7BYBPG

**Comment by cherdman** [comment]
Blocked depending on whether or not store info graphql query is working.
