### ISSUE TITLE
Component for Filter Button

### ISSUE THREAD

**Issue by awilcoxa** [magento-research/pwa-studio#846]

**Comment by awilcoxa** [comment]
This issue may now be related to #361 and the previously submitted PR (#722) may now be a duplicate based on the new PR by @codeAdrian (#797) 

If the newer PR makes the previous redundant then we should close both #846 and #722

**Comment by awilcoxa** [comment]
test with 2.3.1 Graphql schema and determine if there are new input types

**Comment by awilcoxa** [comment]
on hold pending 2.3.1 compatibility

**Comment by sirugh** [comment]
Closed as this work is most certainly already contained in #797 (issue #361)
