### ISSUE TITLE
Close Cart View and "Continue Shopping"

### ISSUE THREAD

**Issue by awilcoxa** [magento-research/pwa-studio#848]
A user in the cart view should be able to click a button, besides the `x`, that takes them back to the page they were on (category/product/etc). This could be a button that reads `Continue Shopping` and is located to the left of the "Checkout" button in the cart view.

**Comment by soumya-ashok** [comment]
"Continue Shopping" would take them back to the page they were on before they entered the cart. @jimbo and @sirugh - Thoughts?

**Comment by supernova-at** [comment]
Closing as "won't fix".
