### ISSUE TITLE
Zero configuration and setup for PWA Studio

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#85]
## This issue is for the following packages:

[X] `venia-concept`
[X] `pwa-buildpack`
[X] `peregrine`
[ ] `pwa-module`
[X] `pwa-devdocs`

## This issue is a:

[ ] Bug
[X] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a developer, I want to setup and configure PWA Studio for my Magento 2 store with minimal effort so that I can begin development and contribution to the project.

Implement standard connection between M2 storefront and theme
Create index of root components for Venia (development mode)
Improve to PWA Studio environment and setup process
Basic setup and examples (scaffolding) for Venia theme

## Expected result:

Getting started guides (for Venia reference and for Buildpack scaffolded from scratch)
Recommended local configuration for Magento instance
Low-to-zero-configuration setup and scaffolding
For advanced usage, extension points which expose existing, documented APIs (i.e. Webpack, Babel) instead of creating another "advanced" layer to learn
Light and automatic code formatting and linting scripts

**Comment by awilcoxa** [comment]
Calling this complete at this stage.
