### ISSUE TITLE
system fails to query for "<space>0<space<1>" 

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/pwa-studio#854]
Description:
Enter " 0 1" in search box and hit enter >> Infinite loading spinner.  Not a business use case but system fails to query.

1. Navigate to Venia storefront and click on Search icon.
2. Enter " 0 1" in search field and hit enter.

Expected behavior:
No results found message should be displayed.

Actual :
Infinite loading spinner, search never returns results.

Screen:

![image.png](https://images.zenhubusercontent.com/5c585c5aecb0076f3e898431/02065136-52d8-48c7-b713-d153c676e79e)

**Comment by brendanfalkowski** [comment]
I'm sure it's doing something...

![ef2kmsu](https://user-images.githubusercontent.com/214924/52382513-71ef1e00-2a2a-11e9-9dab-0f4869c0b8c4.gif)

**Comment by supernova-at** [comment]
Related PR #1363 .

**Comment by supernova-at** [comment]
It turns out this issue is already fixed on `develop`. Verified on https://magento-venia-develop.now.sh/.
