### ISSUE TITLE
"Add to Cart" button does not handle multiple clicks properly.

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/pwa-studio#855]
Description:
When user clicks on Add to Cart button multiple times then Cart gets updated as separate product for each click.

1. Go to Venia storefront and navigate to any product details page.
2. Select size and color and now click on Add to Cart button multiple times.

Actual:
Cart gets updated for each click as separate product.

Possible Solution:
"Add to cart" button should get disabled until the product gets added to cart. Once product added then again "Add to Cart" button gets enabled.

Screen:

![image.png](https://images.zenhubusercontent.com/5c585c5aecb0076f3e898431/3e6e79bb-761e-46f1-bbfd-ac9adfee72f7)

**Comment by awilcoxa** [comment]
S2. P3. for evaluation after 2.0 release

**Comment by awilcoxa** [comment]
per @zetlen we should fix this via the button component rather than the specific add to cart use case

**Comment by awilcoxa** [comment]
may need UX review, ready for developer pick up
