### ISSUE TITLE
[Documentation] Installing Venia sample data

### ISSUE THREAD

**Issue by jcalcaben** [magento-research/pwa-studio#86]
## This issue is for the following packages:

[ ] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[X] `pwa-devdocs`

## This issue is a:

[ ] Bug
[X] Feature suggestion
[X] Documentation issue
[ ] Other (Please Specify)

## Description

Create documentation for manually installing the modules that provide Venia-specific sample data into a Magento backend.

## Expected result:

A new topic is created for manually installing the following modules into Magento:

* https://github.com/PMET-public/module-catalog-sample-data-venia
* https://github.com/PMET-public/module-configurable-sample-data-venia
* https://github.com/PMET-public/module-customer-sample-data-venia
* https://github.com/PMET-public/module-sales-sample-data-venia
* https://github.com/PMET-public/module-tax-sample-data-venia
* https://github.com/PMET-public/sample-data-media-venia

**Comment by ericerway** [comment]
Updated to include new Venia sample data

**Comment by awilcoxa** [comment]
closing during backlog cleanup, topic was created and exists in current docs
