### ISSUE TITLE
"[BUG]" Venia Storybook Crash

### ISSUE THREAD

**Issue by supernova-at** [magento-research/pwa-studio#862]
**Describe the bug**
Running `yarn storybook:venia` results in the Storybook "red screen of death" with the error message:

> Module parse failed: Unexpected token (15:8) You may need an appropriate loader to handle this file type. | | return ( > <div style={styles}> | <BraintreeDropin onError={() => {}} onSuccess={() => {}} /> | </div>

**To Reproduce**
1. Checkout the latest of `release/2.0` branch. As of this writing it is [this commit](https://github.com/magento-research/pwa-studio/commit/625dd5130dd318f5c3166f97b6305ca028085638)
1. `yarn clean:all`
1. `yarn install`
1. `yarn build`
1. `yarn storybook:venia`

Observe the red screen of death.

**Expected behavior**
Storybook loads and behaves as expected.

**Screenshots**

![Screen Shot 2019-02-07 at 10.04.13 pm.png](https://images.zenhubusercontent.com/5bef16763560017fb6812f47/6c797a68-278f-4c1c-861d-cbcf32a19818)

**Please complete the following device information:**
 - Device: MacBook Pro
 - OS: macOS Mojave 10.14.2
 - Browser: Chrome
 - Version: 71
 - Node Version `node -v`: 10.15.0

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Possible solutions**

This likely has to do with some last minute additions to the Braintree PR that lazy loaded the `BraintreeDropin` component.

This may also have to do with a recent upgrade to React `16.8`.

**Comment by marcin-piekarski** [comment]
Running into the same issue as above.

Had a look at previous commits and found that `20ff0d13b4d1cbd0ac8d809cdcae19a5f5f355b5 - docs: Updated composer deprecated flag --repository-url (#789)` is works and 
`441b648147702737ecf2f10fe5639ca3ef73fdb5 - feat(devex): Refactor Venia to be portable and importable (#788)` breaks.

Hope that helps narrow things down a bit.
