### ISSUE TITLE
[DEVEX] Build process logs multiple console warnings when building Venia ES Modules

### ISSUE THREAD

**Issue by zetlen** [magento-research/pwa-studio#880]
**Describe the bug**
Since adding [babel-plugin-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver/) in #788, and a Babel compilation step which creates consumable ES Modules for third party projects, we've had a lot of noise in the Babel build output saying `Could not resolve '@magento/venia-drivers' in <path>`.

We put in a warning that these messages are normal and no problem, but it often scrolls by too fast to read--and it happens in dev mode too!

The cause is that we [configure the plugin to rewrite calls to the real file `/src/drivers` to an alias `@venia-concept/drivers`](https://github.com/magento-research/pwa-studio/blob/release/2.0/babel.config.js#L45-L68). The `@magento/venia-drivers` file doesn't really exist. When building Venia, we map it back to the real file [here](https://github.com/magento-research/pwa-studio/blob/release/2.0/packages/venia-concept/package.json#L9-L11), using [this specification](https://github.com/defunctzombie/package-browser-field-spec#replace-specific-files---advanced), but the idea is that third-party consumers using Venia modules should make [their own alias](https://github.com/magento-research/venia-consumer-example/blob/master/config/webpack.config.js#L269) to a replacement file.

However, `babel-plugin-module-resolver` doesn't expect this kind of "partial resolution" that happens in two steps, so in development mode it throws warnings when it can't locate the file it's mapping to. 

Unfortunately, this behavior is not easily configurable because it relies on a [global environment variable](https://github.com/tleunen/babel-plugin-module-resolver/blob/v3.1.3/src/resolvePath.js#L73-L75), which we don't want to set to `production` during the ESM build because that has other side effects. (We have a [pull request open](https://github.com/tleunen/babel-plugin-module-resolver/pull/351) to resolve this issue, but the maintainer @tleunen has not yet triaged it as of 2019/02/10).

**To Reproduce**
1. Checkout and install PWA Studio on branch `release/2.0`.
2. Run `yarn && yarn build`.

**Expected behavior**
Build output is not full of anxious warnings about missing modules.

**Screenshots**

![image](https://user-images.githubusercontent.com/1643758/52536358-128d5880-2d1f-11e9-8d8a-34eb5b3a0bec.png)

**Please complete the following device information:**
 - Device: All
 - OS: All
 - Browser N/A
 - Version N/A
 - Magento Version N/A
 - NPM version 6.4.1
 - Node Version 10.14.2

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

(Change is in the Venia-relevant portion of root `babel-config.js`.

**Additional context**
At some point, `babel-plugin-module-resolver` may not be the right choice here, as it's not designed for this.

**Possible solutions**
- Plugin maintainer merges PR
- We hack the env var

**Comment by sirugh** [comment]
3 hours ago the maintainer merged your PR to the resolver.  Looks like we can take the easy way out :D
