### ISSUE TITLE
Cart flashes/reloads twice when last cart item is removed.

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/pwa-studio#901]
Description:
Add product to cart and click on Remove Item link > Cart flashes (Shows "There are no item in your cart" now  displays Loading spinner and back to ""There are no item in your cart"" )

1. Go to Venia storefront and add a product to cart.
2. Now click on Remove Item option present under more options (3 vertical dots).

Expected behavior:
Shopping Cart right drawer should be displayed with "There are no items in your shopping cart" message with Continue shopping button.

Actual:
Shopping Cart right drawer displays message then shows loading icon and displays message.  This behavior needs to be changed.

**Comment by pradeep-cedcoss** [comment]
I am working on this at #dmcdindia1
