### ISSUE TITLE
[Docs]: Remove NPM from Modular install docs and promote Yarn

### ISSUE THREAD

**Issue by tonai** [magento-research/pwa-studio#907]
**Describe the bug**
Can't install package @magento/venia-concept with npm.
Ok with yarn.

**To Reproduce**
```bash
mkdir test
cd test
npm init
npm install @magento/venia-concept
```

**Expected behavior**
Module should install as expected (from the doc : https://magento-research.github.io/pwa-studio/venia-pwa-concept/features/modular-components/).

**Screenshots**
![capture d ecran de 2019-02-15 09-19-25](https://user-images.githubusercontent.com/5246045/52843756-4f809300-3103-11e9-8b1d-2c6188436ee5.png)

**Please complete the following device information:**
 - Device: PC
 - OS: Ubuntu 18.04
 - Browser: NA
 - Version: NA
 - Magento Version: 2.3
 - NPM version `npm -v`: 6.5.0
 - Node Version `node -v`: 11.7.0

**Please let us know what packages this bug is in regards to:**
- [X] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by awilcoxa** [comment]
Using yarn vs npm is now the recommended approach. We'll update docs to reflect this.
