### ISSUE TITLE
[BUG] Can't import components inside CRA app.

### ISSUE THREAD

**Issue by tonai** [magento-research/pwa-studio#908]
**Describe the bug**
Can't use `@magento/venia-concept` components inside an app created with `create-react-app`.

**To Reproduce**
Create a new app using  `create-react-app` and try to import the `App` component of `@magento/venia-concept`:
```js
import VeniaApp from '@magento/venia-concept/esm/components/App';
```
(Same happen when import `Product` component as suggested in the doc: https://magento-research.github.io/pwa-studio/venia-pwa-concept/features/modular-components/).

**Expected behavior**
To be able to use the component and build the application.

**Screenshots**
![capture d ecran de 2019-02-15 11-26-46](https://user-images.githubusercontent.com/5246045/52850787-acd11000-3114-11e9-9ad2-5e2b0908c5d6.png)

**Please complete the following device information:**
 - Device: PC
 - OS: Ubuntu 18.4
 - Browser: NA
 - Version: NA
 - Magento Version: 2.3
 - NPM version `npm -v`: 6.5.0
 - Node Version `node -v`: * 11.7.0

**Please let us know what packages this bug is in regards to:**
- [X] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Additional context**
Conventions seems to agree to use `.module.css` extension for CSS module files : https://github.com/css-modules/css-modules/issues/229

**Possible solutions**
`create-react-app` use this convention to compile css module files (compared to classic css files).

**Comment by tjwiebell** [comment]
If you wrap these components with a configured `VeniaAdapter`, they should function as expected. A simple component like `LoadingIndicator` that doesn't have `Link` or `Query` components in them should work without, if you're just looking to validate this is possible. There's more information in the documentation link you seem to be aware of:

https://magento-research.github.io/pwa-studio/venia-pwa-concept/features/modular-components/#venia-drivers-and-adapter

I'll leave this open until you've confirmed this resolves your problem.

**Comment by tonai** [comment]
Hi @tjwiebell , the components are wrapped.

But, it is not the usage of the components that is problematic, I did not reach this far because my app crash at compile time.

I can import `VeniaApp`, and event without using it, the compilation fail.

**Comment by awilcoxa** [comment]
@zetlen

**Comment by zetlen** [comment]
The documentation should have been clearer that using `@magento/venia-concept` as a dependency was a temporary approach. In the future we'll make it clearer when a page in our documentation is experimental.

Very soon, we will debut a better way to include Venia components and we will support it going forward. For now, @tonai, thank you for your patience; your best bet is to copy and paste code until we debut a better library structure.
