### ISSUE TITLE
[BUG] Create Account form input style is different from Sign In

### ISSUE THREAD

**Issue by JStein92** [magento-research/pwa-studio#912]
Create Account and Sign In components have different Input styles. 

createAccount.js uses `TextInput`
signIn uses `Input`

![image](https://user-images.githubusercontent.com/27716099/52971040-d5eade00-336a-11e9-8418-04b23d88499e.png)

![image](https://user-images.githubusercontent.com/27716099/52971056-e00cdc80-336a-11e9-960a-1567175d2e4e.png)

**Please complete the following device information:**
 - Device: [PC]
 - OS: [Ubuntu]
 - Browser [Chrome]

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Possible solutions**
Decide on one or the other.

**Comment by LucasCalazans** [comment]
Including more details, the layout on invision says that the first one should be used in both case.

Login: https://magento.invisionapp.com/share/WQN5F7BYBPG#/screens/318790635
Create Account: https://magento.invisionapp.com/share/WQN5F7BYBPG#/screens/320064949

**Comment by awilcoxa** [comment]
putting on hold pending response in PR from @LucasCalazans
