### ISSUE TITLE
Continue Shopping after Checkout

### ISSUE THREAD

**Issue by supernova-at** [magento-research/pwa-studio#916]
**Describe the bug**

After submitting a successful order, users are unable to add items to the cart.

**To Reproduce**
1. Add an item to the cart
1. Checkout and submit an order
1. Click "Continue Shopping" button
1. Attempt to add an item to the cart
1. Observe error notification on screen (and in browser console)

**Expected behavior**

Users should be able to add items to their cart after submitting an order.

**Screenshot**

![image.png](https://images.zenhubusercontent.com/5bef16763560017fb6812f47/a48c6ead-19cb-4a6c-a65c-b267d7497fe9)

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Additional context**

**Possible solutions**
A `guestCartId` isn't being created again after checkout.

**Comment by awilcoxa** [comment]
awaiting architecture review
