### ISSUE TITLE
Additional Billing Information Fields

### ISSUE THREAD

**Issue by supernova-at** [magento-research/pwa-studio#918]
When filling in a billing address during checkout, users sometimes choose not to use the same address as shipping.

In this case the billing address form needs to be updated to include all the fields required by the M2 backend for a successful address submission. 

This form is currently missing the following fields:

1. First name
1. Last name
1. Phone
1. Email

**Comment by lewisvoncken** [comment]
@supernova-at 
This is a duplicate issue and the other issue is more relevant so please close this one.

The following issue is more relevant:
https://github.com/magento-research/pwa-studio/issues/1154
