### ISSUE TITLE
PWA 2.0.0 Release Execution

### ISSUE THREAD

**Issue by awilcoxa** [magento-research/pwa-studio#923]
Issue to track all activity for PWA 2.0.0 Release. 

Current Action Items: 

- [x] Author & Merge Release Notes to ./changelog.md : @jcalcaben 
- [x] Approve/signoff build: @zetlen @jimbo @dpatil-magento 
- [x] Commit Release Notes: @jcalcaben @zetlen @jimbo 
- [x] Run release commands : @zetlen @jimbo 
- [x] Update UPWARD PHP with release version of UPWARD spec
- [x] Tag major release with UPWARD PHP repo 
- [x] In Github, create release from tag v2.0.0: @zetlen @jimbo 
- [x] Copy CHANGELOG to Github release details : @zetlen @jimbo 
- [x] Deploy to now.sh: @bbatsche @tjwiebell 
- [x] Verify deploys & scale configuration: @zetlen 
- [x] Publish devdocs: @jcalcaben 
- [x] Merge release 2.0.0 to master
- [x] Rebase all outstanding PRs on master 
- [ ] Create branch release/3.0
- [x] Celebrate/Shout from the rooftops @all 

Post-release activity: 
- [ ] Redirect veniapwa.com TO Cloud Pro  instance: @ericerway and Cloud team for DNS info

**Comment by awilcoxa** [comment]
@zetlen @jimbo  to set meeting with team to determine next steps for github branch management, independent activity from release

**Comment by supernova-at** [comment]
> @zetlen @jimbo to set meeting with team to determine next steps for github branch management, independent activity from release

[Here is a proposal](https://gist.github.com/supernova-at/1c6968a0ebaeb74fc728f8440bd3e649) for this.

**Comment by cherdman** [comment]
2.0.0 is released
