### ISSUE TITLE
Style : Load Both Css module and Css Stylesheet

### ISSUE THREAD

**Issue by herobk** [magento-research/pwa-studio#932]
Pwa use style-loader and css-loader to load css module.
                ```
 {
                    test: /\.css$/,
                    use: [
                        'style-loader',
                        {
                            loader: 'css-loader',
                            options: {
                                importLoaders: 1,
                                localIdentName:
                                    '[name]-[local]-[hash:base64:3]',
                                modules: true
                            }
                        }
                    ]
                },
```
But sometimes, I have to  use css stylesheet instead for specific class name and for some third library.
I just add in webpack.config.js :
```
{
        test: /\.custom.css$/,
        use: ['style-loader', 'css-loader']
},
```
It just load my custom.css file , but this way is only working when run at development mode, not for production mode .
**How can I load both css module and css stylesheet at production mode ?**

**Comment by Sharl212** [comment]
Surprised that this is still not answered.

**Comment by jimbo** [comment]
We recently updated [`webpack.config.js`](https://github.com/magento-research/pwa-studio/blob/develop/packages/venia-concept/webpack.config.js#L91-L120) to allow third-party CSS (from `node_modules`) to circumvent CSS Modules. That said, we recommend avoiding third-party CSS where possible.

**Comment by awilcoxa** [comment]
@SharlSherif let us know if you have any other questions on third-party CSS based on the answer from @jimbo above. If not we'll close this out.
