### ISSUE TITLE
DISCOVERY: PWA 2.0 REST queries to Magento 2.3.1 GraphQL 

### ISSUE THREAD

**Issue by awilcoxa** [magento-research/pwa-studio#953]
PWA studio should take advantage of new graphql features launched in 2.3.1 and replace existing REST queries in Venia. This discovery should result in a clear definition for LOE and scope of changes necessary to move any applicable queries from REST to GraphQL. 

## Remaining REST API usage in repo as of cf29cd6. 

See [here](https://devdocs.magento.com/redoc/2.3/guest-rest-api.html) for parameter/options.

### src/actions/cart/asyncActions.js
  - :white_check_mark: POST /rest/V1/guest-carts (can be replaced by `createEmptyCart` mutation)
  - :white_check_mark: POST /rest/V1/guest-carts/:cartId/items (replaceable by `addSimpleProductsToCart`/`addConfigurableProductsToCart` mutations)
  - :x: PUT /rest/V1/guest-carts/:cartId/items/:itemId (no replacement mutation exists)
  - :x: DELETE /rest/V1/guest-carts/:cartId/items/:itemId (no replacement mutation exists)
  - :x: GET /rest/V1/guest-carts/:cartId/payment-methods (no replacement query exists)
  - :x: GET /rest/V1/guest-carts/:cartId/totals (no replacement query exists. a `cart` query does exist, but it currently doesn't contain total information.)

### src/actions/checkout/asyncActions.js
  - ❌POST /rest/V1/guest-carts/:cartId/estimate-shipping-methods (no replaceable mutation exists)
  - ✅POST /rest/V1/guest-carts/:cartId/shipping-information (can be replaced by two mutations, `setShippingAddressesOnCart` and `setShippingMethodsOnCart`. there does appear to be some complexity here, it seems to expect cart items are passed with shipping addresses, I presume to support multi-address shipping)
  - ❌POST /rest/V1/guest-carts/:cartId/payment-information (no replacement mutation exists)

### src/actions/directory/asyncActions.js
  - ✅GET /rest/V1/directory/countries (can be replaced by `countries` query)

### src/actions/user/asyncActions.js
  - ✅POST /rest/V1/integration/customer/token (can be replaced by `generateCustomerToken` mutation)
  - ✅GET /rest/V1/customers/me (can be replaced by `customer` query)
  - ✅POST /rest/V1/customers (can be replaced by `createCustomer`)
  - ❌PUT /rest/V1/guest-carts/:cartId (no replacement mutation exists. if we wanted to migrate to GraphQL, I think you'd have to create a new cart and copy everything over from the old cart)

### src/components/CreateAccount/validators.js
  - ❌POST /rest/V1/customers/isEmailAvailable (no replacement mutation exists)

### src/actions/purchaseDetails/restApi.js
  - :x: MOCK orderDetailsRequest (`customerOrders` does exist, but the response structure is very light on detail, only contains total and status; no item detail either)

**Comment by sirugh** [comment]
It's been a little difficult to assess the possible graphql queries provided in `2.3.1` really because of a lack of docs/notes thus far. I'm currently talking to a few people from the team responsible for that work but in the meantime I was given a draft of the release notes so far. I then tried to extract any relevant tickets from the notes and put them in this issue above.

**Comment by tjwiebell** [comment]
@sirugh - Reviewed your findings and updated the description after confirming your suspicions about what could be replaced. I'll schedule some time with @awilcoxa to review, and break out into stories if this is deemed a priority.

**Comment by tjwiebell** [comment]
Some GraphQL features were postponed until 2.3.2, so this full assessment will apply to 2.3.2 instead. Three replacements can still be done against 2.3.1:
- mutation `createEmptyCart`
- query `countries`
- query `customer`

**Comment by tjwiebell** [comment]
Created #1013 epic to track this work.
