### ISSUE TITLE
DISCOVERY: Sample data availability for 2.3.1 new features

### ISSUE THREAD

**Issue by awilcoxa** [magento-research/pwa-studio#954]
2.3.1 launched new features in graphql, in order to build in and demonstrate the value in Venia we need to ensure that the backing sample data exists. Need to determine who owns making these changes/additions to the Venia sample data.

**Comment by dpatil-magento** [comment]
@cherdman While testing #955 observed all the products are not displaying on Venia storefront and its because sample data not indexed correctly as per @tjwiebell

**Comment by cherdman** [comment]
I discussed our need to modify the Venia sample data with Jeffrey Betts, who has agreed to help us make the necessary changes for 2.3.1. We will create a new issue to outline the required changes.
