### ISSUE TITLE
DISCOVERY: 2.3.1 Cloud Changes

### ISSUE THREAD

**Issue by awilcoxa** [magento-research/pwa-studio#955]
Identify necessary changes to UPWARD connector module, upward php library, and any existing deployment scripts

**Comment by tjwiebell** [comment]
Deployed 2.3.1 compatibility branch on a Magento Cloud Starter instance using magento-research/upward-php@1.0.0 and magento-research/magento2-upward-connector@1.0.0 here:

https://tommy-arhuwni-xjmpcdjpe6kzm.us-4.magentosite.cloud/

In my manual testing, I have found no new issues introduced with Magento 2.3.1, but should be validated by one more engineer.

**Comment by awilcoxa** [comment]
before closing can we get a review from @dpatil-magento

**Comment by dpatil-magento** [comment]
@tjwiebell  Seeing multiple observations when compared to https://dd2prod.dummycachetest.com
1. Data/Page loads slower.
2. All the products are not displaying under Tops, bottoms, Dresses category.
3. On Fresh browser > Say load "Accessories" category > Click on page navigation icon (i.e. > or >> or page number 2) > Now click Venia Home page icon > Now try accessing say Bottoms > Issue "Data fetch error"

<img width="902" alt="image" src="https://user-images.githubusercontent.com/40405790/53773818-8996b680-3eb1-11e9-9411-84b4f9dc924d.png">

**Comment by dpatil-magento** [comment]
Discussed with @tjwiebell  and observations not actual issues related to this ticket. 
1 - Slowness is because  cloud env is relatively small compared to dd2prod...
2 and 3 are because of #954.   Hence closing this issue.
