### ISSUE TITLE
Consider updating your .env file or environment variables to resolve the reported issues.

### ISSUE THREAD

**Issue by mssyogi** [magento-research/pwa-studio#959]
Hi,
 I am facing an issue when I try to run 
"yarn run build"
Issue: Consider updating your .env file or environment variables to resolve the reported issues.

Setup: 
Magento 2.3
yarn 1.13

-------------------------Error -----------------------------------
Using environment variables from .env
Validating queries based on schema at http://pwamagento.local/graphql...
Unexpected token < in JSON at position 209029

The current default backend for Venia development is:

	https://release-dev-rxvv2iq-zddsyhrdimyra.us-4.magentosite.cloud/

The configured MAGENTO_BACKEND_URL in the current environment is

	http://pwamagento.local/

Consider updating your .env file or environment variables to resolve the reported issues.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /home/lenovo/.nvm/versions/node/v10.7.0/bin/node
Arguments: /home/lenovo/.nvm/versions/node/v10.7.0/lib/node_modules/yarn/lib/cli.js build
Directory: /var/www/pwa-studio/packages/venia-concept
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspaces for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by sirugh** [comment]
This error could be occurring because your Magento instance at `pwamagento.local` is not set up correctly. Ensure that you are actually running a Magento 2.3 instance and try again! Please let us know if you continue to have problems after investigating.
