### ISSUE TITLE
Hosting PWA Studio on an external machine

### ISSUE THREAD

**Issue by rowan-m** [magento-research/pwa-studio#96]
## This issue is for the following packages:

- [X] `venia-concept`
- [X] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-module`
- [ ] `pwa-devdocs`

## This issue is a:

- [ ] Bug
- [x] Feature suggestion
- [x] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             | `2.3-develop@ce48579f46a74f34f572092697145a68bd758989` |
| Operating System + version  | `Ubuntu 18.04 LTS` |
| node.js version (`node -v`) | `v10.4.1` |
| npm version (`npm -v`)      | `6.1.0` |

## Description

Attempting to run the Venia theme on Google Compute Engine with a public facing URL. I've set up Magento with sample data and then installed the theme as per https://magento-research.github.io/pwa-studio/venia-pwa-concept/setup/

Magento appears to load as expected via the standard SSL port, i.e. it returns:
```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Venia</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <div id="root"></div>
    <script src="/pub/static/frontend/Magento/venia/en_US/client.js"></script>
  </body>
</html>
```

Running `~/src/pwa-studio/packages/venia-concept$ npm start` launches the devserver and it is accessible on port 8000 if I `curl` from the local instance. However, I can't get this through the firewall to access it remotely. I'm unsure exactly why this is - either the self signed cert or maybe it's only listening on a local interface. It does appear to be running the proxy properly through as `curl https://[host]:8000/pub/static/frontend/Magento/venia/en_US/client.js` returns the Webpack generated bundle.

## Expected result:

Hit an external URL on an arbitrary port and get the theme.

## Possible solutions:

A production configuration where I can just link in the generated bundle to serve through the existing nginx configuration would be great. Alternatively, a way the devserver can be exposed remotely.

**Comment by php4umagento** [comment]
Have exactly the same issue - changing .env file to host on external domain is still causing webpack to create a LOCAL server

It would be good to add more configuration options there so it can be passed to the nodejs server

**Comment by php4umagento** [comment]
I found solution how to fix that - https://webpack.js.org/configuration/dev-server/#devserver-public

**Comment by ericerway** [comment]
Reviewing some of our older issues -- @rowan-m can you confirm if this is still the case after all of the recent changes including UPWARD? Thanks!

**Comment by awilcoxa** [comment]
Closing issue given staleness
