### ISSUE TITLE
Running a Storefront in Production

### ISSUE THREAD

**Issue by supernova-at** [magento-research/pwa-studio#960]
There are many questions in the community along these lines:

> Looking for docs / cheatsheet / slack thread on newbies guide to going from Venia running locally on laptop using "yarn run watch:venia" to having it hosted "somewhere". Webpack/Yarn is still in the realm of dark arts for me, and unsure if Upward has its own requirements.

It would be a great help to the community if we could provide some guidance / documentation here.

**Comment by awilcoxa** [comment]
possible duplicate from other issue where answer was documented, I'll try to find that issue and close this out. Will still need to evaluate if we should formalize that into documentation.
