### ISSUE TITLE
Basic content for Venia (PWA)

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#97]
## This issue is for the following packages:

[X] `venia-concept`
[X] `pwa-buildpack`
[X] `peregrine`
[X] `pwa-module`
[X] `pwa-devdocs`

## This issue is a:

[ ] Bug
[X] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a shopper, I want to visit basic content from the Venia experience outside the checkout flow to inform my purchase and get help if I have a question or issue with an order placed.

Home
About Us
Customer Service
Privacy Policy
Contact Us
404 Error

## Expected result:

Fully developed content pages in Venia independent of data services and authentication. Sample content from prototype and data from product marketing team.

**Comment by awilcoxa** [comment]
Closing as complete
