### ISSUE TITLE
SyntaxError: src/ContainerChild/ContainerChild.js: Unexpected token (10:21)

### ISSUE THREAD

**Issue by maheshWebkul721** [magento-research/pwa-studio#970]
**Describe the bug**
When i run `npm run build` it gives the syntax error.

```js
> @magento/pwa-studio@2.0.0 build /home/mahesh-pwa/www/pwa1/pwa-studio
> yarn workspaces run build

yarn workspaces v1.13.0
yarn run v1.13.0
$ concurrently --raw yarn:build:cjs yarn:build:esm
$ BABEL_ENV=development babel src --out-dir esm --root-mode 'upward' --source-maps
$ BABEL_ENV=production babel src --out-dir dist --root-mode 'upward' --source-maps
SyntaxError: src/ContainerChild/ContainerChild.js: Unexpected token (10:21)
   8 | 
   9 | export default class ContainerChild extends Component {
> 10 |     static propTypes = {
     |                      ^
  11 |         id: string.isRequired,
  12 |         render: func.isRequired
  13 |     };
error Command failed with exit code 1.

```

**To Reproduce**
1. Setup venia as given: https://magento-research.github.io/pwa-studio/venia-pwa-concept/setup/ 

**Expected behavior**

**Screenshots**

**Please complete the following device information:**
 OS: Ubuntu
 - Magento Version 2.3
 - NPM version`v8.11.2` 
 - Node Version  `v5.6.0`

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Additional context**

**Possible solutions**
Add any ideas about possible solutions to the problem here.

**Comment by maheshWebkul721** [comment]
When i am runing : `yarn run build` after runing `yarn install`, i am getting below error.
```js
$ BABEL_ENV=development babel src --out-dir esm --root-mode 'upward' --source-maps --copy-files
SyntaxError: src/RootComponents/CMS/CMS.js: Unexpected token (6:15)
  4 | export default class CMS extends Component {
  5 |     render() {
> 6 |         return <CategoryList title="Shop by category" id={2} />;
    |                ^
  7 |     }
  8 | }
  9 | 
error C
```

**Comment by davoc** [comment]
I'm getting the exact same error. Cannot run PWA Studio as a result. Any news on this?

**Comment by sirugh** [comment]
Looks like this is due to incorrect versions of node/npm/yarn. If you look in the root `package.json` file you'll see the `engines` prop that requires node >= 10.7.0 and yarn >= 1.12.0. Please ensure you have installed the requisite versions.

If you have trouble running these commands and you are sure you are running the correct versions of node/yarn then please reopen an issue!

**Comment by lbrito55** [comment]
im having the same error @davoc  pointed out.

ubuntu@host:/var/www/html/magento2/pwa-studio$ nodejs --version
v11.12.0

ubuntu@host:/var/www/html/magento2/pwa-studio$ yarn --version
1.15.2

$ yarn run clean && yarn run build:esm && yarn run validate-queries && yarn run build:prod
$ rimraf dist esm
$ BABEL_ENV=development babel src --out-dir esm --root-mode 'upward' --source-maps --copy-files
SyntaxError: src/RootComponents/CMS/CMS.js: Unexpected token (6:15)
  4 | export default class CMS extends Component {
  5 |     render() {
> 6 |         return <CategoryList title="Shop by category" id={2} />;
    |                ^
  7 |     }
  8 | }
  9 |
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/bin/node
Arguments: /usr/share/yarn/lib/cli.js build
Directory: /var/www/html/magento2/pwa-studio/packages/venia-concept
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspaces for documentation about this command.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @magento/pwa-studio@2.1.0-dev build: `yarn workspaces run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @magento/pwa-studio@2.1.0-dev build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2019-03-21T07_13_35_689Z-debug.log

**Comment by JeoffScott** [comment]
> ![npm_build_error](https://user-images.githubusercontent.com/7751246/53896487-077ecd00-402c-11e9-9c3d-a25475dbf37d.png)
> I'm getting the exact same error. Cannot run PWA Studio as a result. Any news on this?

I have the same Issue

**Comment by maheshWebkul721** [comment]
@JeoffScott , have tried to run `sudo yarn run build`?

**Comment by maheshWebkul721** [comment]
@JeoffScott also use yarn to install node dependencies `yarn install` instead of `npm install`

**Comment by JeoffScott** [comment]
@maheshWebkul721 yes I tried
![image](https://user-images.githubusercontent.com/9309416/57233368-2a772e80-7027-11e9-8330-6be6357514f4.png)

**Comment by maheshWebkul721** [comment]
@JeoffScott , i was also having the same issue, then
1. I just cloned the fresh repository: `git clone https://github.com/magento-research/pwa-studio.git`
2. `cd pwa-studio`
3. run `yarn install`
4. change the magento instance url in .env
5. run `sudo yarn run build`
6. `yarn run watch:venia`

You can see that i am able to run venia project successfully.
![Screenshot_43](https://user-images.githubusercontent.com/32479280/57233995-67e6b680-703d-11e9-9b94-d80c0f4fda9b.png)

**Comment by JeoffScott** [comment]
@maheshWebkul721 what branch in repo do u use?

**Comment by maheshWebkul721** [comment]
@JeoffScott if you use `git clone https://github.com/magento-research/pwa-studio.git` it will clone from
tag `v2.1.0`

**Comment by maheshWebkul721** [comment]
@JeoffScott , also make sure you are using it with Magento 2.3.1 and set the Magento instance in
developer mode.

**Comment by umair-khanzada** [comment]
@JeoffScott Have you solved this issue I am facing the same one in windows 10.

![image](https://user-images.githubusercontent.com/8782817/60760653-1add8b80-a052-11e9-9e1f-c0c414f1cd65.png)
