### ISSUE TITLE
Peregrine: Left Drawer Component

### ISSUE THREAD

**Issue by awilcoxa** [magento-research/pwa-studio#977]
This story represents the effort to translate the left drawer component from Venia into Peregrine. Additional details to follow pending publish of @jimbo blog post via gist.

**Comment by supernova-at** [comment]
The left drawer component is also known as the "Navigation" component:

![Screen Shot 2019-05-01 at 2.13.18 PM.png](https://images.zenhubusercontent.com/5bef16763560017fb6812f47/59b9a07e-2055-41a6-a130-add3208348e2)

**Comment by supernova-at** [comment]
Closing as duplicate of #972.
