### ISSUE TITLE
Homepage for Venia

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#98]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[X] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## This issue is a:

[ ] Bug
[X] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a shopper, I want to browse the Venia homepage with the ability to find products that I am looking for so that I can make a purchase.

Prototype: https://magento.invisionapp.com/share/QWGTYLT7HNR#/291000408_Home_-_Fully_Loaded

Welcome banner
Header
Main navigation
User navigation

Content blocks:

Categories (8)
- Dresses
- Tops
- Bottoms
- Skirts
- Outerwear
- Accessories
- Shoes
- Jewelry

Promotional banner (for SALE!)
Coverflow (for New Arrivals)
Basic promo
Scrolling promo (for Recommendations)

Footer content
- Your Account
- Follow Us (external link) 
- Store Locator

## Expected result:

Fully built and tested homepage for Venia with PWA
Documentation (as appropriate)

**Comment by artKozinets** [comment]
Checked design. It is awesome!

Some comments and workaround.

@ericerway please check the comments, questions, suggestions... we can also make a short call if you want to discuss something specific.

**1. Header**

Let's keep the existing header (minimalist and compact)
![venia-header.png](https://images.zenhubusercontent.com/5b310669505d510c73d5f5e4/a2104ab5-6027-4cbe-aadb-80b28536859e)
 
 
 
**2. "Shop By Category"**

This section looks like a Sub Category block from main category.

**Options:**
- "Choose Main Category" -> show subcategories from;
- "Show child subcategories" -> 1, 2, 3....

Would be better to add new component.

![venia_02.png](https://images.zenhubusercontent.com/5b310669505d510c73d5f5e4/913ad7a3-8cf1-4956-9d01-509f1b835c00)


**3. "Sale" banner**

Just Image. "CMS Block" + PageBuilder or "CMS Page" + PageBuilder
![venia_03.png](https://images.zenhubusercontent.com/5b310669505d510c73d5f5e4/e1b23d22-ca39-496e-92e0-f73e7a13a799)


**4. "New Arrivals"**

Logicaly it is a block with products and some options, how to show it.

**Options:**
- "default" -> looks like a simple product grid;
- "slider" -> looks like a "New Arrivals" (main image + possibility to slide left and right );
- "gallery" -> looks like "Recommended for you" (main image + other images are as thumbnail at the bottom).

**Question:**

Where "See All New Arrivals" button should navigate to?

To NewArrivalsCategory / SearchResultPage / new module route...?

![venia_04.png](https://images.zenhubusercontent.com/5b310669505d510c73d5f5e4/0843c243-4862-47b3-a454-6aa2c1c1e8d0)


**5. "40% off outerwear" section.**

Just "CMS Block" + PageBuilder

![venia_05.png](https://images.zenhubusercontent.com/5b310669505d510c73d5f5e4/25fd7857-b84c-44ee-bd15-bbfae2fe989b)


**6. "Recommended for you" section**

Same as "New Arrivals"

**Question:** 

Where "See All Recommended" button should navigate to? To RecommendedCategory / SearchResultPage / new module route...


**Suggestion:** 

Magento Api does not provide any "Rating" data (
For first version lets do it without "Rating" label (bottom right on main image)

![venia_06.png](https://images.zenhubusercontent.com/5b310669505d510c73d5f5e4/a9982dc3-798a-4ced-b0c8-78398b246b95)


**7. "Shop The Look" section**

Just "CMS Block" + PageBuilder

![venia_07.png](https://images.zenhubusercontent.com/5b310669505d510c73d5f5e4/541cfca7-baab-467d-abee-2b5d189a1bd3)


**8. Footer section**

"CMS Block" + PageBuilder

![venia_09.png](https://images.zenhubusercontent.com/5b310669505d510c73d5f5e4/f0c5a8c7-e1a8-4779-9032-0b1c3042a7bc)

**Comment by ericerway** [comment]
Absolutely, let's talk about this after or during grooming on Friday when the team is back in the office. Copying @soumya-ashok and @jimbo for visibility. Thanks!

**Comment by soumya-ashok** [comment]
@artKozinets - The venia flower icon for the header and the static category images for the home page.
[venia-icon-logo.zip](https://github.com/magento-research/pwa-studio/files/2184272/venia-icon-logo.zip)
[veniapwa-home-categories.zip](https://github.com/magento-research/pwa-studio/files/2184292/veniapwa-home-categories.zip)

**Comment by soumya-ashok** [comment]
[veniapwa-category-images-home.zip](https://github.com/magento-research/pwa-studio/files/2207091/veniapwa-category-images-home.zip)
@artKozinets Here are the category images without any border and at a larger size.

**Comment by awilcoxa** [comment]
Removed open issues (which will remain in backlog for prioritization with additional homepage work). Calling homepage complete based on MVP definition and additional work will be schedule for iterative release.
