### ISSUE TITLE
Change Product components to use attribute collections instead of Venia custom attrs

### ISSUE THREAD

**Issue by zetlen** [magento-research/pwa-studio#983]
Venia currently uses a custom attribute `fashion_color` in its product detail query. This makes it strictly dependent on Venia sample data.

Like Luma, Venia is meant to be consumed in multiple contexts, so we need to change these queries to be agnostic and the components that use them to be agnostic.

Acceptance Criteria

- No direct custom attribute selection in any queries
- No switching off attribute names to pick options display
- Swatch display based on attribute metadata

**Comment by supernova-at** [comment]
`fashion_size` too

**Comment by awilcoxa** [comment]
@zetlen is this required for 2.3.1 compatibility? Or is this a nice to have?
