### ISSUE TITLE
[BUG] HTML special characters not displyaing properly.

### ISSUE THREAD

**Issue by yogeshsuhagiya** [magento-research/pwa-studio#984]
**Describe the bug**
HTML special characters like `&trade;` are not appearing properly on category and product detail page.

**To Reproduce**
1. Login into Magento 2 Backend
2. Goto 'Catalog > Products'
3. Search 'Carmina Earrings' product
4. Edit the product and replace the product name with `Carmina Earrings &trade;`
5. Now goto pwa studio's root directory and run the server `yarn run watch:venia`.
6. In navigation menu, click on *Accessories* menu and then open `Carmina Earrings` product.

**Expected behavior**
The product name should look like: `Carmina Earrings ™` instead of `Carmina Earrings &trade;`.

**Screenshots**
![screenshot_list](https://user-images.githubusercontent.com/783102/53713817-38b39d80-3e72-11e9-9d7b-74d27bfb31fa.png)
![screenshot_product_view](https://user-images.githubusercontent.com/783102/53713819-3cdfbb00-3e72-11e9-9fe0-45a47d81ba64.png)

**Please complete the following device information:**
 - Device: [e.g. iPhone6, PC]
 - OS: [e.g. iOS8.1, Windows 10]
 - Magento Version
 - NPM version `npm -v`
 - Node Version `node -v`

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Additional context**

**Possible solutions**
Add any ideas about possible solutions to the problem here.

**Comment by jimbo** [comment]
What happens if you put `™` directly in the product name, rather than the HTML entity `&trade;`?
